/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vportal.portlet.vcms.model.VcmsArticleStatus;
import com.vportal.portlet.vcms.model.VcmsArticleStatusModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the VcmsArticleStatus service. Represents a row in the &quot;VcmsArticleStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vcms.model.VcmsArticleStatusModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsArticleStatusImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a vcms article status model instance should use the {@link com.vportal.portlet.vcms.model.VcmsArticleStatus} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsArticleStatusImpl
 * @see com.vportal.portlet.vcms.model.VcmsArticleStatus
 * @see com.vportal.portlet.vcms.model.VcmsArticleStatusModel
 * @generated
 */
public class VcmsArticleStatusModelImpl extends BaseModelImpl<VcmsArticleStatus>
	implements VcmsArticleStatusModel {
	public static final String TABLE_NAME = "VcmsArticleStatus";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", new Integer(Types.BIGINT) },
			{ "statusId", new Integer(Types.BIGINT) },
			{ "articleId", new Integer(Types.VARCHAR) },
			{ "categoryId", new Integer(Types.VARCHAR) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "createdByUser", new Integer(Types.VARCHAR) },
			{ "active_", new Integer(Types.BOOLEAN) },
			{ "articleVersionId", new Integer(Types.BIGINT) }
		};
	public static final String TABLE_SQL_CREATE = "create table VcmsArticleStatus (id_ LONG not null primary key,statusId LONG,articleId VARCHAR(75) null,categoryId VARCHAR(75) null,createdDate DATE null,createdByUser VARCHAR(200) null,active_ BOOLEAN,articleVersionId LONG)";
	public static final String TABLE_SQL_DROP = "drop table VcmsArticleStatus";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsArticleStatus.createdDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsArticleStatus.createdDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vcms.model.VcmsArticleStatus"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vcms.model.VcmsArticleStatus"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vcms.model.VcmsArticleStatus"));

	public VcmsArticleStatusModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long pk) {
		setId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public long getStatusId() {
		return _statusId;
	}

	public void setStatusId(long statusId) {
		_statusId = statusId;
	}

	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	public void setArticleId(String articleId) {
		_articleId = articleId;
	}

	public String getCategoryId() {
		if (_categoryId == null) {
			return StringPool.BLANK;
		}
		else {
			return _categoryId;
		}
	}

	public void setCategoryId(String categoryId) {
		_categoryId = categoryId;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public String getCreatedByUser() {
		if (_createdByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdByUser;
		}
	}

	public void setCreatedByUser(String createdByUser) {
		_createdByUser = createdByUser;
	}

	public boolean getActive() {
		return _active;
	}

	public boolean isActive() {
		return _active;
	}

	public void setActive(boolean active) {
		_active = active;
	}

	public long getArticleVersionId() {
		return _articleVersionId;
	}

	public void setArticleVersionId(long articleVersionId) {
		_articleVersionId = articleVersionId;
	}

	public VcmsArticleStatus toEscapedModel() {
		if (isEscapedModel()) {
			return (VcmsArticleStatus)this;
		}
		else {
			return (VcmsArticleStatus)Proxy.newProxyInstance(VcmsArticleStatus.class.getClassLoader(),
				new Class[] { VcmsArticleStatus.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					VcmsArticleStatus.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		VcmsArticleStatusImpl vcmsArticleStatusImpl = new VcmsArticleStatusImpl();

		vcmsArticleStatusImpl.setId(getId());

		vcmsArticleStatusImpl.setStatusId(getStatusId());

		vcmsArticleStatusImpl.setArticleId(getArticleId());

		vcmsArticleStatusImpl.setCategoryId(getCategoryId());

		vcmsArticleStatusImpl.setCreatedDate(getCreatedDate());

		vcmsArticleStatusImpl.setCreatedByUser(getCreatedByUser());

		vcmsArticleStatusImpl.setActive(getActive());

		vcmsArticleStatusImpl.setArticleVersionId(getArticleVersionId());

		return vcmsArticleStatusImpl;
	}

	public int compareTo(VcmsArticleStatus vcmsArticleStatus) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				vcmsArticleStatus.getCreatedDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VcmsArticleStatus vcmsArticleStatus = null;

		try {
			vcmsArticleStatus = (VcmsArticleStatus)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = vcmsArticleStatus.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", statusId=");
		sb.append(getStatusId());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append(", categoryId=");
		sb.append(getCategoryId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", active=");
		sb.append(getActive());
		sb.append(", articleVersionId=");
		sb.append(getArticleVersionId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vcms.model.VcmsArticleStatus");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusId</column-name><column-value><![CDATA[");
		sb.append(getStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>categoryId</column-name><column-value><![CDATA[");
		sb.append(getCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleVersionId</column-name><column-value><![CDATA[");
		sb.append(getArticleVersionId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _id;
	private long _statusId;
	private String _articleId;
	private String _categoryId;
	private Date _createdDate;
	private String _createdByUser;
	private boolean _active;
	private long _articleVersionId;
	private transient ExpandoBridge _expandoBridge;
}