/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vcms.model.VcmsPARelation;
import com.vportal.portlet.vcms.model.VcmsPARelationModel;
import com.vportal.portlet.vcms.model.VcmsPARelationSoap;
import com.vportal.portlet.vcms.service.persistence.VcmsPARelationPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VcmsPARelation service. Represents a row in the &quot;VcmsPARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vcms.model.VcmsPARelationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsPARelationImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a vcms p a relation model instance should use the {@link com.vportal.portlet.vcms.model.VcmsPARelation} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsPARelationImpl
 * @see com.vportal.portlet.vcms.model.VcmsPARelation
 * @see com.vportal.portlet.vcms.model.VcmsPARelationModel
 * @generated
 */
public class VcmsPARelationModelImpl extends BaseModelImpl<VcmsPARelation>
	implements VcmsPARelationModel {
	public static final String TABLE_NAME = "VcmsPARelation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "portionId", new Integer(Types.VARCHAR) },
			{ "articleId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table VcmsPARelation (portionId VARCHAR(75) not null,articleId VARCHAR(75) not null,primary key (portionId, articleId))";
	public static final String TABLE_SQL_DROP = "drop table VcmsPARelation";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsPARelation.id.articleId DESC, vcmsPARelation.id.portionId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsPARelation.articleId DESC, VcmsPARelation.portionId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vcms.model.VcmsPARelation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vcms.model.VcmsPARelation"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VcmsPARelation toModel(VcmsPARelationSoap soapModel) {
		VcmsPARelation model = new VcmsPARelationImpl();

		model.setPortionId(soapModel.getPortionId());
		model.setArticleId(soapModel.getArticleId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VcmsPARelation> toModels(VcmsPARelationSoap[] soapModels) {
		List<VcmsPARelation> models = new ArrayList<VcmsPARelation>(soapModels.length);

		for (VcmsPARelationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vcms.model.VcmsPARelation"));

	public VcmsPARelationModelImpl() {
	}

	public VcmsPARelationPK getPrimaryKey() {
		return new VcmsPARelationPK(_portionId, _articleId);
	}

	public void setPrimaryKey(VcmsPARelationPK pk) {
		setPortionId(pk.portionId);
		setArticleId(pk.articleId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VcmsPARelationPK(_portionId, _articleId);
	}

	public String getPortionId() {
		if (_portionId == null) {
			return StringPool.BLANK;
		}
		else {
			return _portionId;
		}
	}

	public void setPortionId(String portionId) {
		_portionId = portionId;
	}

	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	public void setArticleId(String articleId) {
		_articleId = articleId;
	}

	public VcmsPARelation toEscapedModel() {
		if (isEscapedModel()) {
			return (VcmsPARelation)this;
		}
		else {
			return (VcmsPARelation)Proxy.newProxyInstance(VcmsPARelation.class.getClassLoader(),
				new Class[] { VcmsPARelation.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VcmsPARelationImpl vcmsPARelationImpl = new VcmsPARelationImpl();

		vcmsPARelationImpl.setPortionId(getPortionId());

		vcmsPARelationImpl.setArticleId(getArticleId());

		return vcmsPARelationImpl;
	}

	public int compareTo(VcmsPARelation vcmsPARelation) {
		int value = 0;

		value = getArticleId().compareTo(vcmsPARelation.getArticleId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getPortionId().compareTo(vcmsPARelation.getPortionId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VcmsPARelation vcmsPARelation = null;

		try {
			vcmsPARelation = (VcmsPARelation)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VcmsPARelationPK pk = vcmsPARelation.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{portionId=");
		sb.append(getPortionId());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vcms.model.VcmsPARelation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>portionId</column-name><column-value><![CDATA[");
		sb.append(getPortionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _portionId;
	private String _articleId;
}