/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vcms.model.VcmsCARelation;
import com.vportal.portlet.vcms.model.VcmsCARelationModel;
import com.vportal.portlet.vcms.model.VcmsCARelationSoap;
import com.vportal.portlet.vcms.service.persistence.VcmsCARelationPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the VcmsCARelation service. Represents a row in the &quot;VcmsCARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vcms.model.VcmsCARelationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsCARelationImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a vcms c a relation model instance should use the {@link com.vportal.portlet.vcms.model.VcmsCARelation} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsCARelationImpl
 * @see com.vportal.portlet.vcms.model.VcmsCARelation
 * @see com.vportal.portlet.vcms.model.VcmsCARelationModel
 * @generated
 */
public class VcmsCARelationModelImpl extends BaseModelImpl<VcmsCARelation>
	implements VcmsCARelationModel {
	public static final String TABLE_NAME = "VcmsCARelation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "categoryId", new Integer(Types.VARCHAR) },
			{ "articleId", new Integer(Types.VARCHAR) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "createdByUser", new Integer(Types.VARCHAR) },
			{ "status", new Integer(Types.BIGINT) }
		};
	public static final String TABLE_SQL_CREATE = "create table VcmsCARelation (categoryId VARCHAR(75) not null,articleId VARCHAR(75) not null,createdDate DATE null,createdByUser VARCHAR(75) null,status LONG,primary key (categoryId, articleId))";
	public static final String TABLE_SQL_DROP = "drop table VcmsCARelation";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsCARelation.id.articleId DESC, vcmsCARelation.id.categoryId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsCARelation.articleId DESC, VcmsCARelation.categoryId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vcms.model.VcmsCARelation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vcms.model.VcmsCARelation"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VcmsCARelation toModel(VcmsCARelationSoap soapModel) {
		VcmsCARelation model = new VcmsCARelationImpl();

		model.setCategoryId(soapModel.getCategoryId());
		model.setArticleId(soapModel.getArticleId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setCreatedByUser(soapModel.getCreatedByUser());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VcmsCARelation> toModels(VcmsCARelationSoap[] soapModels) {
		List<VcmsCARelation> models = new ArrayList<VcmsCARelation>(soapModels.length);

		for (VcmsCARelationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vcms.model.VcmsCARelation"));

	public VcmsCARelationModelImpl() {
	}

	public VcmsCARelationPK getPrimaryKey() {
		return new VcmsCARelationPK(_categoryId, _articleId);
	}

	public void setPrimaryKey(VcmsCARelationPK pk) {
		setCategoryId(pk.categoryId);
		setArticleId(pk.articleId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VcmsCARelationPK(_categoryId, _articleId);
	}

	public String getCategoryId() {
		if (_categoryId == null) {
			return StringPool.BLANK;
		}
		else {
			return _categoryId;
		}
	}

	public void setCategoryId(String categoryId) {
		_categoryId = categoryId;
	}

	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	public void setArticleId(String articleId) {
		_articleId = articleId;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public String getCreatedByUser() {
		if (_createdByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdByUser;
		}
	}

	public void setCreatedByUser(String createdByUser) {
		_createdByUser = createdByUser;
	}

	public long getStatus() {
		return _status;
	}

	public void setStatus(long status) {
		_status = status;
	}

	public VcmsCARelation toEscapedModel() {
		if (isEscapedModel()) {
			return (VcmsCARelation)this;
		}
		else {
			return (VcmsCARelation)Proxy.newProxyInstance(VcmsCARelation.class.getClassLoader(),
				new Class[] { VcmsCARelation.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VcmsCARelationImpl vcmsCARelationImpl = new VcmsCARelationImpl();

		vcmsCARelationImpl.setCategoryId(getCategoryId());

		vcmsCARelationImpl.setArticleId(getArticleId());

		vcmsCARelationImpl.setCreatedDate(getCreatedDate());

		vcmsCARelationImpl.setCreatedByUser(getCreatedByUser());

		vcmsCARelationImpl.setStatus(getStatus());

		return vcmsCARelationImpl;
	}

	public int compareTo(VcmsCARelation vcmsCARelation) {
		int value = 0;

		value = getArticleId().compareTo(vcmsCARelation.getArticleId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getCategoryId().compareTo(vcmsCARelation.getCategoryId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VcmsCARelation vcmsCARelation = null;

		try {
			vcmsCARelation = (VcmsCARelation)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VcmsCARelationPK pk = vcmsCARelation.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{categoryId=");
		sb.append(getCategoryId());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vcms.model.VcmsCARelation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>categoryId</column-name><column-value><![CDATA[");
		sb.append(getCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _categoryId;
	private String _articleId;
	private Date _createdDate;
	private String _createdByUser;
	private long _status;
}