/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcalendar.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VCal service. Represents a row in the &quot;VCal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcalendar.model.impl.VCalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcalendar.model.impl.VCalImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v cal model instance should use the {@link VCal} interface instead.
 * </p>
 *
 * @author Admin
 * @see VCal
 * @see com.vportal.portlet.vcalendar.model.impl.VCalImpl
 * @see com.vportal.portlet.vcalendar.model.impl.VCalModelImpl
 * @generated
 */
public interface VCalModel extends BaseModel<VCal> {
	/**
	 * Gets the primary key of this v cal.
	 *
	 * @return the primary key of this v cal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v cal
	 *
	 * @param pk the primary key of this v cal
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the cal id of this v cal.
	 *
	 * @return the cal id of this v cal
	 */
	public long getCalId();

	/**
	 * Sets the cal id of this v cal.
	 *
	 * @param calId the cal id of this v cal
	 */
	public void setCalId(long calId);

	/**
	 * Gets the group id of this v cal.
	 *
	 * @return the group id of this v cal
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this v cal.
	 *
	 * @param groupId the group id of this v cal
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this v cal.
	 *
	 * @return the company id of this v cal
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this v cal.
	 *
	 * @param companyId the company id of this v cal
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this v cal.
	 *
	 * @return the user id of this v cal
	 */
	public long getUserId();

	/**
	 * Sets the user id of this v cal.
	 *
	 * @param userId the user id of this v cal
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this v cal.
	 *
	 * @return the user uuid of this v cal
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v cal.
	 *
	 * @param userUuid the user uuid of this v cal
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this v cal.
	 *
	 * @return the user name of this v cal
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this v cal.
	 *
	 * @param userName the user name of this v cal
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this v cal.
	 *
	 * @return the create date of this v cal
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this v cal.
	 *
	 * @param createDate the create date of this v cal
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this v cal.
	 *
	 * @return the modified date of this v cal
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v cal.
	 *
	 * @param modifiedDate the modified date of this v cal
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the language id of this v cal.
	 *
	 * @return the language id of this v cal
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language id of this v cal.
	 *
	 * @param languageId the language id of this v cal
	 */
	public void setLanguageId(String languageId);

	/**
	 * Gets the file id of this v cal.
	 *
	 * @return the file id of this v cal
	 */
	public long getFileId();

	/**
	 * Sets the file id of this v cal.
	 *
	 * @param fileId the file id of this v cal
	 */
	public void setFileId(long fileId);

	/**
	 * Gets the title of this v cal.
	 *
	 * @return the title of this v cal
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this v cal.
	 *
	 * @param title the title of this v cal
	 */
	public void setTitle(String title);

	/**
	 * Gets the description of this v cal.
	 *
	 * @return the description of this v cal
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this v cal.
	 *
	 * @param description the description of this v cal
	 */
	public void setDescription(String description);

	/**
	 * Gets the guest of this v cal.
	 *
	 * @return the guest of this v cal
	 */
	@AutoEscape
	public String getGuest();

	/**
	 * Sets the guest of this v cal.
	 *
	 * @param guest the guest of this v cal
	 */
	public void setGuest(String guest);

	/**
	 * Gets the location of this v cal.
	 *
	 * @return the location of this v cal
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this v cal.
	 *
	 * @param location the location of this v cal
	 */
	public void setLocation(String location);

	/**
	 * Gets the time of this v cal.
	 *
	 * @return the time of this v cal
	 */
	@AutoEscape
	public String getTime();

	/**
	 * Sets the time of this v cal.
	 *
	 * @param time the time of this v cal
	 */
	public void setTime(String time);

	/**
	 * Gets the start date of this v cal.
	 *
	 * @return the start date of this v cal
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this v cal.
	 *
	 * @param startDate the start date of this v cal
	 */
	public void setStartDate(Date startDate);

	/**
	 * Gets the end date of this v cal.
	 *
	 * @return the end date of this v cal
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this v cal.
	 *
	 * @param endDate the end date of this v cal
	 */
	public void setEndDate(Date endDate);

	/**
	 * Gets the status of this v cal.
	 *
	 * @return the status of this v cal
	 */
	public int getStatus();

	/**
	 * Sets the status of this v cal.
	 *
	 * @param status the status of this v cal
	 */
	public void setStatus(int status);

	/**
	 * Gets a copy of this v cal as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VCal toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VCal vCal);

	public int hashCode();

	public String toString();

	public String toXmlString();
}