/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.vportal.portlet.vlegal.service.persistence.VLegalDFRelPK;

import java.io.Serializable;

/**
 * The base model interface for the VLegalDFRel service. Represents a row in the &quot;VLegalDFRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalDFRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalDFRelImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal d f rel model instance should use the {@link VLegalDFRel} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalDFRel
 * @see com.vportal.portlet.vlegal.model.impl.VLegalDFRelImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalDFRelModelImpl
 * @generated
 */
public interface VLegalDFRelModel extends BaseModel<VLegalDFRel> {
	/**
	 * Gets the primary key of this v legal d f rel.
	 *
	 * @return the primary key of this v legal d f rel
	 */
	public VLegalDFRelPK getPrimaryKey();

	/**
	 * Sets the primary key of this v legal d f rel
	 *
	 * @param pk the primary key of this v legal d f rel
	 */
	public void setPrimaryKey(VLegalDFRelPK pk);

	/**
	 * Gets the field id of this v legal d f rel.
	 *
	 * @return the field id of this v legal d f rel
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field id of this v legal d f rel.
	 *
	 * @param fieldId the field id of this v legal d f rel
	 */
	public void setFieldId(String fieldId);

	/**
	 * Gets the doc id of this v legal d f rel.
	 *
	 * @return the doc id of this v legal d f rel
	 */
	@AutoEscape
	public String getDocId();

	/**
	 * Sets the doc id of this v legal d f rel.
	 *
	 * @param docId the doc id of this v legal d f rel
	 */
	public void setDocId(String docId);

	/**
	 * Gets a copy of this v legal d f rel as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalDFRel toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalDFRel vLegalDFRel);

	public int hashCode();

	public String toString();

	public String toXmlString();
}