/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalDocument service. Represents a row in the &quot;VLegalDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalDocumentImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal document model instance should use the {@link VLegalDocument} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalDocument
 * @see com.vportal.portlet.vlegal.model.impl.VLegalDocumentImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalDocumentModelImpl
 * @generated
 */
public interface VLegalDocumentModel extends BaseModel<VLegalDocument> {
	/**
	 * Gets the primary key of this v legal document.
	 *
	 * @return the primary key of this v legal document
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal document
	 *
	 * @param pk the primary key of this v legal document
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the doc id of this v legal document.
	 *
	 * @return the doc id of this v legal document
	 */
	@AutoEscape
	public String getDocId();

	/**
	 * Sets the doc id of this v legal document.
	 *
	 * @param docId the doc id of this v legal document
	 */
	public void setDocId(String docId);

	/**
	 * Gets the group id of this v legal document.
	 *
	 * @return the group id of this v legal document
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this v legal document.
	 *
	 * @param groupId the group id of this v legal document
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this v legal document.
	 *
	 * @return the company id of this v legal document
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this v legal document.
	 *
	 * @param companyId the company id of this v legal document
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this v legal document.
	 *
	 * @return the user id of this v legal document
	 */
	public long getUserId();

	/**
	 * Sets the user id of this v legal document.
	 *
	 * @param userId the user id of this v legal document
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this v legal document.
	 *
	 * @return the user uuid of this v legal document
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v legal document.
	 *
	 * @param userUuid the user uuid of this v legal document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the created by user of this v legal document.
	 *
	 * @return the created by user of this v legal document
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal document.
	 *
	 * @param createdByUser the created by user of this v legal document
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Gets the created date of this v legal document.
	 *
	 * @return the created date of this v legal document
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal document.
	 *
	 * @param createdDate the created date of this v legal document
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the modified by user of this v legal document.
	 *
	 * @return the modified by user of this v legal document
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this v legal document.
	 *
	 * @param modifiedByUser the modified by user of this v legal document
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Gets the modified date of this v legal document.
	 *
	 * @return the modified date of this v legal document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal document.
	 *
	 * @param modifiedDate the modified date of this v legal document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the approved by user of this v legal document.
	 *
	 * @return the approved by user of this v legal document
	 */
	public long getApprovedByUser();

	/**
	 * Sets the approved by user of this v legal document.
	 *
	 * @param approvedByUser the approved by user of this v legal document
	 */
	public void setApprovedByUser(long approvedByUser);

	/**
	 * Gets the approved date of this v legal document.
	 *
	 * @return the approved date of this v legal document
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this v legal document.
	 *
	 * @param approvedDate the approved date of this v legal document
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Gets the forwarded by user of this v legal document.
	 *
	 * @return the forwarded by user of this v legal document
	 */
	public long getForwardedByUser();

	/**
	 * Sets the forwarded by user of this v legal document.
	 *
	 * @param forwardedByUser the forwarded by user of this v legal document
	 */
	public void setForwardedByUser(long forwardedByUser);

	/**
	 * Gets the forwarded date of this v legal document.
	 *
	 * @return the forwarded date of this v legal document
	 */
	public Date getForwardedDate();

	/**
	 * Sets the forwarded date of this v legal document.
	 *
	 * @param forwardedDate the forwarded date of this v legal document
	 */
	public void setForwardedDate(Date forwardedDate);

	/**
	 * Gets the published by user of this v legal document.
	 *
	 * @return the published by user of this v legal document
	 */
	public long getPublishedByUser();

	/**
	 * Sets the published by user of this v legal document.
	 *
	 * @param publishedByUser the published by user of this v legal document
	 */
	public void setPublishedByUser(long publishedByUser);

	/**
	 * Gets the published date of this v legal document.
	 *
	 * @return the published date of this v legal document
	 */
	public Date getPublishedDate();

	/**
	 * Sets the published date of this v legal document.
	 *
	 * @param publishedDate the published date of this v legal document
	 */
	public void setPublishedDate(Date publishedDate);

	/**
	 * Gets the symbol of this v legal document.
	 *
	 * @return the symbol of this v legal document
	 */
	@AutoEscape
	public String getSymbol();

	/**
	 * Sets the symbol of this v legal document.
	 *
	 * @param symbol the symbol of this v legal document
	 */
	public void setSymbol(String symbol);

	/**
	 * Gets the num of this v legal document.
	 *
	 * @return the num of this v legal document
	 */
	@AutoEscape
	public String getNum();

	/**
	 * Sets the num of this v legal document.
	 *
	 * @param num the num of this v legal document
	 */
	public void setNum(String num);

	/**
	 * Gets the promul date of this v legal document.
	 *
	 * @return the promul date of this v legal document
	 */
	public Date getPromulDate();

	/**
	 * Sets the promul date of this v legal document.
	 *
	 * @param promulDate the promul date of this v legal document
	 */
	public void setPromulDate(Date promulDate);

	/**
	 * Gets the effectived date of this v legal document.
	 *
	 * @return the effectived date of this v legal document
	 */
	public Date getEffectivedDate();

	/**
	 * Sets the effectived date of this v legal document.
	 *
	 * @param effectivedDate the effectived date of this v legal document
	 */
	public void setEffectivedDate(Date effectivedDate);

	/**
	 * Gets the expired date of this v legal document.
	 *
	 * @return the expired date of this v legal document
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this v legal document.
	 *
	 * @param expiredDate the expired date of this v legal document
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Gets the replace doc of this v legal document.
	 *
	 * @return the replace doc of this v legal document
	 */
	@AutoEscape
	public String getReplaceDoc();

	/**
	 * Sets the replace doc of this v legal document.
	 *
	 * @param replaceDoc the replace doc of this v legal document
	 */
	public void setReplaceDoc(String replaceDoc);

	/**
	 * Gets the summary of this v legal document.
	 *
	 * @return the summary of this v legal document
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this v legal document.
	 *
	 * @param summary the summary of this v legal document
	 */
	public void setSummary(String summary);

	/**
	 * Gets the content of this v legal document.
	 *
	 * @return the content of this v legal document
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this v legal document.
	 *
	 * @param content the content of this v legal document
	 */
	public void setContent(String content);

	/**
	 * Gets the language of this v legal document.
	 *
	 * @return the language of this v legal document
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this v legal document.
	 *
	 * @param language the language of this v legal document
	 */
	public void setLanguage(String language);

	/**
	 * Gets the user hit of this v legal document.
	 *
	 * @return the user hit of this v legal document
	 */
	public int getUserHit();

	/**
	 * Sets the user hit of this v legal document.
	 *
	 * @param userHit the user hit of this v legal document
	 */
	public void setUserHit(int userHit);

	/**
	 * Gets the status doc of this v legal document.
	 *
	 * @return the status doc of this v legal document
	 */
	public int getStatusDoc();

	/**
	 * Sets the status doc of this v legal document.
	 *
	 * @param statusDoc the status doc of this v legal document
	 */
	public void setStatusDoc(int statusDoc);

	/**
	 * Gets the has attachment of this v legal document.
	 *
	 * @return the has attachment of this v legal document
	 */
	public boolean getHasAttachment();

	/**
	 * Determines if this v legal document is has attachment.
	 *
	 * @return <code>true</code> if this v legal document is has attachment; <code>false</code> otherwise
	 */
	public boolean isHasAttachment();

	/**
	 * Sets whether this {$entity.humanName} is has attachment.
	 *
	 * @param hasAttachment the has attachment of this v legal document
	 */
	public void setHasAttachment(boolean hasAttachment);

	/**
	 * Gets the type doc id of this v legal document.
	 *
	 * @return the type doc id of this v legal document
	 */
	@AutoEscape
	public String getTypeDocId();

	/**
	 * Sets the type doc id of this v legal document.
	 *
	 * @param typeDocId the type doc id of this v legal document
	 */
	public void setTypeDocId(String typeDocId);

	/**
	 * Gets the field id of this v legal document.
	 *
	 * @return the field id of this v legal document
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field id of this v legal document.
	 *
	 * @param fieldId the field id of this v legal document
	 */
	public void setFieldId(String fieldId);

	/**
	 * Gets the org id of this v legal document.
	 *
	 * @return the org id of this v legal document
	 */
	@AutoEscape
	public String getOrgId();

	/**
	 * Sets the org id of this v legal document.
	 *
	 * @param orgId the org id of this v legal document
	 */
	public void setOrgId(String orgId);

	/**
	 * Gets the org rels of this v legal document.
	 *
	 * @return the org rels of this v legal document
	 */
	@AutoEscape
	public String getOrgRels();

	/**
	 * Sets the org rels of this v legal document.
	 *
	 * @param orgRels the org rels of this v legal document
	 */
	public void setOrgRels(String orgRels);

	/**
	 * Gets the signer rels of this v legal document.
	 *
	 * @return the signer rels of this v legal document
	 */
	@AutoEscape
	public String getSignerRels();

	/**
	 * Sets the signer rels of this v legal document.
	 *
	 * @param signerRels the signer rels of this v legal document
	 */
	public void setSignerRels(String signerRels);

	/**
	 * Gets the field rels of this v legal document.
	 *
	 * @return the field rels of this v legal document
	 */
	@AutoEscape
	public String getFieldRels();

	/**
	 * Sets the field rels of this v legal document.
	 *
	 * @param fieldRels the field rels of this v legal document
	 */
	public void setFieldRels(String fieldRels);

	/**
	 * Gets the num rels of this v legal document.
	 *
	 * @return the num rels of this v legal document
	 */
	@AutoEscape
	public String getNumRels();

	/**
	 * Sets the num rels of this v legal document.
	 *
	 * @param numRels the num rels of this v legal document
	 */
	public void setNumRels(String numRels);

	/**
	 * Gets the doc code of this v legal document.
	 *
	 * @return the doc code of this v legal document
	 */
	@AutoEscape
	public String getDocCode();

	/**
	 * Sets the doc code of this v legal document.
	 *
	 * @param docCode the doc code of this v legal document
	 */
	public void setDocCode(String docCode);

	/**
	 * Gets the department rels of this v legal document.
	 *
	 * @return the department rels of this v legal document
	 */
	@AutoEscape
	public String getDepartmentRels();

	/**
	 * Sets the department rels of this v legal document.
	 *
	 * @param departmentRels the department rels of this v legal document
	 */
	public void setDepartmentRels(String departmentRels);

	/**
	 * Gets a copy of this v legal document as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalDocument toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalDocument vLegalDocument);

	public int hashCode();

	public String toString();

	public String toXmlString();
}