/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalLogger service. Represents a row in the &quot;VLegalLogger&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalLoggerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalLoggerImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal logger model instance should use the {@link VLegalLogger} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalLogger
 * @see com.vportal.portlet.vlegal.model.impl.VLegalLoggerImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalLoggerModelImpl
 * @generated
 */
public interface VLegalLoggerModel extends BaseModel<VLegalLogger> {
	/**
	 * Gets the primary key of this v legal logger.
	 *
	 * @return the primary key of this v legal logger
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal logger
	 *
	 * @param pk the primary key of this v legal logger
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the logger id of this v legal logger.
	 *
	 * @return the logger id of this v legal logger
	 */
	@AutoEscape
	public String getLoggerId();

	/**
	 * Sets the logger id of this v legal logger.
	 *
	 * @param loggerId the logger id of this v legal logger
	 */
	public void setLoggerId(String loggerId);

	/**
	 * Gets the group id of this v legal logger.
	 *
	 * @return the group id of this v legal logger
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this v legal logger.
	 *
	 * @param groupId the group id of this v legal logger
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this v legal logger.
	 *
	 * @return the company id of this v legal logger
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this v legal logger.
	 *
	 * @param companyId the company id of this v legal logger
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this v legal logger.
	 *
	 * @return the user id of this v legal logger
	 */
	public long getUserId();

	/**
	 * Sets the user id of this v legal logger.
	 *
	 * @param userId the user id of this v legal logger
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this v legal logger.
	 *
	 * @return the user uuid of this v legal logger
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v legal logger.
	 *
	 * @param userUuid the user uuid of this v legal logger
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the created date of this v legal logger.
	 *
	 * @return the created date of this v legal logger
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal logger.
	 *
	 * @param createdDate the created date of this v legal logger
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the created by user of this v legal logger.
	 *
	 * @return the created by user of this v legal logger
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal logger.
	 *
	 * @param createdByUser the created by user of this v legal logger
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Gets the content of this v legal logger.
	 *
	 * @return the content of this v legal logger
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this v legal logger.
	 *
	 * @param content the content of this v legal logger
	 */
	public void setContent(String content);

	/**
	 * Gets a copy of this v legal logger as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalLogger toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalLogger vLegalLogger);

	public int hashCode();

	public String toString();

	public String toXmlString();
}