/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalField service. Represents a row in the &quot;VLegalField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalFieldModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalFieldImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal field model instance should use the {@link VLegalField} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalField
 * @see com.vportal.portlet.vlegal.model.impl.VLegalFieldImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalFieldModelImpl
 * @generated
 */
public interface VLegalFieldModel extends BaseModel<VLegalField> {
	/**
	 * Gets the primary key of this v legal field.
	 *
	 * @return the primary key of this v legal field
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal field
	 *
	 * @param pk the primary key of this v legal field
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the field id of this v legal field.
	 *
	 * @return the field id of this v legal field
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field id of this v legal field.
	 *
	 * @param fieldId the field id of this v legal field
	 */
	public void setFieldId(String fieldId);

	/**
	 * Gets the group id of this v legal field.
	 *
	 * @return the group id of this v legal field
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this v legal field.
	 *
	 * @param groupId the group id of this v legal field
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this v legal field.
	 *
	 * @return the company id of this v legal field
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this v legal field.
	 *
	 * @param companyId the company id of this v legal field
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this v legal field.
	 *
	 * @return the user id of this v legal field
	 */
	public long getUserId();

	/**
	 * Sets the user id of this v legal field.
	 *
	 * @param userId the user id of this v legal field
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this v legal field.
	 *
	 * @return the user uuid of this v legal field
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v legal field.
	 *
	 * @param userUuid the user uuid of this v legal field
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the created date of this v legal field.
	 *
	 * @return the created date of this v legal field
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal field.
	 *
	 * @param createdDate the created date of this v legal field
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the modified date of this v legal field.
	 *
	 * @return the modified date of this v legal field
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal field.
	 *
	 * @param modifiedDate the modified date of this v legal field
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the created by user of this v legal field.
	 *
	 * @return the created by user of this v legal field
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal field.
	 *
	 * @param createdByUser the created by user of this v legal field
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Gets the modified by user of this v legal field.
	 *
	 * @return the modified by user of this v legal field
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this v legal field.
	 *
	 * @param modifiedByUser the modified by user of this v legal field
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Gets the name of this v legal field.
	 *
	 * @return the name of this v legal field
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this v legal field.
	 *
	 * @param name the name of this v legal field
	 */
	public void setName(String name);

	/**
	 * Gets the description of this v legal field.
	 *
	 * @return the description of this v legal field
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this v legal field.
	 *
	 * @param description the description of this v legal field
	 */
	public void setDescription(String description);

	/**
	 * Gets the language of this v legal field.
	 *
	 * @return the language of this v legal field
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this v legal field.
	 *
	 * @param language the language of this v legal field
	 */
	public void setLanguage(String language);

	/**
	 * Gets the status field of this v legal field.
	 *
	 * @return the status field of this v legal field
	 */
	public boolean getStatusField();

	/**
	 * Determines if this v legal field is status field.
	 *
	 * @return <code>true</code> if this v legal field is status field; <code>false</code> otherwise
	 */
	public boolean isStatusField();

	/**
	 * Sets whether this {$entity.humanName} is status field.
	 *
	 * @param statusField the status field of this v legal field
	 */
	public void setStatusField(boolean statusField);

	/**
	 * Gets the rssable of this v legal field.
	 *
	 * @return the rssable of this v legal field
	 */
	public boolean getRssable();

	/**
	 * Determines if this v legal field is rssable.
	 *
	 * @return <code>true</code> if this v legal field is rssable; <code>false</code> otherwise
	 */
	public boolean isRssable();

	/**
	 * Sets whether this {$entity.humanName} is rssable.
	 *
	 * @param rssable the rssable of this v legal field
	 */
	public void setRssable(boolean rssable);

	/**
	 * Gets a copy of this v legal field as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalField toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalField vLegalField);

	public int hashCode();

	public String toString();

	public String toXmlString();
}