/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalSuggestDocument service. Represents a row in the &quot;VLegalSuggestDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalSuggestDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalSuggestDocumentImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal suggest document model instance should use the {@link VLegalSuggestDocument} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalSuggestDocument
 * @see com.vportal.portlet.vlegal.model.impl.VLegalSuggestDocumentImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalSuggestDocumentModelImpl
 * @generated
 */
public interface VLegalSuggestDocumentModel extends BaseModel<VLegalSuggestDocument> {
	/**
	 * Gets the primary key of this v legal suggest document.
	 *
	 * @return the primary key of this v legal suggest document
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal suggest document
	 *
	 * @param pk the primary key of this v legal suggest document
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the sug id of this v legal suggest document.
	 *
	 * @return the sug id of this v legal suggest document
	 */
	@AutoEscape
	public String getSugId();

	/**
	 * Sets the sug id of this v legal suggest document.
	 *
	 * @param sugId the sug id of this v legal suggest document
	 */
	public void setSugId(String sugId);

	/**
	 * Gets the group id of this v legal suggest document.
	 *
	 * @return the group id of this v legal suggest document
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this v legal suggest document.
	 *
	 * @param groupId the group id of this v legal suggest document
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this v legal suggest document.
	 *
	 * @return the company id of this v legal suggest document
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this v legal suggest document.
	 *
	 * @param companyId the company id of this v legal suggest document
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this v legal suggest document.
	 *
	 * @return the user id of this v legal suggest document
	 */
	public long getUserId();

	/**
	 * Sets the user id of this v legal suggest document.
	 *
	 * @param userId the user id of this v legal suggest document
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this v legal suggest document.
	 *
	 * @return the user uuid of this v legal suggest document
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v legal suggest document.
	 *
	 * @param userUuid the user uuid of this v legal suggest document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the created date of this v legal suggest document.
	 *
	 * @return the created date of this v legal suggest document
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal suggest document.
	 *
	 * @param createdDate the created date of this v legal suggest document
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the modified date of this v legal suggest document.
	 *
	 * @return the modified date of this v legal suggest document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal suggest document.
	 *
	 * @param modifiedDate the modified date of this v legal suggest document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the modified by user of this v legal suggest document.
	 *
	 * @return the modified by user of this v legal suggest document
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this v legal suggest document.
	 *
	 * @param modifiedByUser the modified by user of this v legal suggest document
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Gets the approved of this v legal suggest document.
	 *
	 * @return the approved of this v legal suggest document
	 */
	public boolean getApproved();

	/**
	 * Determines if this v legal suggest document is approved.
	 *
	 * @return <code>true</code> if this v legal suggest document is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this {$entity.humanName} is approved.
	 *
	 * @param approved the approved of this v legal suggest document
	 */
	public void setApproved(boolean approved);

	/**
	 * Gets the approved by user of this v legal suggest document.
	 *
	 * @return the approved by user of this v legal suggest document
	 */
	public long getApprovedByUser();

	/**
	 * Sets the approved by user of this v legal suggest document.
	 *
	 * @param approvedByUser the approved by user of this v legal suggest document
	 */
	public void setApprovedByUser(long approvedByUser);

	/**
	 * Gets the approved date of this v legal suggest document.
	 *
	 * @return the approved date of this v legal suggest document
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this v legal suggest document.
	 *
	 * @param approvedDate the approved date of this v legal suggest document
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Gets the title of this v legal suggest document.
	 *
	 * @return the title of this v legal suggest document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this v legal suggest document.
	 *
	 * @param title the title of this v legal suggest document
	 */
	public void setTitle(String title);

	/**
	 * Gets the content of this v legal suggest document.
	 *
	 * @return the content of this v legal suggest document
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this v legal suggest document.
	 *
	 * @param content the content of this v legal suggest document
	 */
	public void setContent(String content);

	/**
	 * Gets the language of this v legal suggest document.
	 *
	 * @return the language of this v legal suggest document
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this v legal suggest document.
	 *
	 * @param language the language of this v legal suggest document
	 */
	public void setLanguage(String language);

	/**
	 * Gets the visitor name of this v legal suggest document.
	 *
	 * @return the visitor name of this v legal suggest document
	 */
	@AutoEscape
	public String getVisitorName();

	/**
	 * Sets the visitor name of this v legal suggest document.
	 *
	 * @param visitorName the visitor name of this v legal suggest document
	 */
	public void setVisitorName(String visitorName);

	/**
	 * Gets the visitor email of this v legal suggest document.
	 *
	 * @return the visitor email of this v legal suggest document
	 */
	@AutoEscape
	public String getVisitorEmail();

	/**
	 * Sets the visitor email of this v legal suggest document.
	 *
	 * @param visitorEmail the visitor email of this v legal suggest document
	 */
	public void setVisitorEmail(String visitorEmail);

	/**
	 * Gets the visitor tel of this v legal suggest document.
	 *
	 * @return the visitor tel of this v legal suggest document
	 */
	@AutoEscape
	public String getVisitorTel();

	/**
	 * Sets the visitor tel of this v legal suggest document.
	 *
	 * @param visitorTel the visitor tel of this v legal suggest document
	 */
	public void setVisitorTel(String visitorTel);

	/**
	 * Gets the visitor address of this v legal suggest document.
	 *
	 * @return the visitor address of this v legal suggest document
	 */
	@AutoEscape
	public String getVisitorAddress();

	/**
	 * Sets the visitor address of this v legal suggest document.
	 *
	 * @param visitorAddress the visitor address of this v legal suggest document
	 */
	public void setVisitorAddress(String visitorAddress);

	/**
	 * Gets the draft id of this v legal suggest document.
	 *
	 * @return the draft id of this v legal suggest document
	 */
	@AutoEscape
	public String getDraftId();

	/**
	 * Sets the draft id of this v legal suggest document.
	 *
	 * @param draftId the draft id of this v legal suggest document
	 */
	public void setDraftId(String draftId);

	/**
	 * Gets the has attachment of this v legal suggest document.
	 *
	 * @return the has attachment of this v legal suggest document
	 */
	public boolean getHasAttachment();

	/**
	 * Determines if this v legal suggest document is has attachment.
	 *
	 * @return <code>true</code> if this v legal suggest document is has attachment; <code>false</code> otherwise
	 */
	public boolean isHasAttachment();

	/**
	 * Sets whether this {$entity.humanName} is has attachment.
	 *
	 * @param hasAttachment the has attachment of this v legal suggest document
	 */
	public void setHasAttachment(boolean hasAttachment);

	/**
	 * Gets a copy of this v legal suggest document as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalSuggestDocument toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalSuggestDocument vLegalSuggestDocument);

	public int hashCode();

	public String toString();

	public String toXmlString();
}