/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vcms.model.VcmsTARelation;
import com.vportal.portlet.vcms.model.VcmsTARelationModel;
import com.vportal.portlet.vcms.model.VcmsTARelationSoap;
import com.vportal.portlet.vcms.service.persistence.VcmsTARelationPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VcmsTARelation service. Represents a row in the &quot;VcmsTARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vcms.model.VcmsTARelationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsTARelationImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a vcms t a relation model instance should use the {@link com.vportal.portlet.vcms.model.VcmsTARelation} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsTARelationImpl
 * @see com.vportal.portlet.vcms.model.VcmsTARelation
 * @see com.vportal.portlet.vcms.model.VcmsTARelationModel
 * @generated
 */
public class VcmsTARelationModelImpl extends BaseModelImpl<VcmsTARelation>
	implements VcmsTARelationModel {
	public static final String TABLE_NAME = "VcmsTARelation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "threadId", new Integer(Types.VARCHAR) },
			{ "articleId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table VcmsTARelation (threadId VARCHAR(75) not null,articleId VARCHAR(75) not null,primary key (threadId, articleId))";
	public static final String TABLE_SQL_DROP = "drop table VcmsTARelation";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsTARelation.id.articleId DESC, vcmsTARelation.id.threadId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsTARelation.articleId DESC, VcmsTARelation.threadId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vcms.model.VcmsTARelation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vcms.model.VcmsTARelation"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VcmsTARelation toModel(VcmsTARelationSoap soapModel) {
		VcmsTARelation model = new VcmsTARelationImpl();

		model.setThreadId(soapModel.getThreadId());
		model.setArticleId(soapModel.getArticleId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VcmsTARelation> toModels(VcmsTARelationSoap[] soapModels) {
		List<VcmsTARelation> models = new ArrayList<VcmsTARelation>(soapModels.length);

		for (VcmsTARelationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vcms.model.VcmsTARelation"));

	public VcmsTARelationModelImpl() {
	}

	public VcmsTARelationPK getPrimaryKey() {
		return new VcmsTARelationPK(_threadId, _articleId);
	}

	public void setPrimaryKey(VcmsTARelationPK pk) {
		setThreadId(pk.threadId);
		setArticleId(pk.articleId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VcmsTARelationPK(_threadId, _articleId);
	}

	public String getThreadId() {
		if (_threadId == null) {
			return StringPool.BLANK;
		}
		else {
			return _threadId;
		}
	}

	public void setThreadId(String threadId) {
		_threadId = threadId;
	}

	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	public void setArticleId(String articleId) {
		_articleId = articleId;
	}

	public VcmsTARelation toEscapedModel() {
		if (isEscapedModel()) {
			return (VcmsTARelation)this;
		}
		else {
			return (VcmsTARelation)Proxy.newProxyInstance(VcmsTARelation.class.getClassLoader(),
				new Class[] { VcmsTARelation.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VcmsTARelationImpl vcmsTARelationImpl = new VcmsTARelationImpl();

		vcmsTARelationImpl.setThreadId(getThreadId());

		vcmsTARelationImpl.setArticleId(getArticleId());

		return vcmsTARelationImpl;
	}

	public int compareTo(VcmsTARelation vcmsTARelation) {
		int value = 0;

		value = getArticleId().compareTo(vcmsTARelation.getArticleId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getThreadId().compareTo(vcmsTARelation.getThreadId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VcmsTARelation vcmsTARelation = null;

		try {
			vcmsTARelation = (VcmsTARelation)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VcmsTARelationPK pk = vcmsTARelation.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{threadId=");
		sb.append(getThreadId());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vcms.model.VcmsTARelation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>threadId</column-name><column-value><![CDATA[");
		sb.append(getThreadId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _threadId;
	private String _articleId;
}