/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vportal.portlet.vcms.model.VcmsStatus;
import com.vportal.portlet.vcms.model.VcmsStatusModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the VcmsStatus service. Represents a row in the &quot;VcmsStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vcms.model.VcmsStatusModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsStatusImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a vcms status model instance should use the {@link com.vportal.portlet.vcms.model.VcmsStatus} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsStatusImpl
 * @see com.vportal.portlet.vcms.model.VcmsStatus
 * @see com.vportal.portlet.vcms.model.VcmsStatusModel
 * @generated
 */
public class VcmsStatusModelImpl extends BaseModelImpl<VcmsStatus>
	implements VcmsStatusModel {
	public static final String TABLE_NAME = "VcmsStatus";
	public static final Object[][] TABLE_COLUMNS = {
			{ "statusId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "createdByUser", new Integer(Types.VARCHAR) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedByUser", new Integer(Types.VARCHAR) },
			{ "name", new Integer(Types.VARCHAR) },
			{ "description", new Integer(Types.VARCHAR) },
			{ "cssClass", new Integer(Types.VARCHAR) },
			{ "textColor", new Integer(Types.VARCHAR) },
			{ "position", new Integer(Types.INTEGER) },
			{ "isPrimary", new Integer(Types.BOOLEAN) },
			{ "active_", new Integer(Types.BOOLEAN) }
		};
	public static final String TABLE_SQL_CREATE = "create table VcmsStatus (statusId LONG not null primary key,companyId LONG,groupId LONG,createdDate DATE null,createdByUser VARCHAR(75) null,modifiedDate DATE null,modifiedByUser VARCHAR(75) null,name VARCHAR(500) null,description VARCHAR(1000) null,cssClass VARCHAR(75) null,textColor VARCHAR(75) null,position INTEGER,isPrimary BOOLEAN,active_ BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table VcmsStatus";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsStatus.position ASC, vcmsStatus.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsStatus.position ASC, VcmsStatus.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vcms.model.VcmsStatus"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vcms.model.VcmsStatus"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vcms.model.VcmsStatus"));

	public VcmsStatusModelImpl() {
	}

	public long getPrimaryKey() {
		return _statusId;
	}

	public void setPrimaryKey(long pk) {
		setStatusId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_statusId);
	}

	public long getStatusId() {
		return _statusId;
	}

	public void setStatusId(long statusId) {
		_statusId = statusId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public String getCreatedByUser() {
		if (_createdByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdByUser;
		}
	}

	public void setCreatedByUser(String createdByUser) {
		_createdByUser = createdByUser;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public String getModifiedByUser() {
		if (_modifiedByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _modifiedByUser;
		}
	}

	public void setModifiedByUser(String modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public String getCssClass() {
		if (_cssClass == null) {
			return StringPool.BLANK;
		}
		else {
			return _cssClass;
		}
	}

	public void setCssClass(String cssClass) {
		_cssClass = cssClass;
	}

	public String getTextColor() {
		if (_textColor == null) {
			return StringPool.BLANK;
		}
		else {
			return _textColor;
		}
	}

	public void setTextColor(String textColor) {
		_textColor = textColor;
	}

	public int getPosition() {
		return _position;
	}

	public void setPosition(int position) {
		_position = position;
	}

	public boolean getIsPrimary() {
		return _isPrimary;
	}

	public boolean isIsPrimary() {
		return _isPrimary;
	}

	public void setIsPrimary(boolean isPrimary) {
		if (!_setOriginalIsPrimary) {
			_setOriginalIsPrimary = true;

			_originalIsPrimary = _isPrimary;
		}

		_isPrimary = isPrimary;
	}

	public boolean getOriginalIsPrimary() {
		return _originalIsPrimary;
	}

	public boolean getActive() {
		return _active;
	}

	public boolean isActive() {
		return _active;
	}

	public void setActive(boolean active) {
		if (!_setOriginalActive) {
			_setOriginalActive = true;

			_originalActive = _active;
		}

		_active = active;
	}

	public boolean getOriginalActive() {
		return _originalActive;
	}

	public VcmsStatus toEscapedModel() {
		if (isEscapedModel()) {
			return (VcmsStatus)this;
		}
		else {
			return (VcmsStatus)Proxy.newProxyInstance(VcmsStatus.class.getClassLoader(),
				new Class[] { VcmsStatus.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					VcmsStatus.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		VcmsStatusImpl vcmsStatusImpl = new VcmsStatusImpl();

		vcmsStatusImpl.setStatusId(getStatusId());

		vcmsStatusImpl.setCompanyId(getCompanyId());

		VcmsStatusModelImpl vcmsStatusModelImpl = vcmsStatusImpl;

		vcmsStatusModelImpl._originalCompanyId = vcmsStatusModelImpl._companyId;

		vcmsStatusModelImpl._setOriginalCompanyId = false;
		vcmsStatusImpl.setGroupId(getGroupId());

		vcmsStatusModelImpl._originalGroupId = vcmsStatusModelImpl._groupId;

		vcmsStatusModelImpl._setOriginalGroupId = false;
		vcmsStatusImpl.setCreatedDate(getCreatedDate());

		vcmsStatusImpl.setCreatedByUser(getCreatedByUser());

		vcmsStatusImpl.setModifiedDate(getModifiedDate());

		vcmsStatusImpl.setModifiedByUser(getModifiedByUser());

		vcmsStatusImpl.setName(getName());

		vcmsStatusImpl.setDescription(getDescription());

		vcmsStatusImpl.setCssClass(getCssClass());

		vcmsStatusImpl.setTextColor(getTextColor());

		vcmsStatusImpl.setPosition(getPosition());

		vcmsStatusImpl.setIsPrimary(getIsPrimary());

		vcmsStatusModelImpl._originalIsPrimary = vcmsStatusModelImpl._isPrimary;

		vcmsStatusModelImpl._setOriginalIsPrimary = false;
		vcmsStatusImpl.setActive(getActive());

		vcmsStatusModelImpl._originalActive = vcmsStatusModelImpl._active;

		vcmsStatusModelImpl._setOriginalActive = false;

		return vcmsStatusImpl;
	}

	public int compareTo(VcmsStatus vcmsStatus) {
		int value = 0;

		if (getPosition() < vcmsStatus.getPosition()) {
			value = -1;
		}
		else if (getPosition() > vcmsStatus.getPosition()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreatedDate(), vcmsStatus.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VcmsStatus vcmsStatus = null;

		try {
			vcmsStatus = (VcmsStatus)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = vcmsStatus.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{statusId=");
		sb.append(getStatusId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", cssClass=");
		sb.append(getCssClass());
		sb.append(", textColor=");
		sb.append(getTextColor());
		sb.append(", position=");
		sb.append(getPosition());
		sb.append(", isPrimary=");
		sb.append(getIsPrimary());
		sb.append(", active=");
		sb.append(getActive());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vcms.model.VcmsStatus");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>statusId</column-name><column-value><![CDATA[");
		sb.append(getStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cssClass</column-name><column-value><![CDATA[");
		sb.append(getCssClass());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>textColor</column-name><column-value><![CDATA[");
		sb.append(getTextColor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position</column-name><column-value><![CDATA[");
		sb.append(getPosition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isPrimary</column-name><column-value><![CDATA[");
		sb.append(getIsPrimary());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _statusId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private Date _createdDate;
	private String _createdByUser;
	private Date _modifiedDate;
	private String _modifiedByUser;
	private String _name;
	private String _description;
	private String _cssClass;
	private String _textColor;
	private int _position;
	private boolean _isPrimary;
	private boolean _originalIsPrimary;
	private boolean _setOriginalIsPrimary;
	private boolean _active;
	private boolean _originalActive;
	private boolean _setOriginalActive;
	private transient ExpandoBridge _expandoBridge;
}