/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vcms.model.VcmsDiscussion;
import com.vportal.portlet.vcms.model.VcmsDiscussionModel;
import com.vportal.portlet.vcms.model.VcmsDiscussionSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the VcmsDiscussion service. Represents a row in the &quot;VcmsDiscussion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vcms.model.VcmsDiscussionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VcmsDiscussionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a vcms discussion model instance should use the {@link com.vportal.portlet.vcms.model.VcmsDiscussion} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsDiscussionImpl
 * @see com.vportal.portlet.vcms.model.VcmsDiscussion
 * @see com.vportal.portlet.vcms.model.VcmsDiscussionModel
 * @generated
 */
public class VcmsDiscussionModelImpl extends BaseModelImpl<VcmsDiscussion>
	implements VcmsDiscussionModel {
	public static final String TABLE_NAME = "VcmsDiscussion";
	public static final Object[][] TABLE_COLUMNS = {
			{ "discussionId", new Integer(Types.VARCHAR) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "visitorName", new Integer(Types.VARCHAR) },
			{ "visitorEmail", new Integer(Types.VARCHAR) },
			{ "visitorPhone", new Integer(Types.VARCHAR) },
			{ "postedDate", new Integer(Types.TIMESTAMP) },
			{ "approved", new Integer(Types.BOOLEAN) },
			{ "approvedByUser", new Integer(Types.VARCHAR) },
			{ "approvedDate", new Integer(Types.TIMESTAMP) },
			{ "articleId", new Integer(Types.VARCHAR) },
			{ "title", new Integer(Types.VARCHAR) },
			{ "content", new Integer(Types.VARCHAR) },
			{ "language", new Integer(Types.VARCHAR) },
			{ "hasAttachment", new Integer(Types.BOOLEAN) }
		};
	public static final String TABLE_SQL_CREATE = "create table VcmsDiscussion (discussionId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,visitorName VARCHAR(200) null,visitorEmail VARCHAR(200) null,visitorPhone VARCHAR(200) null,postedDate DATE null,approved BOOLEAN,approvedByUser VARCHAR(75) null,approvedDate DATE null,articleId VARCHAR(75) null,title VARCHAR(500) null,content TEXT null,language VARCHAR(75) null,hasAttachment BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table VcmsDiscussion";
	public static final String ORDER_BY_JPQL = " ORDER BY vcmsDiscussion.postedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VcmsDiscussion.postedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vcms.model.VcmsDiscussion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vcms.model.VcmsDiscussion"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VcmsDiscussion toModel(VcmsDiscussionSoap soapModel) {
		VcmsDiscussion model = new VcmsDiscussionImpl();

		model.setDiscussionId(soapModel.getDiscussionId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setVisitorName(soapModel.getVisitorName());
		model.setVisitorEmail(soapModel.getVisitorEmail());
		model.setVisitorPhone(soapModel.getVisitorPhone());
		model.setPostedDate(soapModel.getPostedDate());
		model.setApproved(soapModel.getApproved());
		model.setApprovedByUser(soapModel.getApprovedByUser());
		model.setApprovedDate(soapModel.getApprovedDate());
		model.setArticleId(soapModel.getArticleId());
		model.setTitle(soapModel.getTitle());
		model.setContent(soapModel.getContent());
		model.setLanguage(soapModel.getLanguage());
		model.setHasAttachment(soapModel.getHasAttachment());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VcmsDiscussion> toModels(VcmsDiscussionSoap[] soapModels) {
		List<VcmsDiscussion> models = new ArrayList<VcmsDiscussion>(soapModels.length);

		for (VcmsDiscussionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vcms.model.VcmsDiscussion"));

	public VcmsDiscussionModelImpl() {
	}

	public String getPrimaryKey() {
		return _discussionId;
	}

	public void setPrimaryKey(String pk) {
		setDiscussionId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return _discussionId;
	}

	public String getDiscussionId() {
		if (_discussionId == null) {
			return StringPool.BLANK;
		}
		else {
			return _discussionId;
		}
	}

	public void setDiscussionId(String discussionId) {
		_discussionId = discussionId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public String getVisitorName() {
		if (_visitorName == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitorName;
		}
	}

	public void setVisitorName(String visitorName) {
		_visitorName = visitorName;
	}

	public String getVisitorEmail() {
		if (_visitorEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitorEmail;
		}
	}

	public void setVisitorEmail(String visitorEmail) {
		_visitorEmail = visitorEmail;
	}

	public String getVisitorPhone() {
		if (_visitorPhone == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitorPhone;
		}
	}

	public void setVisitorPhone(String visitorPhone) {
		_visitorPhone = visitorPhone;
	}

	public Date getPostedDate() {
		return _postedDate;
	}

	public void setPostedDate(Date postedDate) {
		_postedDate = postedDate;
	}

	public boolean getApproved() {
		return _approved;
	}

	public boolean isApproved() {
		return _approved;
	}

	public void setApproved(boolean approved) {
		_approved = approved;
	}

	public String getApprovedByUser() {
		if (_approvedByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _approvedByUser;
		}
	}

	public void setApprovedByUser(String approvedByUser) {
		_approvedByUser = approvedByUser;
	}

	public Date getApprovedDate() {
		return _approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		_approvedDate = approvedDate;
	}

	public String getArticleId() {
		if (_articleId == null) {
			return StringPool.BLANK;
		}
		else {
			return _articleId;
		}
	}

	public void setArticleId(String articleId) {
		_articleId = articleId;
	}

	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	public void setTitle(String title) {
		_title = title;
	}

	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	public void setContent(String content) {
		_content = content;
	}

	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	public void setLanguage(String language) {
		_language = language;
	}

	public boolean getHasAttachment() {
		return _hasAttachment;
	}

	public boolean isHasAttachment() {
		return _hasAttachment;
	}

	public void setHasAttachment(boolean hasAttachment) {
		_hasAttachment = hasAttachment;
	}

	public VcmsDiscussion toEscapedModel() {
		if (isEscapedModel()) {
			return (VcmsDiscussion)this;
		}
		else {
			return (VcmsDiscussion)Proxy.newProxyInstance(VcmsDiscussion.class.getClassLoader(),
				new Class[] { VcmsDiscussion.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VcmsDiscussionImpl vcmsDiscussionImpl = new VcmsDiscussionImpl();

		vcmsDiscussionImpl.setDiscussionId(getDiscussionId());

		vcmsDiscussionImpl.setGroupId(getGroupId());

		vcmsDiscussionImpl.setCompanyId(getCompanyId());

		vcmsDiscussionImpl.setVisitorName(getVisitorName());

		vcmsDiscussionImpl.setVisitorEmail(getVisitorEmail());

		vcmsDiscussionImpl.setVisitorPhone(getVisitorPhone());

		vcmsDiscussionImpl.setPostedDate(getPostedDate());

		vcmsDiscussionImpl.setApproved(getApproved());

		vcmsDiscussionImpl.setApprovedByUser(getApprovedByUser());

		vcmsDiscussionImpl.setApprovedDate(getApprovedDate());

		vcmsDiscussionImpl.setArticleId(getArticleId());

		vcmsDiscussionImpl.setTitle(getTitle());

		vcmsDiscussionImpl.setContent(getContent());

		vcmsDiscussionImpl.setLanguage(getLanguage());

		vcmsDiscussionImpl.setHasAttachment(getHasAttachment());

		return vcmsDiscussionImpl;
	}

	public int compareTo(VcmsDiscussion vcmsDiscussion) {
		int value = 0;

		value = DateUtil.compareTo(getPostedDate(),
				vcmsDiscussion.getPostedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VcmsDiscussion vcmsDiscussion = null;

		try {
			vcmsDiscussion = (VcmsDiscussion)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String pk = vcmsDiscussion.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{discussionId=");
		sb.append(getDiscussionId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", visitorName=");
		sb.append(getVisitorName());
		sb.append(", visitorEmail=");
		sb.append(getVisitorEmail());
		sb.append(", visitorPhone=");
		sb.append(getVisitorPhone());
		sb.append(", postedDate=");
		sb.append(getPostedDate());
		sb.append(", approved=");
		sb.append(getApproved());
		sb.append(", approvedByUser=");
		sb.append(getApprovedByUser());
		sb.append(", approvedDate=");
		sb.append(getApprovedDate());
		sb.append(", articleId=");
		sb.append(getArticleId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", hasAttachment=");
		sb.append(getHasAttachment());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vcms.model.VcmsDiscussion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>discussionId</column-name><column-value><![CDATA[");
		sb.append(getDiscussionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitorName</column-name><column-value><![CDATA[");
		sb.append(getVisitorName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitorEmail</column-name><column-value><![CDATA[");
		sb.append(getVisitorEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitorPhone</column-name><column-value><![CDATA[");
		sb.append(getVisitorPhone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postedDate</column-name><column-value><![CDATA[");
		sb.append(getPostedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approved</column-name><column-value><![CDATA[");
		sb.append(getApproved());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approvedByUser</column-name><column-value><![CDATA[");
		sb.append(getApprovedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approvedDate</column-name><column-value><![CDATA[");
		sb.append(getApprovedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>articleId</column-name><column-value><![CDATA[");
		sb.append(getArticleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hasAttachment</column-name><column-value><![CDATA[");
		sb.append(getHasAttachment());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _discussionId;
	private long _groupId;
	private long _companyId;
	private String _visitorName;
	private String _visitorEmail;
	private String _visitorPhone;
	private Date _postedDate;
	private boolean _approved;
	private String _approvedByUser;
	private Date _approvedDate;
	private String _articleId;
	private String _title;
	private String _content;
	private String _language;
	private boolean _hasAttachment;
}