/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcalendar.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VFile service. Represents a row in the &quot;VFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcalendar.model.impl.VFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcalendar.model.impl.VFileImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v file model instance should use the {@link VFile} interface instead.
 * </p>
 *
 * @author Admin
 * @see VFile
 * @see com.vportal.portlet.vcalendar.model.impl.VFileImpl
 * @see com.vportal.portlet.vcalendar.model.impl.VFileModelImpl
 * @generated
 */
public interface VFileModel extends BaseModel<VFile> {
	/**
	 * Gets the primary key of this v file.
	 *
	 * @return the primary key of this v file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this v file
	 *
	 * @param pk the primary key of this v file
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the file id of this v file.
	 *
	 * @return the file id of this v file
	 */
	public long getFileId();

	/**
	 * Sets the file id of this v file.
	 *
	 * @param fileId the file id of this v file
	 */
	public void setFileId(long fileId);

	/**
	 * Gets the fullname of this v file.
	 *
	 * @return the fullname of this v file
	 */
	@AutoEscape
	public String getFullname();

	/**
	 * Sets the fullname of this v file.
	 *
	 * @param fullname the fullname of this v file
	 */
	public void setFullname(String fullname);

	/**
	 * Gets the phone of this v file.
	 *
	 * @return the phone of this v file
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this v file.
	 *
	 * @param phone the phone of this v file
	 */
	public void setPhone(String phone);

	/**
	 * Gets the address of this v file.
	 *
	 * @return the address of this v file
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this v file.
	 *
	 * @param address the address of this v file
	 */
	public void setAddress(String address);

	/**
	 * Gets the birthday of this v file.
	 *
	 * @return the birthday of this v file
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this v file.
	 *
	 * @param birthday the birthday of this v file
	 */
	public void setBirthday(Date birthday);

	/**
	 * Gets the position of this v file.
	 *
	 * @return the position of this v file
	 */
	@AutoEscape
	public String getPosition();

	/**
	 * Sets the position of this v file.
	 *
	 * @param position the position of this v file
	 */
	public void setPosition(String position);

	/**
	 * Gets the status of this v file.
	 *
	 * @return the status of this v file
	 */
	public int getStatus();

	/**
	 * Sets the status of this v file.
	 *
	 * @param status the status of this v file
	 */
	public void setStatus(int status);

	/**
	 * Gets a copy of this v file as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VFile toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VFile vFile);

	public int hashCode();

	public String toString();

	public String toXmlString();
}