/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsLogger service. Represents a row in the &quot;VcmsLogger&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsLoggerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsLoggerImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a vcms logger model instance should use the {@link VcmsLogger} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsLogger
 * @see com.vportal.portlet.vcms.model.impl.VcmsLoggerImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsLoggerModelImpl
 * @generated
 */
public interface VcmsLoggerModel extends BaseModel<VcmsLogger> {
	/**
	 * Gets the primary key of this vcms logger.
	 *
	 * @return the primary key of this vcms logger
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vcms logger
	 *
	 * @param pk the primary key of this vcms logger
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the logger id of this vcms logger.
	 *
	 * @return the logger id of this vcms logger
	 */
	@AutoEscape
	public String getLoggerId();

	/**
	 * Sets the logger id of this vcms logger.
	 *
	 * @param loggerId the logger id of this vcms logger
	 */
	public void setLoggerId(String loggerId);

	/**
	 * Gets the group id of this vcms logger.
	 *
	 * @return the group id of this vcms logger
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this vcms logger.
	 *
	 * @param groupId the group id of this vcms logger
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this vcms logger.
	 *
	 * @return the company id of this vcms logger
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this vcms logger.
	 *
	 * @param companyId the company id of this vcms logger
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the created date of this vcms logger.
	 *
	 * @return the created date of this vcms logger
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms logger.
	 *
	 * @param createdDate the created date of this vcms logger
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the created by user of this vcms logger.
	 *
	 * @return the created by user of this vcms logger
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms logger.
	 *
	 * @param createdByUser the created by user of this vcms logger
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Gets the content of this vcms logger.
	 *
	 * @return the content of this vcms logger
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this vcms logger.
	 *
	 * @param content the content of this vcms logger
	 */
	public void setContent(String content);

	/**
	 * Gets a copy of this vcms logger as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VcmsLogger toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsLogger vcmsLogger);

	public int hashCode();

	public String toString();

	public String toXmlString();
}