/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsType service. Represents a row in the &quot;VcmsType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsTypeImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a vcms type model instance should use the {@link VcmsType} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsType
 * @see com.vportal.portlet.vcms.model.impl.VcmsTypeImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsTypeModelImpl
 * @generated
 */
public interface VcmsTypeModel extends BaseModel<VcmsType> {
	/**
	 * Gets the primary key of this vcms type.
	 *
	 * @return the primary key of this vcms type
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vcms type
	 *
	 * @param pk the primary key of this vcms type
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the type id of this vcms type.
	 *
	 * @return the type id of this vcms type
	 */
	@AutoEscape
	public String getTypeId();

	/**
	 * Sets the type id of this vcms type.
	 *
	 * @param typeId the type id of this vcms type
	 */
	public void setTypeId(String typeId);

	/**
	 * Gets the group id of this vcms type.
	 *
	 * @return the group id of this vcms type
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this vcms type.
	 *
	 * @param groupId the group id of this vcms type
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this vcms type.
	 *
	 * @return the company id of this vcms type
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this vcms type.
	 *
	 * @param companyId the company id of this vcms type
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the created date of this vcms type.
	 *
	 * @return the created date of this vcms type
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms type.
	 *
	 * @param createdDate the created date of this vcms type
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the created by user of this vcms type.
	 *
	 * @return the created by user of this vcms type
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms type.
	 *
	 * @param createdByUser the created by user of this vcms type
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Gets the modified date of this vcms type.
	 *
	 * @return the modified date of this vcms type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vcms type.
	 *
	 * @param modifiedDate the modified date of this vcms type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the modified by user of this vcms type.
	 *
	 * @return the modified by user of this vcms type
	 */
	@AutoEscape
	public String getModifiedByUser();

	/**
	 * Sets the modified by user of this vcms type.
	 *
	 * @param modifiedByUser the modified by user of this vcms type
	 */
	public void setModifiedByUser(String modifiedByUser);

	/**
	 * Gets the code of this vcms type.
	 *
	 * @return the code of this vcms type
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this vcms type.
	 *
	 * @param code the code of this vcms type
	 */
	public void setCode(String code);

	/**
	 * Gets the name of this vcms type.
	 *
	 * @return the name of this vcms type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this vcms type.
	 *
	 * @param name the name of this vcms type
	 */
	public void setName(String name);

	/**
	 * Gets the description of this vcms type.
	 *
	 * @return the description of this vcms type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vcms type.
	 *
	 * @param description the description of this vcms type
	 */
	public void setDescription(String description);

	/**
	 * Gets the language of this vcms type.
	 *
	 * @return the language of this vcms type
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vcms type.
	 *
	 * @param language the language of this vcms type
	 */
	public void setLanguage(String language);

	/**
	 * Gets a copy of this vcms type as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VcmsType toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsType vcmsType);

	public int hashCode();

	public String toString();

	public String toXmlString();
}