/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsArticleStatus service. Represents a row in the &quot;VcmsArticleStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsArticleStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsArticleStatusImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a vcms article status model instance should use the {@link VcmsArticleStatus} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsArticleStatus
 * @see com.vportal.portlet.vcms.model.impl.VcmsArticleStatusImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsArticleStatusModelImpl
 * @generated
 */
public interface VcmsArticleStatusModel extends BaseModel<VcmsArticleStatus> {
	/**
	 * Gets the primary key of this vcms article status.
	 *
	 * @return the primary key of this vcms article status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vcms article status
	 *
	 * @param pk the primary key of this vcms article status
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the id of this vcms article status.
	 *
	 * @return the id of this vcms article status
	 */
	public long getId();

	/**
	 * Sets the id of this vcms article status.
	 *
	 * @param id the id of this vcms article status
	 */
	public void setId(long id);

	/**
	 * Gets the status id of this vcms article status.
	 *
	 * @return the status id of this vcms article status
	 */
	public long getStatusId();

	/**
	 * Sets the status id of this vcms article status.
	 *
	 * @param statusId the status id of this vcms article status
	 */
	public void setStatusId(long statusId);

	/**
	 * Gets the article id of this vcms article status.
	 *
	 * @return the article id of this vcms article status
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article id of this vcms article status.
	 *
	 * @param articleId the article id of this vcms article status
	 */
	public void setArticleId(String articleId);

	/**
	 * Gets the category id of this vcms article status.
	 *
	 * @return the category id of this vcms article status
	 */
	@AutoEscape
	public String getCategoryId();

	/**
	 * Sets the category id of this vcms article status.
	 *
	 * @param categoryId the category id of this vcms article status
	 */
	public void setCategoryId(String categoryId);

	/**
	 * Gets the created date of this vcms article status.
	 *
	 * @return the created date of this vcms article status
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms article status.
	 *
	 * @param createdDate the created date of this vcms article status
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the created by user of this vcms article status.
	 *
	 * @return the created by user of this vcms article status
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms article status.
	 *
	 * @param createdByUser the created by user of this vcms article status
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Gets the active of this vcms article status.
	 *
	 * @return the active of this vcms article status
	 */
	public boolean getActive();

	/**
	 * Determines if this vcms article status is active.
	 *
	 * @return <code>true</code> if this vcms article status is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this {$entity.humanName} is active.
	 *
	 * @param active the active of this vcms article status
	 */
	public void setActive(boolean active);

	/**
	 * Gets the article version id of this vcms article status.
	 *
	 * @return the article version id of this vcms article status
	 */
	public long getArticleVersionId();

	/**
	 * Sets the article version id of this vcms article status.
	 *
	 * @param articleVersionId the article version id of this vcms article status
	 */
	public void setArticleVersionId(long articleVersionId);

	/**
	 * Gets a copy of this vcms article status as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VcmsArticleStatus toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsArticleStatus vcmsArticleStatus);

	public int hashCode();

	public String toString();

	public String toXmlString();
}