/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vlegal.model.VLegalFTRel;
import com.vportal.portlet.vlegal.model.VLegalFTRelModel;
import com.vportal.portlet.vlegal.model.VLegalFTRelSoap;
import com.vportal.portlet.vlegal.service.persistence.VLegalFTRelPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VLegalFTRel service. Represents a row in the &quot;VLegalFTRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalFTRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalFTRelImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal f t rel model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalFTRel} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalFTRelImpl
 * @see com.vportal.portlet.vlegal.model.VLegalFTRel
 * @see com.vportal.portlet.vlegal.model.VLegalFTRelModel
 * @generated
 */
public class VLegalFTRelModelImpl extends BaseModelImpl<VLegalFTRel>
	implements VLegalFTRelModel {
	public static final String TABLE_NAME = "VLegalFTRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fieldId", new Integer(Types.VARCHAR) },
			{ "typeId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalFTRel (fieldId VARCHAR(75) not null,typeId VARCHAR(75) not null,primary key (fieldId, typeId))";
	public static final String TABLE_SQL_DROP = "drop table VLegalFTRel";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalFTRel.id.fieldId DESC, vLegalFTRel.id.typeId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalFTRel.fieldId DESC, VLegalFTRel.typeId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalFTRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalFTRel"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalFTRel toModel(VLegalFTRelSoap soapModel) {
		VLegalFTRel model = new VLegalFTRelImpl();

		model.setFieldId(soapModel.getFieldId());
		model.setTypeId(soapModel.getTypeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalFTRel> toModels(VLegalFTRelSoap[] soapModels) {
		List<VLegalFTRel> models = new ArrayList<VLegalFTRel>(soapModels.length);

		for (VLegalFTRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalFTRel"));

	public VLegalFTRelModelImpl() {
	}

	public VLegalFTRelPK getPrimaryKey() {
		return new VLegalFTRelPK(_fieldId, _typeId);
	}

	public void setPrimaryKey(VLegalFTRelPK pk) {
		setFieldId(pk.fieldId);
		setTypeId(pk.typeId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VLegalFTRelPK(_fieldId, _typeId);
	}

	public String getFieldId() {
		if (_fieldId == null) {
			return StringPool.BLANK;
		}
		else {
			return _fieldId;
		}
	}

	public void setFieldId(String fieldId) {
		_fieldId = fieldId;
	}

	public String getTypeId() {
		if (_typeId == null) {
			return StringPool.BLANK;
		}
		else {
			return _typeId;
		}
	}

	public void setTypeId(String typeId) {
		_typeId = typeId;
	}

	public VLegalFTRel toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalFTRel)this;
		}
		else {
			return (VLegalFTRel)Proxy.newProxyInstance(VLegalFTRel.class.getClassLoader(),
				new Class[] { VLegalFTRel.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalFTRelImpl vLegalFTRelImpl = new VLegalFTRelImpl();

		vLegalFTRelImpl.setFieldId(getFieldId());

		vLegalFTRelImpl.setTypeId(getTypeId());

		return vLegalFTRelImpl;
	}

	public int compareTo(VLegalFTRel vLegalFTRel) {
		int value = 0;

		value = getFieldId().compareTo(vLegalFTRel.getFieldId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getTypeId().compareTo(vLegalFTRel.getTypeId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalFTRel vLegalFTRel = null;

		try {
			vLegalFTRel = (VLegalFTRel)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VLegalFTRelPK pk = vLegalFTRel.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{fieldId=");
		sb.append(getFieldId());
		sb.append(", typeId=");
		sb.append(getTypeId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalFTRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fieldId</column-name><column-value><![CDATA[");
		sb.append(getFieldId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typeId</column-name><column-value><![CDATA[");
		sb.append(getTypeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _fieldId;
	private String _typeId;
}