/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vlegal.model.VLegalDSRel;
import com.vportal.portlet.vlegal.model.VLegalDSRelModel;
import com.vportal.portlet.vlegal.model.VLegalDSRelSoap;
import com.vportal.portlet.vlegal.service.persistence.VLegalDSRelPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VLegalDSRel service. Represents a row in the &quot;VLegalDSRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalDSRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalDSRelImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal d s rel model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalDSRel} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalDSRelImpl
 * @see com.vportal.portlet.vlegal.model.VLegalDSRel
 * @see com.vportal.portlet.vlegal.model.VLegalDSRelModel
 * @generated
 */
public class VLegalDSRelModelImpl extends BaseModelImpl<VLegalDSRel>
	implements VLegalDSRelModel {
	public static final String TABLE_NAME = "VLegalDSRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "sigId", new Integer(Types.VARCHAR) },
			{ "docId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalDSRel (sigId VARCHAR(75) not null,docId VARCHAR(75) not null,primary key (sigId, docId))";
	public static final String TABLE_SQL_DROP = "drop table VLegalDSRel";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalDSRel.id.sigId DESC, vLegalDSRel.id.docId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalDSRel.sigId DESC, VLegalDSRel.docId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalDSRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalDSRel"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalDSRel toModel(VLegalDSRelSoap soapModel) {
		VLegalDSRel model = new VLegalDSRelImpl();

		model.setSigId(soapModel.getSigId());
		model.setDocId(soapModel.getDocId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalDSRel> toModels(VLegalDSRelSoap[] soapModels) {
		List<VLegalDSRel> models = new ArrayList<VLegalDSRel>(soapModels.length);

		for (VLegalDSRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalDSRel"));

	public VLegalDSRelModelImpl() {
	}

	public VLegalDSRelPK getPrimaryKey() {
		return new VLegalDSRelPK(_sigId, _docId);
	}

	public void setPrimaryKey(VLegalDSRelPK pk) {
		setSigId(pk.sigId);
		setDocId(pk.docId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VLegalDSRelPK(_sigId, _docId);
	}

	public String getSigId() {
		if (_sigId == null) {
			return StringPool.BLANK;
		}
		else {
			return _sigId;
		}
	}

	public void setSigId(String sigId) {
		_sigId = sigId;
	}

	public String getDocId() {
		if (_docId == null) {
			return StringPool.BLANK;
		}
		else {
			return _docId;
		}
	}

	public void setDocId(String docId) {
		_docId = docId;
	}

	public VLegalDSRel toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalDSRel)this;
		}
		else {
			return (VLegalDSRel)Proxy.newProxyInstance(VLegalDSRel.class.getClassLoader(),
				new Class[] { VLegalDSRel.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalDSRelImpl vLegalDSRelImpl = new VLegalDSRelImpl();

		vLegalDSRelImpl.setSigId(getSigId());

		vLegalDSRelImpl.setDocId(getDocId());

		return vLegalDSRelImpl;
	}

	public int compareTo(VLegalDSRel vLegalDSRel) {
		int value = 0;

		value = getSigId().compareTo(vLegalDSRel.getSigId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getDocId().compareTo(vLegalDSRel.getDocId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalDSRel vLegalDSRel = null;

		try {
			vLegalDSRel = (VLegalDSRel)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VLegalDSRelPK pk = vLegalDSRel.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{sigId=");
		sb.append(getSigId());
		sb.append(", docId=");
		sb.append(getDocId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalDSRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>sigId</column-name><column-value><![CDATA[");
		sb.append(getSigId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>docId</column-name><column-value><![CDATA[");
		sb.append(getDocId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _sigId;
	private String _docId;
}