/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vlegal.model.VLegalFORel;
import com.vportal.portlet.vlegal.model.VLegalFORelModel;
import com.vportal.portlet.vlegal.model.VLegalFORelSoap;
import com.vportal.portlet.vlegal.service.persistence.VLegalFORelPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VLegalFORel service. Represents a row in the &quot;VLegalFORel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalFORelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalFORelImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal f o rel model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalFORel} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalFORelImpl
 * @see com.vportal.portlet.vlegal.model.VLegalFORel
 * @see com.vportal.portlet.vlegal.model.VLegalFORelModel
 * @generated
 */
public class VLegalFORelModelImpl extends BaseModelImpl<VLegalFORel>
	implements VLegalFORelModel {
	public static final String TABLE_NAME = "VLegalFORel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fieldId", new Integer(Types.VARCHAR) },
			{ "orgId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalFORel (fieldId VARCHAR(75) not null,orgId VARCHAR(75) not null,primary key (fieldId, orgId))";
	public static final String TABLE_SQL_DROP = "drop table VLegalFORel";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalFORel.id.fieldId DESC, vLegalFORel.id.orgId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalFORel.fieldId DESC, VLegalFORel.orgId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalFORel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalFORel"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalFORel toModel(VLegalFORelSoap soapModel) {
		VLegalFORel model = new VLegalFORelImpl();

		model.setFieldId(soapModel.getFieldId());
		model.setOrgId(soapModel.getOrgId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalFORel> toModels(VLegalFORelSoap[] soapModels) {
		List<VLegalFORel> models = new ArrayList<VLegalFORel>(soapModels.length);

		for (VLegalFORelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalFORel"));

	public VLegalFORelModelImpl() {
	}

	public VLegalFORelPK getPrimaryKey() {
		return new VLegalFORelPK(_fieldId, _orgId);
	}

	public void setPrimaryKey(VLegalFORelPK pk) {
		setFieldId(pk.fieldId);
		setOrgId(pk.orgId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VLegalFORelPK(_fieldId, _orgId);
	}

	public String getFieldId() {
		if (_fieldId == null) {
			return StringPool.BLANK;
		}
		else {
			return _fieldId;
		}
	}

	public void setFieldId(String fieldId) {
		_fieldId = fieldId;
	}

	public String getOrgId() {
		if (_orgId == null) {
			return StringPool.BLANK;
		}
		else {
			return _orgId;
		}
	}

	public void setOrgId(String orgId) {
		_orgId = orgId;
	}

	public VLegalFORel toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalFORel)this;
		}
		else {
			return (VLegalFORel)Proxy.newProxyInstance(VLegalFORel.class.getClassLoader(),
				new Class[] { VLegalFORel.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalFORelImpl vLegalFORelImpl = new VLegalFORelImpl();

		vLegalFORelImpl.setFieldId(getFieldId());

		vLegalFORelImpl.setOrgId(getOrgId());

		return vLegalFORelImpl;
	}

	public int compareTo(VLegalFORel vLegalFORel) {
		int value = 0;

		value = getFieldId().compareTo(vLegalFORel.getFieldId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getOrgId().compareTo(vLegalFORel.getOrgId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalFORel vLegalFORel = null;

		try {
			vLegalFORel = (VLegalFORel)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VLegalFORelPK pk = vLegalFORel.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{fieldId=");
		sb.append(getFieldId());
		sb.append(", orgId=");
		sb.append(getOrgId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalFORel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fieldId</column-name><column-value><![CDATA[");
		sb.append(getFieldId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orgId</column-name><column-value><![CDATA[");
		sb.append(getOrgId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _fieldId;
	private String _orgId;
}