/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vlegal.model.VLegalDFRel;
import com.vportal.portlet.vlegal.model.VLegalDFRelModel;
import com.vportal.portlet.vlegal.model.VLegalDFRelSoap;
import com.vportal.portlet.vlegal.service.persistence.VLegalDFRelPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VLegalDFRel service. Represents a row in the &quot;VLegalDFRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalDFRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalDFRelImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal d f rel model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalDFRel} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalDFRelImpl
 * @see com.vportal.portlet.vlegal.model.VLegalDFRel
 * @see com.vportal.portlet.vlegal.model.VLegalDFRelModel
 * @generated
 */
public class VLegalDFRelModelImpl extends BaseModelImpl<VLegalDFRel>
	implements VLegalDFRelModel {
	public static final String TABLE_NAME = "VLegalDFRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fieldId", new Integer(Types.VARCHAR) },
			{ "docId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalDFRel (fieldId VARCHAR(75) not null,docId VARCHAR(75) not null,primary key (fieldId, docId))";
	public static final String TABLE_SQL_DROP = "drop table VLegalDFRel";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalDFRel.id.fieldId DESC, vLegalDFRel.id.docId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalDFRel.fieldId DESC, VLegalDFRel.docId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalDFRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalDFRel"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalDFRel toModel(VLegalDFRelSoap soapModel) {
		VLegalDFRel model = new VLegalDFRelImpl();

		model.setFieldId(soapModel.getFieldId());
		model.setDocId(soapModel.getDocId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalDFRel> toModels(VLegalDFRelSoap[] soapModels) {
		List<VLegalDFRel> models = new ArrayList<VLegalDFRel>(soapModels.length);

		for (VLegalDFRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalDFRel"));

	public VLegalDFRelModelImpl() {
	}

	public VLegalDFRelPK getPrimaryKey() {
		return new VLegalDFRelPK(_fieldId, _docId);
	}

	public void setPrimaryKey(VLegalDFRelPK pk) {
		setFieldId(pk.fieldId);
		setDocId(pk.docId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VLegalDFRelPK(_fieldId, _docId);
	}

	public String getFieldId() {
		if (_fieldId == null) {
			return StringPool.BLANK;
		}
		else {
			return _fieldId;
		}
	}

	public void setFieldId(String fieldId) {
		_fieldId = fieldId;
	}

	public String getDocId() {
		if (_docId == null) {
			return StringPool.BLANK;
		}
		else {
			return _docId;
		}
	}

	public void setDocId(String docId) {
		_docId = docId;
	}

	public VLegalDFRel toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalDFRel)this;
		}
		else {
			return (VLegalDFRel)Proxy.newProxyInstance(VLegalDFRel.class.getClassLoader(),
				new Class[] { VLegalDFRel.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalDFRelImpl vLegalDFRelImpl = new VLegalDFRelImpl();

		vLegalDFRelImpl.setFieldId(getFieldId());

		vLegalDFRelImpl.setDocId(getDocId());

		return vLegalDFRelImpl;
	}

	public int compareTo(VLegalDFRel vLegalDFRel) {
		int value = 0;

		value = getFieldId().compareTo(vLegalDFRel.getFieldId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getDocId().compareTo(vLegalDFRel.getDocId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalDFRel vLegalDFRel = null;

		try {
			vLegalDFRel = (VLegalDFRel)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VLegalDFRelPK pk = vLegalDFRel.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{fieldId=");
		sb.append(getFieldId());
		sb.append(", docId=");
		sb.append(getDocId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalDFRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fieldId</column-name><column-value><![CDATA[");
		sb.append(getFieldId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>docId</column-name><column-value><![CDATA[");
		sb.append(getDocId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _fieldId;
	private String _docId;
}