/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.vportal.portlet.vlegal.model.VLegalTags;
import com.vportal.portlet.vlegal.model.VLegalTagsModel;
import com.vportal.portlet.vlegal.model.VLegalTagsSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the VLegalTags service. Represents a row in the &quot;VLegalTags&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalTagsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalTagsImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal tags model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalTags} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalTagsImpl
 * @see com.vportal.portlet.vlegal.model.VLegalTags
 * @see com.vportal.portlet.vlegal.model.VLegalTagsModel
 * @generated
 */
public class VLegalTagsModelImpl extends BaseModelImpl<VLegalTags>
	implements VLegalTagsModel {
	public static final String TABLE_NAME = "VLegalTags";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tagId", new Integer(Types.VARCHAR) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "name", new Integer(Types.VARCHAR) },
			{ "statusTags", new Integer(Types.BOOLEAN) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalTags (tagId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,statusTags BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table VLegalTags";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalTags.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalTags.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalTags"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalTags"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalTags toModel(VLegalTagsSoap soapModel) {
		VLegalTags model = new VLegalTagsImpl();

		model.setTagId(soapModel.getTagId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setStatusTags(soapModel.getStatusTags());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalTags> toModels(VLegalTagsSoap[] soapModels) {
		List<VLegalTags> models = new ArrayList<VLegalTags>(soapModels.length);

		for (VLegalTagsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalTags"));

	public VLegalTagsModelImpl() {
	}

	public String getPrimaryKey() {
		return _tagId;
	}

	public void setPrimaryKey(String pk) {
		setTagId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return _tagId;
	}

	public String getTagId() {
		if (_tagId == null) {
			return StringPool.BLANK;
		}
		else {
			return _tagId;
		}
	}

	public void setTagId(String tagId) {
		_tagId = tagId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public boolean getStatusTags() {
		return _statusTags;
	}

	public boolean isStatusTags() {
		return _statusTags;
	}

	public void setStatusTags(boolean statusTags) {
		_statusTags = statusTags;
	}

	public VLegalTags toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalTags)this;
		}
		else {
			return (VLegalTags)Proxy.newProxyInstance(VLegalTags.class.getClassLoader(),
				new Class[] { VLegalTags.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalTagsImpl vLegalTagsImpl = new VLegalTagsImpl();

		vLegalTagsImpl.setTagId(getTagId());

		vLegalTagsImpl.setGroupId(getGroupId());

		vLegalTagsImpl.setCompanyId(getCompanyId());

		vLegalTagsImpl.setUserId(getUserId());

		vLegalTagsImpl.setCreatedDate(getCreatedDate());

		vLegalTagsImpl.setModifiedDate(getModifiedDate());

		vLegalTagsImpl.setName(getName());

		vLegalTagsImpl.setStatusTags(getStatusTags());

		return vLegalTagsImpl;
	}

	public int compareTo(VLegalTags vLegalTags) {
		int value = 0;

		value = getName().compareTo(vLegalTags.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalTags vLegalTags = null;

		try {
			vLegalTags = (VLegalTags)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String pk = vLegalTags.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{tagId=");
		sb.append(getTagId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", statusTags=");
		sb.append(getStatusTags());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalTags");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusTags</column-name><column-value><![CDATA[");
		sb.append(getStatusTags());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _tagId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createdDate;
	private Date _modifiedDate;
	private String _name;
	private boolean _statusTags;
}