/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vsi.edirectory.portlet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vsi.edirectory.portlet.model.EDDepartment;
import com.vsi.edirectory.portlet.model.EDDepartmentModel;
import com.vsi.edirectory.portlet.model.EDDepartmentSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the EDDepartment service. Represents a row in the &quot;EDDepartment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vsi.edirectory.portlet.model.EDDepartmentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EDDepartmentImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a e d department model instance should use the {@link com.vsi.edirectory.portlet.model.EDDepartment} interface instead.
 * </p>
 *
 * @author vinhnt
 * @see EDDepartmentImpl
 * @see com.vsi.edirectory.portlet.model.EDDepartment
 * @see com.vsi.edirectory.portlet.model.EDDepartmentModel
 * @generated
 */
public class EDDepartmentModelImpl extends BaseModelImpl<EDDepartment>
	implements EDDepartmentModel {
	public static final String TABLE_NAME = "EDDepartment";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", new Integer(Types.BIGINT) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "name", new Integer(Types.VARCHAR) },
			{ "parent", new Integer(Types.BIGINT) },
			{ "phone", new Integer(Types.VARCHAR) },
			{ "fax", new Integer(Types.VARCHAR) },
			{ "levelEd", new Integer(Types.INTEGER) },
			{ "email", new Integer(Types.VARCHAR) },
			{ "address", new Integer(Types.VARCHAR) },
			{ "description", new Integer(Types.VARCHAR) },
			{ "website", new Integer(Types.VARCHAR) },
			{ "imgurl", new Integer(Types.VARCHAR) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "languageId", new Integer(Types.VARCHAR) },
			{ "domainId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table EDDepartment (id_ LONG not null primary key,createdDate DATE null,name VARCHAR(500) null,parent LONG,phone VARCHAR(75) null,fax VARCHAR(75) null,levelEd INTEGER,email VARCHAR(75) null,address VARCHAR(500) null,description VARCHAR(1000) null,website VARCHAR(100) null,imgurl VARCHAR(75) null,companyId LONG,groupId LONG,userId LONG,languageId VARCHAR(75) null,domainId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table EDDepartment";
	public static final String ORDER_BY_JPQL = " ORDER BY edDepartment.parent ASC, edDepartment.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EDDepartment.parent ASC, EDDepartment.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vsi.edirectory.portlet.model.EDDepartment"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vsi.edirectory.portlet.model.EDDepartment"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EDDepartment toModel(EDDepartmentSoap soapModel) {
		EDDepartment model = new EDDepartmentImpl();

		model.setId(soapModel.getId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setName(soapModel.getName());
		model.setParent(soapModel.getParent());
		model.setPhone(soapModel.getPhone());
		model.setFax(soapModel.getFax());
		model.setLevelEd(soapModel.getLevelEd());
		model.setEmail(soapModel.getEmail());
		model.setAddress(soapModel.getAddress());
		model.setDescription(soapModel.getDescription());
		model.setWebsite(soapModel.getWebsite());
		model.setImgurl(soapModel.getImgurl());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setLanguageId(soapModel.getLanguageId());
		model.setDomainId(soapModel.getDomainId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EDDepartment> toModels(EDDepartmentSoap[] soapModels) {
		List<EDDepartment> models = new ArrayList<EDDepartment>(soapModels.length);

		for (EDDepartmentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vsi.edirectory.portlet.model.EDDepartment"));

	public EDDepartmentModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long pk) {
		setId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public long getParent() {
		return _parent;
	}

	public void setParent(long parent) {
		_parent = parent;
	}

	public String getPhone() {
		if (_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _phone;
		}
	}

	public void setPhone(String phone) {
		_phone = phone;
	}

	public String getFax() {
		if (_fax == null) {
			return StringPool.BLANK;
		}
		else {
			return _fax;
		}
	}

	public void setFax(String fax) {
		_fax = fax;
	}

	public int getLevelEd() {
		return _levelEd;
	}

	public void setLevelEd(int levelEd) {
		_levelEd = levelEd;
	}

	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	public void setEmail(String email) {
		_email = email;
	}

	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	public void setAddress(String address) {
		_address = address;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public String getWebsite() {
		if (_website == null) {
			return StringPool.BLANK;
		}
		else {
			return _website;
		}
	}

	public void setWebsite(String website) {
		_website = website;
	}

	public String getImgurl() {
		if (_imgurl == null) {
			return StringPool.BLANK;
		}
		else {
			return _imgurl;
		}
	}

	public void setImgurl(String imgurl) {
		_imgurl = imgurl;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public String getLanguageId() {
		if (_languageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageId;
		}
	}

	public void setLanguageId(String languageId) {
		_languageId = languageId;
	}

	public String getDomainId() {
		if (_domainId == null) {
			return StringPool.BLANK;
		}
		else {
			return _domainId;
		}
	}

	public void setDomainId(String domainId) {
		_domainId = domainId;
	}

	public EDDepartment toEscapedModel() {
		if (isEscapedModel()) {
			return (EDDepartment)this;
		}
		else {
			return (EDDepartment)Proxy.newProxyInstance(EDDepartment.class.getClassLoader(),
				new Class[] { EDDepartment.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					EDDepartment.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		EDDepartmentImpl edDepartmentImpl = new EDDepartmentImpl();

		edDepartmentImpl.setId(getId());

		EDDepartmentModelImpl edDepartmentModelImpl = edDepartmentImpl;

		edDepartmentModelImpl._originalId = edDepartmentModelImpl._id;

		edDepartmentModelImpl._setOriginalId = false;
		edDepartmentImpl.setCreatedDate(getCreatedDate());

		edDepartmentImpl.setName(getName());

		edDepartmentImpl.setParent(getParent());

		edDepartmentImpl.setPhone(getPhone());

		edDepartmentImpl.setFax(getFax());

		edDepartmentImpl.setLevelEd(getLevelEd());

		edDepartmentImpl.setEmail(getEmail());

		edDepartmentImpl.setAddress(getAddress());

		edDepartmentImpl.setDescription(getDescription());

		edDepartmentImpl.setWebsite(getWebsite());

		edDepartmentImpl.setImgurl(getImgurl());

		edDepartmentImpl.setCompanyId(getCompanyId());

		edDepartmentImpl.setGroupId(getGroupId());

		edDepartmentModelImpl._originalGroupId = edDepartmentModelImpl._groupId;

		edDepartmentModelImpl._setOriginalGroupId = false;
		edDepartmentImpl.setUserId(getUserId());

		edDepartmentImpl.setLanguageId(getLanguageId());

		edDepartmentImpl.setDomainId(getDomainId());

		return edDepartmentImpl;
	}

	public int compareTo(EDDepartment edDepartment) {
		int value = 0;

		if (getParent() < edDepartment.getParent()) {
			value = -1;
		}
		else if (getParent() > edDepartment.getParent()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getName().toLowerCase()
					.compareTo(edDepartment.getName().toLowerCase());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		EDDepartment edDepartment = null;

		try {
			edDepartment = (EDDepartment)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = edDepartment.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(35);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", parent=");
		sb.append(getParent());
		sb.append(", phone=");
		sb.append(getPhone());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", levelEd=");
		sb.append(getLevelEd());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", website=");
		sb.append(getWebsite());
		sb.append(", imgurl=");
		sb.append(getImgurl());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", domainId=");
		sb.append(getDomainId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(55);

		sb.append("<model><model-name>");
		sb.append("com.vsi.edirectory.portlet.model.EDDepartment");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parent</column-name><column-value><![CDATA[");
		sb.append(getParent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phone</column-name><column-value><![CDATA[");
		sb.append(getPhone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>levelEd</column-name><column-value><![CDATA[");
		sb.append(getLevelEd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>website</column-name><column-value><![CDATA[");
		sb.append(getWebsite());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imgurl</column-name><column-value><![CDATA[");
		sb.append(getImgurl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>domainId</column-name><column-value><![CDATA[");
		sb.append(getDomainId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private Date _createdDate;
	private String _name;
	private long _parent;
	private String _phone;
	private String _fax;
	private int _levelEd;
	private String _email;
	private String _address;
	private String _description;
	private String _website;
	private String _imgurl;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private String _languageId;
	private String _domainId;
	private transient ExpandoBridge _expandoBridge;
}