/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.vportal.portlet.vlegal.model.VLegalSigner;
import com.vportal.portlet.vlegal.model.VLegalSignerModel;
import com.vportal.portlet.vlegal.model.VLegalSignerSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the VLegalSigner service. Represents a row in the &quot;VLegalSigner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalSignerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalSignerImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal signer model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalSigner} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalSignerImpl
 * @see com.vportal.portlet.vlegal.model.VLegalSigner
 * @see com.vportal.portlet.vlegal.model.VLegalSignerModel
 * @generated
 */
public class VLegalSignerModelImpl extends BaseModelImpl<VLegalSigner>
	implements VLegalSignerModel {
	public static final String TABLE_NAME = "VLegalSigner";
	public static final Object[][] TABLE_COLUMNS = {
			{ "sigId", new Integer(Types.VARCHAR) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "createdByUser", new Integer(Types.BIGINT) },
			{ "modifiedByUser", new Integer(Types.BIGINT) },
			{ "firstName", new Integer(Types.VARCHAR) },
			{ "lastName", new Integer(Types.VARCHAR) },
			{ "language", new Integer(Types.VARCHAR) },
			{ "statusSigner", new Integer(Types.BOOLEAN) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalSigner (sigId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,createdByUser LONG,modifiedByUser LONG,firstName VARCHAR(500) null,lastName VARCHAR(500) null,language VARCHAR(75) null,statusSigner BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table VLegalSigner";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalSigner.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalSigner.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalSigner"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalSigner"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalSigner toModel(VLegalSignerSoap soapModel) {
		VLegalSigner model = new VLegalSignerImpl();

		model.setSigId(soapModel.getSigId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCreatedByUser(soapModel.getCreatedByUser());
		model.setModifiedByUser(soapModel.getModifiedByUser());
		model.setFirstName(soapModel.getFirstName());
		model.setLastName(soapModel.getLastName());
		model.setLanguage(soapModel.getLanguage());
		model.setStatusSigner(soapModel.getStatusSigner());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalSigner> toModels(VLegalSignerSoap[] soapModels) {
		List<VLegalSigner> models = new ArrayList<VLegalSigner>(soapModels.length);

		for (VLegalSignerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalSigner"));

	public VLegalSignerModelImpl() {
	}

	public String getPrimaryKey() {
		return _sigId;
	}

	public void setPrimaryKey(String pk) {
		setSigId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return _sigId;
	}

	public String getSigId() {
		if (_sigId == null) {
			return StringPool.BLANK;
		}
		else {
			return _sigId;
		}
	}

	public void setSigId(String sigId) {
		if (_originalSigId == null) {
			_originalSigId = _sigId;
		}

		_sigId = sigId;
	}

	public String getOriginalSigId() {
		return GetterUtil.getString(_originalSigId);
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getCreatedByUser() {
		return _createdByUser;
	}

	public void setCreatedByUser(long createdByUser) {
		_createdByUser = createdByUser;
	}

	public long getModifiedByUser() {
		return _modifiedByUser;
	}

	public void setModifiedByUser(long modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	public String getFirstName() {
		if (_firstName == null) {
			return StringPool.BLANK;
		}
		else {
			return _firstName;
		}
	}

	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	public String getLastName() {
		if (_lastName == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastName;
		}
	}

	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	public void setLanguage(String language) {
		_language = language;
	}

	public boolean getStatusSigner() {
		return _statusSigner;
	}

	public boolean isStatusSigner() {
		return _statusSigner;
	}

	public void setStatusSigner(boolean statusSigner) {
		_statusSigner = statusSigner;
	}

	public VLegalSigner toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalSigner)this;
		}
		else {
			return (VLegalSigner)Proxy.newProxyInstance(VLegalSigner.class.getClassLoader(),
				new Class[] { VLegalSigner.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalSignerImpl vLegalSignerImpl = new VLegalSignerImpl();

		vLegalSignerImpl.setSigId(getSigId());

		VLegalSignerModelImpl vLegalSignerModelImpl = vLegalSignerImpl;

		vLegalSignerModelImpl._originalSigId = vLegalSignerModelImpl._sigId;

		vLegalSignerImpl.setGroupId(getGroupId());

		vLegalSignerModelImpl._originalGroupId = vLegalSignerModelImpl._groupId;

		vLegalSignerModelImpl._setOriginalGroupId = false;
		vLegalSignerImpl.setCompanyId(getCompanyId());

		vLegalSignerImpl.setUserId(getUserId());

		vLegalSignerImpl.setCreatedDate(getCreatedDate());

		vLegalSignerImpl.setModifiedDate(getModifiedDate());

		vLegalSignerImpl.setCreatedByUser(getCreatedByUser());

		vLegalSignerImpl.setModifiedByUser(getModifiedByUser());

		vLegalSignerImpl.setFirstName(getFirstName());

		vLegalSignerImpl.setLastName(getLastName());

		vLegalSignerImpl.setLanguage(getLanguage());

		vLegalSignerImpl.setStatusSigner(getStatusSigner());

		return vLegalSignerImpl;
	}

	public int compareTo(VLegalSigner vLegalSigner) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				vLegalSigner.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalSigner vLegalSigner = null;

		try {
			vLegalSigner = (VLegalSigner)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String pk = vLegalSigner.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{sigId=");
		sb.append(getSigId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", firstName=");
		sb.append(getFirstName());
		sb.append(", lastName=");
		sb.append(getLastName());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", statusSigner=");
		sb.append(getStatusSigner());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalSigner");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>sigId</column-name><column-value><![CDATA[");
		sb.append(getSigId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>firstName</column-name><column-value><![CDATA[");
		sb.append(getFirstName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastName</column-name><column-value><![CDATA[");
		sb.append(getLastName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusSigner</column-name><column-value><![CDATA[");
		sb.append(getStatusSigner());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _sigId;
	private String _originalSigId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createdDate;
	private Date _modifiedDate;
	private long _createdByUser;
	private long _modifiedByUser;
	private String _firstName;
	private String _lastName;
	private String _language;
	private boolean _statusSigner;
}