/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.vportal.portlet.vlegal.model.VLegalOrg;
import com.vportal.portlet.vlegal.model.VLegalOrgModel;
import com.vportal.portlet.vlegal.model.VLegalOrgSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the VLegalOrg service. Represents a row in the &quot;VLegalOrg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalOrgModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalOrgImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal org model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalOrg} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalOrgImpl
 * @see com.vportal.portlet.vlegal.model.VLegalOrg
 * @see com.vportal.portlet.vlegal.model.VLegalOrgModel
 * @generated
 */
public class VLegalOrgModelImpl extends BaseModelImpl<VLegalOrg>
	implements VLegalOrgModel {
	public static final String TABLE_NAME = "VLegalOrg";
	public static final Object[][] TABLE_COLUMNS = {
			{ "orgId", new Integer(Types.VARCHAR) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "createdByUser", new Integer(Types.BIGINT) },
			{ "modifiedByUser", new Integer(Types.BIGINT) },
			{ "name", new Integer(Types.VARCHAR) },
			{ "description", new Integer(Types.VARCHAR) },
			{ "parentId", new Integer(Types.VARCHAR) },
			{ "language", new Integer(Types.VARCHAR) },
			{ "statusOrg", new Integer(Types.BOOLEAN) },
			{ "rssable", new Integer(Types.BOOLEAN) },
			{ "position", new Integer(Types.INTEGER) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalOrg (orgId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,createdByUser LONG,modifiedByUser LONG,name VARCHAR(500) null,description VARCHAR(2000) null,parentId VARCHAR(75) null,language VARCHAR(75) null,statusOrg BOOLEAN,rssable BOOLEAN,position INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table VLegalOrg";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalOrg.position ASC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalOrg.position ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalOrg"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalOrg"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalOrg toModel(VLegalOrgSoap soapModel) {
		VLegalOrg model = new VLegalOrgImpl();

		model.setOrgId(soapModel.getOrgId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCreatedByUser(soapModel.getCreatedByUser());
		model.setModifiedByUser(soapModel.getModifiedByUser());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setParentId(soapModel.getParentId());
		model.setLanguage(soapModel.getLanguage());
		model.setStatusOrg(soapModel.getStatusOrg());
		model.setRssable(soapModel.getRssable());
		model.setPosition(soapModel.getPosition());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalOrg> toModels(VLegalOrgSoap[] soapModels) {
		List<VLegalOrg> models = new ArrayList<VLegalOrg>(soapModels.length);

		for (VLegalOrgSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalOrg"));

	public VLegalOrgModelImpl() {
	}

	public String getPrimaryKey() {
		return _orgId;
	}

	public void setPrimaryKey(String pk) {
		setOrgId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return _orgId;
	}

	public String getOrgId() {
		if (_orgId == null) {
			return StringPool.BLANK;
		}
		else {
			return _orgId;
		}
	}

	public void setOrgId(String orgId) {
		if (_originalOrgId == null) {
			_originalOrgId = _orgId;
		}

		_orgId = orgId;
	}

	public String getOriginalOrgId() {
		return GetterUtil.getString(_originalOrgId);
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getCreatedByUser() {
		return _createdByUser;
	}

	public void setCreatedByUser(long createdByUser) {
		_createdByUser = createdByUser;
	}

	public long getModifiedByUser() {
		return _modifiedByUser;
	}

	public void setModifiedByUser(long modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public String getParentId() {
		if (_parentId == null) {
			return StringPool.BLANK;
		}
		else {
			return _parentId;
		}
	}

	public void setParentId(String parentId) {
		_parentId = parentId;
	}

	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	public void setLanguage(String language) {
		_language = language;
	}

	public boolean getStatusOrg() {
		return _statusOrg;
	}

	public boolean isStatusOrg() {
		return _statusOrg;
	}

	public void setStatusOrg(boolean statusOrg) {
		_statusOrg = statusOrg;
	}

	public boolean getRssable() {
		return _rssable;
	}

	public boolean isRssable() {
		return _rssable;
	}

	public void setRssable(boolean rssable) {
		_rssable = rssable;
	}

	public int getPosition() {
		return _position;
	}

	public void setPosition(int position) {
		_position = position;
	}

	public VLegalOrg toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalOrg)this;
		}
		else {
			return (VLegalOrg)Proxy.newProxyInstance(VLegalOrg.class.getClassLoader(),
				new Class[] { VLegalOrg.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalOrgImpl vLegalOrgImpl = new VLegalOrgImpl();

		vLegalOrgImpl.setOrgId(getOrgId());

		VLegalOrgModelImpl vLegalOrgModelImpl = vLegalOrgImpl;

		vLegalOrgModelImpl._originalOrgId = vLegalOrgModelImpl._orgId;

		vLegalOrgImpl.setGroupId(getGroupId());

		vLegalOrgModelImpl._originalGroupId = vLegalOrgModelImpl._groupId;

		vLegalOrgModelImpl._setOriginalGroupId = false;
		vLegalOrgImpl.setCompanyId(getCompanyId());

		vLegalOrgImpl.setUserId(getUserId());

		vLegalOrgImpl.setCreatedDate(getCreatedDate());

		vLegalOrgImpl.setModifiedDate(getModifiedDate());

		vLegalOrgImpl.setCreatedByUser(getCreatedByUser());

		vLegalOrgImpl.setModifiedByUser(getModifiedByUser());

		vLegalOrgImpl.setName(getName());

		vLegalOrgImpl.setDescription(getDescription());

		vLegalOrgImpl.setParentId(getParentId());

		vLegalOrgImpl.setLanguage(getLanguage());

		vLegalOrgImpl.setStatusOrg(getStatusOrg());

		vLegalOrgImpl.setRssable(getRssable());

		vLegalOrgImpl.setPosition(getPosition());

		return vLegalOrgImpl;
	}

	public int compareTo(VLegalOrg vLegalOrg) {
		int value = 0;

		if (getPosition() < vLegalOrg.getPosition()) {
			value = -1;
		}
		else if (getPosition() > vLegalOrg.getPosition()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalOrg vLegalOrg = null;

		try {
			vLegalOrg = (VLegalOrg)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String pk = vLegalOrg.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{orgId=");
		sb.append(getOrgId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", parentId=");
		sb.append(getParentId());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", statusOrg=");
		sb.append(getStatusOrg());
		sb.append(", rssable=");
		sb.append(getRssable());
		sb.append(", position=");
		sb.append(getPosition());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalOrg");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>orgId</column-name><column-value><![CDATA[");
		sb.append(getOrgId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentId</column-name><column-value><![CDATA[");
		sb.append(getParentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusOrg</column-name><column-value><![CDATA[");
		sb.append(getStatusOrg());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rssable</column-name><column-value><![CDATA[");
		sb.append(getRssable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position</column-name><column-value><![CDATA[");
		sb.append(getPosition());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _orgId;
	private String _originalOrgId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createdDate;
	private Date _modifiedDate;
	private long _createdByUser;
	private long _modifiedByUser;
	private String _name;
	private String _description;
	private String _parentId;
	private String _language;
	private boolean _statusOrg;
	private boolean _rssable;
	private int _position;
}