/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.vportal.portlet.vlegal.model.VLegalTDRel;
import com.vportal.portlet.vlegal.model.VLegalTDRelModel;
import com.vportal.portlet.vlegal.model.VLegalTDRelSoap;
import com.vportal.portlet.vlegal.service.persistence.VLegalTDRelPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the VLegalTDRel service. Represents a row in the &quot;VLegalTDRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalTDRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalTDRelImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal t d rel model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalTDRel} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalTDRelImpl
 * @see com.vportal.portlet.vlegal.model.VLegalTDRel
 * @see com.vportal.portlet.vlegal.model.VLegalTDRelModel
 * @generated
 */
public class VLegalTDRelModelImpl extends BaseModelImpl<VLegalTDRel>
	implements VLegalTDRelModel {
	public static final String TABLE_NAME = "VLegalTDRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "docId", new Integer(Types.VARCHAR) },
			{ "tagId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalTDRel (docId VARCHAR(75) not null,tagId VARCHAR(75) not null,primary key (docId, tagId))";
	public static final String TABLE_SQL_DROP = "drop table VLegalTDRel";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalTDRel.id.docId DESC, vLegalTDRel.id.tagId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalTDRel.docId DESC, VLegalTDRel.tagId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalTDRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalTDRel"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalTDRel toModel(VLegalTDRelSoap soapModel) {
		VLegalTDRel model = new VLegalTDRelImpl();

		model.setDocId(soapModel.getDocId());
		model.setTagId(soapModel.getTagId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalTDRel> toModels(VLegalTDRelSoap[] soapModels) {
		List<VLegalTDRel> models = new ArrayList<VLegalTDRel>(soapModels.length);

		for (VLegalTDRelSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalTDRel"));

	public VLegalTDRelModelImpl() {
	}

	public VLegalTDRelPK getPrimaryKey() {
		return new VLegalTDRelPK(_docId, _tagId);
	}

	public void setPrimaryKey(VLegalTDRelPK pk) {
		setDocId(pk.docId);
		setTagId(pk.tagId);
	}

	public Serializable getPrimaryKeyObj() {
		return new VLegalTDRelPK(_docId, _tagId);
	}

	public String getDocId() {
		if (_docId == null) {
			return StringPool.BLANK;
		}
		else {
			return _docId;
		}
	}

	public void setDocId(String docId) {
		_docId = docId;
	}

	public String getTagId() {
		if (_tagId == null) {
			return StringPool.BLANK;
		}
		else {
			return _tagId;
		}
	}

	public void setTagId(String tagId) {
		_tagId = tagId;
	}

	public VLegalTDRel toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalTDRel)this;
		}
		else {
			return (VLegalTDRel)Proxy.newProxyInstance(VLegalTDRel.class.getClassLoader(),
				new Class[] { VLegalTDRel.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalTDRelImpl vLegalTDRelImpl = new VLegalTDRelImpl();

		vLegalTDRelImpl.setDocId(getDocId());

		vLegalTDRelImpl.setTagId(getTagId());

		return vLegalTDRelImpl;
	}

	public int compareTo(VLegalTDRel vLegalTDRel) {
		int value = 0;

		value = getDocId().compareTo(vLegalTDRel.getDocId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		value = getTagId().compareTo(vLegalTDRel.getTagId());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalTDRel vLegalTDRel = null;

		try {
			vLegalTDRel = (VLegalTDRel)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		VLegalTDRelPK pk = vLegalTDRel.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{docId=");
		sb.append(getDocId());
		sb.append(", tagId=");
		sb.append(getTagId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalTDRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>docId</column-name><column-value><![CDATA[");
		sb.append(getDocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tagId</column-name><column-value><![CDATA[");
		sb.append(getTagId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _docId;
	private String _tagId;
}