/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.vportal.portlet.vlegal.model.VLegalSuggestDocument;
import com.vportal.portlet.vlegal.model.VLegalSuggestDocumentModel;
import com.vportal.portlet.vlegal.model.VLegalSuggestDocumentSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the VLegalSuggestDocument service. Represents a row in the &quot;VLegalSuggestDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vportal.portlet.vlegal.model.VLegalSuggestDocumentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VLegalSuggestDocumentImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a v legal suggest document model instance should use the {@link com.vportal.portlet.vlegal.model.VLegalSuggestDocument} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalSuggestDocumentImpl
 * @see com.vportal.portlet.vlegal.model.VLegalSuggestDocument
 * @see com.vportal.portlet.vlegal.model.VLegalSuggestDocumentModel
 * @generated
 */
public class VLegalSuggestDocumentModelImpl extends BaseModelImpl<VLegalSuggestDocument>
	implements VLegalSuggestDocumentModel {
	public static final String TABLE_NAME = "VLegalSuggestDocument";
	public static final Object[][] TABLE_COLUMNS = {
			{ "sugId", new Integer(Types.VARCHAR) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedByUser", new Integer(Types.BIGINT) },
			{ "approved", new Integer(Types.BOOLEAN) },
			{ "approvedByUser", new Integer(Types.BIGINT) },
			{ "approvedDate", new Integer(Types.TIMESTAMP) },
			{ "title", new Integer(Types.VARCHAR) },
			{ "content", new Integer(Types.VARCHAR) },
			{ "language", new Integer(Types.VARCHAR) },
			{ "visitorName", new Integer(Types.VARCHAR) },
			{ "visitorEmail", new Integer(Types.VARCHAR) },
			{ "visitorTel", new Integer(Types.VARCHAR) },
			{ "visitorAddress", new Integer(Types.VARCHAR) },
			{ "draftId", new Integer(Types.VARCHAR) },
			{ "hasAttachment", new Integer(Types.BOOLEAN) }
		};
	public static final String TABLE_SQL_CREATE = "create table VLegalSuggestDocument (sugId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,userId LONG,createdDate DATE null,modifiedDate DATE null,modifiedByUser LONG,approved BOOLEAN,approvedByUser LONG,approvedDate DATE null,title VARCHAR(75) null,content VARCHAR(75) null,language VARCHAR(75) null,visitorName VARCHAR(75) null,visitorEmail VARCHAR(75) null,visitorTel VARCHAR(75) null,visitorAddress VARCHAR(75) null,draftId VARCHAR(75) null,hasAttachment BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table VLegalSuggestDocument";
	public static final String ORDER_BY_JPQL = " ORDER BY vLegalSuggestDocument.createdDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY VLegalSuggestDocument.createdDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vportal.portlet.vlegal.model.VLegalSuggestDocument"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vportal.portlet.vlegal.model.VLegalSuggestDocument"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VLegalSuggestDocument toModel(
		VLegalSuggestDocumentSoap soapModel) {
		VLegalSuggestDocument model = new VLegalSuggestDocumentImpl();

		model.setSugId(soapModel.getSugId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setModifiedByUser(soapModel.getModifiedByUser());
		model.setApproved(soapModel.getApproved());
		model.setApprovedByUser(soapModel.getApprovedByUser());
		model.setApprovedDate(soapModel.getApprovedDate());
		model.setTitle(soapModel.getTitle());
		model.setContent(soapModel.getContent());
		model.setLanguage(soapModel.getLanguage());
		model.setVisitorName(soapModel.getVisitorName());
		model.setVisitorEmail(soapModel.getVisitorEmail());
		model.setVisitorTel(soapModel.getVisitorTel());
		model.setVisitorAddress(soapModel.getVisitorAddress());
		model.setDraftId(soapModel.getDraftId());
		model.setHasAttachment(soapModel.getHasAttachment());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VLegalSuggestDocument> toModels(
		VLegalSuggestDocumentSoap[] soapModels) {
		List<VLegalSuggestDocument> models = new ArrayList<VLegalSuggestDocument>(soapModels.length);

		for (VLegalSuggestDocumentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vportal.portlet.vlegal.model.VLegalSuggestDocument"));

	public VLegalSuggestDocumentModelImpl() {
	}

	public String getPrimaryKey() {
		return _sugId;
	}

	public void setPrimaryKey(String pk) {
		setSugId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return _sugId;
	}

	public String getSugId() {
		if (_sugId == null) {
			return StringPool.BLANK;
		}
		else {
			return _sugId;
		}
	}

	public void setSugId(String sugId) {
		if (_originalSugId == null) {
			_originalSugId = _sugId;
		}

		_sugId = sugId;
	}

	public String getOriginalSugId() {
		return GetterUtil.getString(_originalSugId);
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getModifiedByUser() {
		return _modifiedByUser;
	}

	public void setModifiedByUser(long modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	public boolean getApproved() {
		return _approved;
	}

	public boolean isApproved() {
		return _approved;
	}

	public void setApproved(boolean approved) {
		_approved = approved;
	}

	public long getApprovedByUser() {
		return _approvedByUser;
	}

	public void setApprovedByUser(long approvedByUser) {
		_approvedByUser = approvedByUser;
	}

	public Date getApprovedDate() {
		return _approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		_approvedDate = approvedDate;
	}

	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	public void setTitle(String title) {
		_title = title;
	}

	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	public void setContent(String content) {
		_content = content;
	}

	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	public void setLanguage(String language) {
		_language = language;
	}

	public String getVisitorName() {
		if (_visitorName == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitorName;
		}
	}

	public void setVisitorName(String visitorName) {
		_visitorName = visitorName;
	}

	public String getVisitorEmail() {
		if (_visitorEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitorEmail;
		}
	}

	public void setVisitorEmail(String visitorEmail) {
		_visitorEmail = visitorEmail;
	}

	public String getVisitorTel() {
		if (_visitorTel == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitorTel;
		}
	}

	public void setVisitorTel(String visitorTel) {
		_visitorTel = visitorTel;
	}

	public String getVisitorAddress() {
		if (_visitorAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _visitorAddress;
		}
	}

	public void setVisitorAddress(String visitorAddress) {
		_visitorAddress = visitorAddress;
	}

	public String getDraftId() {
		if (_draftId == null) {
			return StringPool.BLANK;
		}
		else {
			return _draftId;
		}
	}

	public void setDraftId(String draftId) {
		_draftId = draftId;
	}

	public boolean getHasAttachment() {
		return _hasAttachment;
	}

	public boolean isHasAttachment() {
		return _hasAttachment;
	}

	public void setHasAttachment(boolean hasAttachment) {
		_hasAttachment = hasAttachment;
	}

	public VLegalSuggestDocument toEscapedModel() {
		if (isEscapedModel()) {
			return (VLegalSuggestDocument)this;
		}
		else {
			return (VLegalSuggestDocument)Proxy.newProxyInstance(VLegalSuggestDocument.class.getClassLoader(),
				new Class[] { VLegalSuggestDocument.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VLegalSuggestDocumentImpl vLegalSuggestDocumentImpl = new VLegalSuggestDocumentImpl();

		vLegalSuggestDocumentImpl.setSugId(getSugId());

		VLegalSuggestDocumentModelImpl vLegalSuggestDocumentModelImpl = vLegalSuggestDocumentImpl;

		vLegalSuggestDocumentModelImpl._originalSugId = vLegalSuggestDocumentModelImpl._sugId;

		vLegalSuggestDocumentImpl.setGroupId(getGroupId());

		vLegalSuggestDocumentModelImpl._originalGroupId = vLegalSuggestDocumentModelImpl._groupId;

		vLegalSuggestDocumentModelImpl._setOriginalGroupId = false;
		vLegalSuggestDocumentImpl.setCompanyId(getCompanyId());

		vLegalSuggestDocumentImpl.setUserId(getUserId());

		vLegalSuggestDocumentImpl.setCreatedDate(getCreatedDate());

		vLegalSuggestDocumentImpl.setModifiedDate(getModifiedDate());

		vLegalSuggestDocumentImpl.setModifiedByUser(getModifiedByUser());

		vLegalSuggestDocumentImpl.setApproved(getApproved());

		vLegalSuggestDocumentImpl.setApprovedByUser(getApprovedByUser());

		vLegalSuggestDocumentImpl.setApprovedDate(getApprovedDate());

		vLegalSuggestDocumentImpl.setTitle(getTitle());

		vLegalSuggestDocumentImpl.setContent(getContent());

		vLegalSuggestDocumentImpl.setLanguage(getLanguage());

		vLegalSuggestDocumentImpl.setVisitorName(getVisitorName());

		vLegalSuggestDocumentImpl.setVisitorEmail(getVisitorEmail());

		vLegalSuggestDocumentImpl.setVisitorTel(getVisitorTel());

		vLegalSuggestDocumentImpl.setVisitorAddress(getVisitorAddress());

		vLegalSuggestDocumentImpl.setDraftId(getDraftId());

		vLegalSuggestDocumentImpl.setHasAttachment(getHasAttachment());

		return vLegalSuggestDocumentImpl;
	}

	public int compareTo(VLegalSuggestDocument vLegalSuggestDocument) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				vLegalSuggestDocument.getCreatedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		VLegalSuggestDocument vLegalSuggestDocument = null;

		try {
			vLegalSuggestDocument = (VLegalSuggestDocument)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String pk = vLegalSuggestDocument.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{sugId=");
		sb.append(getSugId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", approved=");
		sb.append(getApproved());
		sb.append(", approvedByUser=");
		sb.append(getApprovedByUser());
		sb.append(", approvedDate=");
		sb.append(getApprovedDate());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", visitorName=");
		sb.append(getVisitorName());
		sb.append(", visitorEmail=");
		sb.append(getVisitorEmail());
		sb.append(", visitorTel=");
		sb.append(getVisitorTel());
		sb.append(", visitorAddress=");
		sb.append(getVisitorAddress());
		sb.append(", draftId=");
		sb.append(getDraftId());
		sb.append(", hasAttachment=");
		sb.append(getHasAttachment());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("com.vportal.portlet.vlegal.model.VLegalSuggestDocument");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>sugId</column-name><column-value><![CDATA[");
		sb.append(getSugId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approved</column-name><column-value><![CDATA[");
		sb.append(getApproved());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approvedByUser</column-name><column-value><![CDATA[");
		sb.append(getApprovedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approvedDate</column-name><column-value><![CDATA[");
		sb.append(getApprovedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitorName</column-name><column-value><![CDATA[");
		sb.append(getVisitorName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitorEmail</column-name><column-value><![CDATA[");
		sb.append(getVisitorEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitorTel</column-name><column-value><![CDATA[");
		sb.append(getVisitorTel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitorAddress</column-name><column-value><![CDATA[");
		sb.append(getVisitorAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>draftId</column-name><column-value><![CDATA[");
		sb.append(getDraftId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hasAttachment</column-name><column-value><![CDATA[");
		sb.append(getHasAttachment());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _sugId;
	private String _originalSugId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createdDate;
	private Date _modifiedDate;
	private long _modifiedByUser;
	private boolean _approved;
	private long _approvedByUser;
	private Date _approvedDate;
	private String _title;
	private String _content;
	private String _language;
	private String _visitorName;
	private String _visitorEmail;
	private String _visitorTel;
	private String _visitorAddress;
	private String _draftId;
	private boolean _hasAttachment;
}