/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsArticleVersion service. Represents a row in the &quot;VcmsArticleVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsArticleVersionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsArticleVersionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a vcms article version model instance should use the {@link VcmsArticleVersion} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsArticleVersion
 * @see com.vportal.portlet.vcms.model.impl.VcmsArticleVersionImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsArticleVersionModelImpl
 * @generated
 */
public interface VcmsArticleVersionModel extends BaseModel<VcmsArticleVersion> {
	/**
	 * Gets the primary key of this vcms article version.
	 *
	 * @return the primary key of this vcms article version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vcms article version
	 *
	 * @param pk the primary key of this vcms article version
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the article version id of this vcms article version.
	 *
	 * @return the article version id of this vcms article version
	 */
	public long getArticleVersionId();

	/**
	 * Sets the article version id of this vcms article version.
	 *
	 * @param articleVersionId the article version id of this vcms article version
	 */
	public void setArticleVersionId(long articleVersionId);

	/**
	 * Gets the group id of this vcms article version.
	 *
	 * @return the group id of this vcms article version
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this vcms article version.
	 *
	 * @param groupId the group id of this vcms article version
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this vcms article version.
	 *
	 * @return the company id of this vcms article version
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this vcms article version.
	 *
	 * @param companyId the company id of this vcms article version
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the article id of this vcms article version.
	 *
	 * @return the article id of this vcms article version
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article id of this vcms article version.
	 *
	 * @param articleId the article id of this vcms article version
	 */
	public void setArticleId(String articleId);

	/**
	 * Gets the created by user of this vcms article version.
	 *
	 * @return the created by user of this vcms article version
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms article version.
	 *
	 * @param createdByUser the created by user of this vcms article version
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Gets the created date of this vcms article version.
	 *
	 * @return the created date of this vcms article version
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms article version.
	 *
	 * @param createdDate the created date of this vcms article version
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the type ids of this vcms article version.
	 *
	 * @return the type ids of this vcms article version
	 */
	@AutoEscape
	public String getTypeIds();

	/**
	 * Sets the type ids of this vcms article version.
	 *
	 * @param typeIds the type ids of this vcms article version
	 */
	public void setTypeIds(String typeIds);

	/**
	 * Gets the status of this vcms article version.
	 *
	 * @return the status of this vcms article version
	 */
	public long getStatus();

	/**
	 * Sets the status of this vcms article version.
	 *
	 * @param status the status of this vcms article version
	 */
	public void setStatus(long status);

	/**
	 * Gets the version name of this vcms article version.
	 *
	 * @return the version name of this vcms article version
	 */
	@AutoEscape
	public String getVersionName();

	/**
	 * Sets the version name of this vcms article version.
	 *
	 * @param versionName the version name of this vcms article version
	 */
	public void setVersionName(String versionName);

	/**
	 * Gets the title of this vcms article version.
	 *
	 * @return the title of this vcms article version
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this vcms article version.
	 *
	 * @param title the title of this vcms article version
	 */
	public void setTitle(String title);

	/**
	 * Gets the lead of this vcms article version.
	 *
	 * @return the lead of this vcms article version
	 */
	@AutoEscape
	public String getLead();

	/**
	 * Sets the lead of this vcms article version.
	 *
	 * @param lead the lead of this vcms article version
	 */
	public void setLead(String lead);

	/**
	 * Gets the content of this vcms article version.
	 *
	 * @return the content of this vcms article version
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this vcms article version.
	 *
	 * @param content the content of this vcms article version
	 */
	public void setContent(String content);

	/**
	 * Gets the has image of this vcms article version.
	 *
	 * @return the has image of this vcms article version
	 */
	public boolean getHasImage();

	/**
	 * Determines if this vcms article version is has image.
	 *
	 * @return <code>true</code> if this vcms article version is has image; <code>false</code> otherwise
	 */
	public boolean isHasImage();

	/**
	 * Sets whether this {$entity.humanName} is has image.
	 *
	 * @param hasImage the has image of this vcms article version
	 */
	public void setHasImage(boolean hasImage);

	/**
	 * Gets the image title of this vcms article version.
	 *
	 * @return the image title of this vcms article version
	 */
	@AutoEscape
	public String getImageTitle();

	/**
	 * Sets the image title of this vcms article version.
	 *
	 * @param imageTitle the image title of this vcms article version
	 */
	public void setImageTitle(String imageTitle);

	/**
	 * Gets the image of this vcms article version.
	 *
	 * @return the image of this vcms article version
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this vcms article version.
	 *
	 * @param image the image of this vcms article version
	 */
	public void setImage(String image);

	/**
	 * Gets the language of this vcms article version.
	 *
	 * @return the language of this vcms article version
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vcms article version.
	 *
	 * @param language the language of this vcms article version
	 */
	public void setLanguage(String language);

	/**
	 * Gets the user hit of this vcms article version.
	 *
	 * @return the user hit of this vcms article version
	 */
	public int getUserHit();

	/**
	 * Sets the user hit of this vcms article version.
	 *
	 * @param userHit the user hit of this vcms article version
	 */
	public void setUserHit(int userHit);

	/**
	 * Gets the author of this vcms article version.
	 *
	 * @return the author of this vcms article version
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this vcms article version.
	 *
	 * @param author the author of this vcms article version
	 */
	public void setAuthor(String author);

	/**
	 * Gets the source of this vcms article version.
	 *
	 * @return the source of this vcms article version
	 */
	@AutoEscape
	public String getSource();

	/**
	 * Sets the source of this vcms article version.
	 *
	 * @param source the source of this vcms article version
	 */
	public void setSource(String source);

	/**
	 * Gets the discussible of this vcms article version.
	 *
	 * @return the discussible of this vcms article version
	 */
	public boolean getDiscussible();

	/**
	 * Determines if this vcms article version is discussible.
	 *
	 * @return <code>true</code> if this vcms article version is discussible; <code>false</code> otherwise
	 */
	public boolean isDiscussible();

	/**
	 * Sets whether this {$entity.humanName} is discussible.
	 *
	 * @param discussible the discussible of this vcms article version
	 */
	public void setDiscussible(boolean discussible);

	/**
	 * Gets the has attachment of this vcms article version.
	 *
	 * @return the has attachment of this vcms article version
	 */
	public boolean getHasAttachment();

	/**
	 * Determines if this vcms article version is has attachment.
	 *
	 * @return <code>true</code> if this vcms article version is has attachment; <code>false</code> otherwise
	 */
	public boolean isHasAttachment();

	/**
	 * Sets whether this {$entity.humanName} is has attachment.
	 *
	 * @param hasAttachment the has attachment of this vcms article version
	 */
	public void setHasAttachment(boolean hasAttachment);

	/**
	 * Gets the has poll of this vcms article version.
	 *
	 * @return the has poll of this vcms article version
	 */
	public boolean getHasPoll();

	/**
	 * Determines if this vcms article version is has poll.
	 *
	 * @return <code>true</code> if this vcms article version is has poll; <code>false</code> otherwise
	 */
	public boolean isHasPoll();

	/**
	 * Sets whether this {$entity.humanName} is has poll.
	 *
	 * @param hasPoll the has poll of this vcms article version
	 */
	public void setHasPoll(boolean hasPoll);

	/**
	 * Gets the poll id of this vcms article version.
	 *
	 * @return the poll id of this vcms article version
	 */
	@AutoEscape
	public String getPollId();

	/**
	 * Sets the poll id of this vcms article version.
	 *
	 * @param pollId the poll id of this vcms article version
	 */
	public void setPollId(String pollId);

	/**
	 * Gets the effective date of this vcms article version.
	 *
	 * @return the effective date of this vcms article version
	 */
	public Date getEffectiveDate();

	/**
	 * Sets the effective date of this vcms article version.
	 *
	 * @param effectiveDate the effective date of this vcms article version
	 */
	public void setEffectiveDate(Date effectiveDate);

	/**
	 * Gets the expire date of this vcms article version.
	 *
	 * @return the expire date of this vcms article version
	 */
	public Date getExpireDate();

	/**
	 * Sets the expire date of this vcms article version.
	 *
	 * @param expireDate the expire date of this vcms article version
	 */
	public void setExpireDate(Date expireDate);

	/**
	 * Gets the sticky of this vcms article version.
	 *
	 * @return the sticky of this vcms article version
	 */
	public boolean getSticky();

	/**
	 * Determines if this vcms article version is sticky.
	 *
	 * @return <code>true</code> if this vcms article version is sticky; <code>false</code> otherwise
	 */
	public boolean isSticky();

	/**
	 * Sets whether this {$entity.humanName} is sticky.
	 *
	 * @param sticky the sticky of this vcms article version
	 */
	public void setSticky(boolean sticky);

	/**
	 * Gets the sticky never expired of this vcms article version.
	 *
	 * @return the sticky never expired of this vcms article version
	 */
	public boolean getStickyNeverExpired();

	/**
	 * Determines if this vcms article version is sticky never expired.
	 *
	 * @return <code>true</code> if this vcms article version is sticky never expired; <code>false</code> otherwise
	 */
	public boolean isStickyNeverExpired();

	/**
	 * Sets whether this {$entity.humanName} is sticky never expired.
	 *
	 * @param stickyNeverExpired the sticky never expired of this vcms article version
	 */
	public void setStickyNeverExpired(boolean stickyNeverExpired);

	/**
	 * Gets the sticky expire date of this vcms article version.
	 *
	 * @return the sticky expire date of this vcms article version
	 */
	public Date getStickyExpireDate();

	/**
	 * Sets the sticky expire date of this vcms article version.
	 *
	 * @param stickyExpireDate the sticky expire date of this vcms article version
	 */
	public void setStickyExpireDate(Date stickyExpireDate);

	/**
	 * Gets a copy of this vcms article version as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VcmsArticleVersion toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsArticleVersion vcmsArticleVersion);

	public int hashCode();

	public String toString();

	public String toXmlString();
}