/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsDiscussion service. Represents a row in the &quot;VcmsDiscussion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsDiscussionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsDiscussionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a vcms discussion model instance should use the {@link VcmsDiscussion} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsDiscussion
 * @see com.vportal.portlet.vcms.model.impl.VcmsDiscussionImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsDiscussionModelImpl
 * @generated
 */
public interface VcmsDiscussionModel extends BaseModel<VcmsDiscussion> {
	/**
	 * Gets the primary key of this vcms discussion.
	 *
	 * @return the primary key of this vcms discussion
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vcms discussion
	 *
	 * @param pk the primary key of this vcms discussion
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the discussion id of this vcms discussion.
	 *
	 * @return the discussion id of this vcms discussion
	 */
	@AutoEscape
	public String getDiscussionId();

	/**
	 * Sets the discussion id of this vcms discussion.
	 *
	 * @param discussionId the discussion id of this vcms discussion
	 */
	public void setDiscussionId(String discussionId);

	/**
	 * Gets the group id of this vcms discussion.
	 *
	 * @return the group id of this vcms discussion
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this vcms discussion.
	 *
	 * @param groupId the group id of this vcms discussion
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this vcms discussion.
	 *
	 * @return the company id of this vcms discussion
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this vcms discussion.
	 *
	 * @param companyId the company id of this vcms discussion
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the visitor name of this vcms discussion.
	 *
	 * @return the visitor name of this vcms discussion
	 */
	@AutoEscape
	public String getVisitorName();

	/**
	 * Sets the visitor name of this vcms discussion.
	 *
	 * @param visitorName the visitor name of this vcms discussion
	 */
	public void setVisitorName(String visitorName);

	/**
	 * Gets the visitor email of this vcms discussion.
	 *
	 * @return the visitor email of this vcms discussion
	 */
	@AutoEscape
	public String getVisitorEmail();

	/**
	 * Sets the visitor email of this vcms discussion.
	 *
	 * @param visitorEmail the visitor email of this vcms discussion
	 */
	public void setVisitorEmail(String visitorEmail);

	/**
	 * Gets the visitor phone of this vcms discussion.
	 *
	 * @return the visitor phone of this vcms discussion
	 */
	@AutoEscape
	public String getVisitorPhone();

	/**
	 * Sets the visitor phone of this vcms discussion.
	 *
	 * @param visitorPhone the visitor phone of this vcms discussion
	 */
	public void setVisitorPhone(String visitorPhone);

	/**
	 * Gets the posted date of this vcms discussion.
	 *
	 * @return the posted date of this vcms discussion
	 */
	public Date getPostedDate();

	/**
	 * Sets the posted date of this vcms discussion.
	 *
	 * @param postedDate the posted date of this vcms discussion
	 */
	public void setPostedDate(Date postedDate);

	/**
	 * Gets the approved of this vcms discussion.
	 *
	 * @return the approved of this vcms discussion
	 */
	public boolean getApproved();

	/**
	 * Determines if this vcms discussion is approved.
	 *
	 * @return <code>true</code> if this vcms discussion is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this {$entity.humanName} is approved.
	 *
	 * @param approved the approved of this vcms discussion
	 */
	public void setApproved(boolean approved);

	/**
	 * Gets the approved by user of this vcms discussion.
	 *
	 * @return the approved by user of this vcms discussion
	 */
	@AutoEscape
	public String getApprovedByUser();

	/**
	 * Sets the approved by user of this vcms discussion.
	 *
	 * @param approvedByUser the approved by user of this vcms discussion
	 */
	public void setApprovedByUser(String approvedByUser);

	/**
	 * Gets the approved date of this vcms discussion.
	 *
	 * @return the approved date of this vcms discussion
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this vcms discussion.
	 *
	 * @param approvedDate the approved date of this vcms discussion
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Gets the article id of this vcms discussion.
	 *
	 * @return the article id of this vcms discussion
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article id of this vcms discussion.
	 *
	 * @param articleId the article id of this vcms discussion
	 */
	public void setArticleId(String articleId);

	/**
	 * Gets the title of this vcms discussion.
	 *
	 * @return the title of this vcms discussion
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this vcms discussion.
	 *
	 * @param title the title of this vcms discussion
	 */
	public void setTitle(String title);

	/**
	 * Gets the content of this vcms discussion.
	 *
	 * @return the content of this vcms discussion
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this vcms discussion.
	 *
	 * @param content the content of this vcms discussion
	 */
	public void setContent(String content);

	/**
	 * Gets the language of this vcms discussion.
	 *
	 * @return the language of this vcms discussion
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vcms discussion.
	 *
	 * @param language the language of this vcms discussion
	 */
	public void setLanguage(String language);

	/**
	 * Gets the has attachment of this vcms discussion.
	 *
	 * @return the has attachment of this vcms discussion
	 */
	public boolean getHasAttachment();

	/**
	 * Determines if this vcms discussion is has attachment.
	 *
	 * @return <code>true</code> if this vcms discussion is has attachment; <code>false</code> otherwise
	 */
	public boolean isHasAttachment();

	/**
	 * Sets whether this {$entity.humanName} is has attachment.
	 *
	 * @param hasAttachment the has attachment of this vcms discussion
	 */
	public void setHasAttachment(boolean hasAttachment);

	/**
	 * Gets a copy of this vcms discussion as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VcmsDiscussion toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsDiscussion vcmsDiscussion);

	public int hashCode();

	public String toString();

	public String toXmlString();
}