/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VcmsPortion service. Represents a row in the &quot;VcmsPortion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsPortionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsPortionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a vcms portion model instance should use the {@link VcmsPortion} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsPortion
 * @see com.vportal.portlet.vcms.model.impl.VcmsPortionImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsPortionModelImpl
 * @generated
 */
public interface VcmsPortionModel extends BaseModel<VcmsPortion> {
	/**
	 * Gets the primary key of this vcms portion.
	 *
	 * @return the primary key of this vcms portion
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this vcms portion
	 *
	 * @param pk the primary key of this vcms portion
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the portion id of this vcms portion.
	 *
	 * @return the portion id of this vcms portion
	 */
	@AutoEscape
	public String getPortionId();

	/**
	 * Sets the portion id of this vcms portion.
	 *
	 * @param portionId the portion id of this vcms portion
	 */
	public void setPortionId(String portionId);

	/**
	 * Gets the group id of this vcms portion.
	 *
	 * @return the group id of this vcms portion
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this vcms portion.
	 *
	 * @param groupId the group id of this vcms portion
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this vcms portion.
	 *
	 * @return the company id of this vcms portion
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this vcms portion.
	 *
	 * @param companyId the company id of this vcms portion
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the created date of this vcms portion.
	 *
	 * @return the created date of this vcms portion
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vcms portion.
	 *
	 * @param createdDate the created date of this vcms portion
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the created by user of this vcms portion.
	 *
	 * @return the created by user of this vcms portion
	 */
	@AutoEscape
	public String getCreatedByUser();

	/**
	 * Sets the created by user of this vcms portion.
	 *
	 * @param createdByUser the created by user of this vcms portion
	 */
	public void setCreatedByUser(String createdByUser);

	/**
	 * Gets the modified date of this vcms portion.
	 *
	 * @return the modified date of this vcms portion
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vcms portion.
	 *
	 * @param modifiedDate the modified date of this vcms portion
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the modified by user of this vcms portion.
	 *
	 * @return the modified by user of this vcms portion
	 */
	@AutoEscape
	public String getModifiedByUser();

	/**
	 * Sets the modified by user of this vcms portion.
	 *
	 * @param modifiedByUser the modified by user of this vcms portion
	 */
	public void setModifiedByUser(String modifiedByUser);

	/**
	 * Gets the code of this vcms portion.
	 *
	 * @return the code of this vcms portion
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this vcms portion.
	 *
	 * @param code the code of this vcms portion
	 */
	public void setCode(String code);

	/**
	 * Gets the name of this vcms portion.
	 *
	 * @return the name of this vcms portion
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this vcms portion.
	 *
	 * @param name the name of this vcms portion
	 */
	public void setName(String name);

	/**
	 * Gets the description of this vcms portion.
	 *
	 * @return the description of this vcms portion
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vcms portion.
	 *
	 * @param description the description of this vcms portion
	 */
	public void setDescription(String description);

	/**
	 * Gets the categorizable of this vcms portion.
	 *
	 * @return the categorizable of this vcms portion
	 */
	public boolean getCategorizable();

	/**
	 * Determines if this vcms portion is categorizable.
	 *
	 * @return <code>true</code> if this vcms portion is categorizable; <code>false</code> otherwise
	 */
	public boolean isCategorizable();

	/**
	 * Sets whether this {$entity.humanName} is categorizable.
	 *
	 * @param categorizable the categorizable of this vcms portion
	 */
	public void setCategorizable(boolean categorizable);

	/**
	 * Gets the language of this vcms portion.
	 *
	 * @return the language of this vcms portion
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this vcms portion.
	 *
	 * @param language the language of this vcms portion
	 */
	public void setLanguage(String language);

	/**
	 * Gets a copy of this vcms portion as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VcmsPortion toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsPortion vcmsPortion);

	public int hashCode();

	public String toString();

	public String toXmlString();
}