/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vcms.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.vportal.portlet.vcms.service.persistence.VcmsTARelationPK;

import java.io.Serializable;

/**
 * The base model interface for the VcmsTARelation service. Represents a row in the &quot;VcmsTARelation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vcms.model.impl.VcmsTARelationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vcms.model.impl.VcmsTARelationImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a vcms t a relation model instance should use the {@link VcmsTARelation} interface instead.
 * </p>
 *
 * @author HOAN
 * @see VcmsTARelation
 * @see com.vportal.portlet.vcms.model.impl.VcmsTARelationImpl
 * @see com.vportal.portlet.vcms.model.impl.VcmsTARelationModelImpl
 * @generated
 */
public interface VcmsTARelationModel extends BaseModel<VcmsTARelation> {
	/**
	 * Gets the primary key of this vcms t a relation.
	 *
	 * @return the primary key of this vcms t a relation
	 */
	public VcmsTARelationPK getPrimaryKey();

	/**
	 * Sets the primary key of this vcms t a relation
	 *
	 * @param pk the primary key of this vcms t a relation
	 */
	public void setPrimaryKey(VcmsTARelationPK pk);

	/**
	 * Gets the thread id of this vcms t a relation.
	 *
	 * @return the thread id of this vcms t a relation
	 */
	@AutoEscape
	public String getThreadId();

	/**
	 * Sets the thread id of this vcms t a relation.
	 *
	 * @param threadId the thread id of this vcms t a relation
	 */
	public void setThreadId(String threadId);

	/**
	 * Gets the article id of this vcms t a relation.
	 *
	 * @return the article id of this vcms t a relation
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article id of this vcms t a relation.
	 *
	 * @param articleId the article id of this vcms t a relation
	 */
	public void setArticleId(String articleId);

	/**
	 * Gets a copy of this vcms t a relation as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VcmsTARelation toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VcmsTARelation vcmsTARelation);

	public int hashCode();

	public String toString();

	public String toXmlString();
}