/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalDraftDocument service. Represents a row in the &quot;VLegalDraftDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalDraftDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalDraftDocumentImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal draft document model instance should use the {@link VLegalDraftDocument} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalDraftDocument
 * @see com.vportal.portlet.vlegal.model.impl.VLegalDraftDocumentImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalDraftDocumentModelImpl
 * @generated
 */
public interface VLegalDraftDocumentModel extends BaseModel<VLegalDraftDocument> {
	/**
	 * Gets the primary key of this v legal draft document.
	 *
	 * @return the primary key of this v legal draft document
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal draft document
	 *
	 * @param pk the primary key of this v legal draft document
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the draft id of this v legal draft document.
	 *
	 * @return the draft id of this v legal draft document
	 */
	@AutoEscape
	public String getDraftId();

	/**
	 * Sets the draft id of this v legal draft document.
	 *
	 * @param draftId the draft id of this v legal draft document
	 */
	public void setDraftId(String draftId);

	/**
	 * Gets the group id of this v legal draft document.
	 *
	 * @return the group id of this v legal draft document
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this v legal draft document.
	 *
	 * @param groupId the group id of this v legal draft document
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this v legal draft document.
	 *
	 * @return the company id of this v legal draft document
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this v legal draft document.
	 *
	 * @param companyId the company id of this v legal draft document
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this v legal draft document.
	 *
	 * @return the user id of this v legal draft document
	 */
	public long getUserId();

	/**
	 * Sets the user id of this v legal draft document.
	 *
	 * @param userId the user id of this v legal draft document
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this v legal draft document.
	 *
	 * @return the user uuid of this v legal draft document
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v legal draft document.
	 *
	 * @param userUuid the user uuid of this v legal draft document
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the created by user of this v legal draft document.
	 *
	 * @return the created by user of this v legal draft document
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal draft document.
	 *
	 * @param createdByUser the created by user of this v legal draft document
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Gets the created date of this v legal draft document.
	 *
	 * @return the created date of this v legal draft document
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal draft document.
	 *
	 * @param createdDate the created date of this v legal draft document
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the modified by user of this v legal draft document.
	 *
	 * @return the modified by user of this v legal draft document
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this v legal draft document.
	 *
	 * @param modifiedByUser the modified by user of this v legal draft document
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Gets the modified date of this v legal draft document.
	 *
	 * @return the modified date of this v legal draft document
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal draft document.
	 *
	 * @param modifiedDate the modified date of this v legal draft document
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the approved by user of this v legal draft document.
	 *
	 * @return the approved by user of this v legal draft document
	 */
	public long getApprovedByUser();

	/**
	 * Sets the approved by user of this v legal draft document.
	 *
	 * @param approvedByUser the approved by user of this v legal draft document
	 */
	public void setApprovedByUser(long approvedByUser);

	/**
	 * Gets the approved date of this v legal draft document.
	 *
	 * @return the approved date of this v legal draft document
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this v legal draft document.
	 *
	 * @param approvedDate the approved date of this v legal draft document
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Gets the published by user of this v legal draft document.
	 *
	 * @return the published by user of this v legal draft document
	 */
	public long getPublishedByUser();

	/**
	 * Sets the published by user of this v legal draft document.
	 *
	 * @param publishedByUser the published by user of this v legal draft document
	 */
	public void setPublishedByUser(long publishedByUser);

	/**
	 * Gets the published date of this v legal draft document.
	 *
	 * @return the published date of this v legal draft document
	 */
	public Date getPublishedDate();

	/**
	 * Sets the published date of this v legal draft document.
	 *
	 * @param publishedDate the published date of this v legal draft document
	 */
	public void setPublishedDate(Date publishedDate);

	/**
	 * Gets the title of this v legal draft document.
	 *
	 * @return the title of this v legal draft document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this v legal draft document.
	 *
	 * @param title the title of this v legal draft document
	 */
	public void setTitle(String title);

	/**
	 * Gets the expired date of this v legal draft document.
	 *
	 * @return the expired date of this v legal draft document
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this v legal draft document.
	 *
	 * @param expiredDate the expired date of this v legal draft document
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Gets the language of this v legal draft document.
	 *
	 * @return the language of this v legal draft document
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this v legal draft document.
	 *
	 * @param language the language of this v legal draft document
	 */
	public void setLanguage(String language);

	/**
	 * Gets the content of this v legal draft document.
	 *
	 * @return the content of this v legal draft document
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this v legal draft document.
	 *
	 * @param content the content of this v legal draft document
	 */
	public void setContent(String content);

	/**
	 * Gets the type id of this v legal draft document.
	 *
	 * @return the type id of this v legal draft document
	 */
	@AutoEscape
	public String getTypeId();

	/**
	 * Sets the type id of this v legal draft document.
	 *
	 * @param typeId the type id of this v legal draft document
	 */
	public void setTypeId(String typeId);

	/**
	 * Gets the field id of this v legal draft document.
	 *
	 * @return the field id of this v legal draft document
	 */
	@AutoEscape
	public String getFieldId();

	/**
	 * Sets the field id of this v legal draft document.
	 *
	 * @param fieldId the field id of this v legal draft document
	 */
	public void setFieldId(String fieldId);

	/**
	 * Gets the has attachment of this v legal draft document.
	 *
	 * @return the has attachment of this v legal draft document
	 */
	public boolean getHasAttachment();

	/**
	 * Determines if this v legal draft document is has attachment.
	 *
	 * @return <code>true</code> if this v legal draft document is has attachment; <code>false</code> otherwise
	 */
	public boolean isHasAttachment();

	/**
	 * Sets whether this {$entity.humanName} is has attachment.
	 *
	 * @param hasAttachment the has attachment of this v legal draft document
	 */
	public void setHasAttachment(boolean hasAttachment);

	/**
	 * Gets the draft level of this v legal draft document.
	 *
	 * @return the draft level of this v legal draft document
	 */
	public int getDraftLevel();

	/**
	 * Sets the draft level of this v legal draft document.
	 *
	 * @param draftLevel the draft level of this v legal draft document
	 */
	public void setDraftLevel(int draftLevel);

	/**
	 * Gets the doc code of this v legal draft document.
	 *
	 * @return the doc code of this v legal draft document
	 */
	@AutoEscape
	public String getDocCode();

	/**
	 * Sets the doc code of this v legal draft document.
	 *
	 * @param docCode the doc code of this v legal draft document
	 */
	public void setDocCode(String docCode);

	/**
	 * Gets the status draft of this v legal draft document.
	 *
	 * @return the status draft of this v legal draft document
	 */
	public int getStatusDraft();

	/**
	 * Sets the status draft of this v legal draft document.
	 *
	 * @param statusDraft the status draft of this v legal draft document
	 */
	public void setStatusDraft(int statusDraft);

	/**
	 * Gets a copy of this v legal draft document as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalDraftDocument toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalDraftDocument vLegalDraftDocument);

	public int hashCode();

	public String toString();

	public String toXmlString();
}