/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VLegalSigner service. Represents a row in the &quot;VLegalSigner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalSignerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalSignerImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal signer model instance should use the {@link VLegalSigner} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalSigner
 * @see com.vportal.portlet.vlegal.model.impl.VLegalSignerImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalSignerModelImpl
 * @generated
 */
public interface VLegalSignerModel extends BaseModel<VLegalSigner> {
	/**
	 * Gets the primary key of this v legal signer.
	 *
	 * @return the primary key of this v legal signer
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v legal signer
	 *
	 * @param pk the primary key of this v legal signer
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the sig id of this v legal signer.
	 *
	 * @return the sig id of this v legal signer
	 */
	@AutoEscape
	public String getSigId();

	/**
	 * Sets the sig id of this v legal signer.
	 *
	 * @param sigId the sig id of this v legal signer
	 */
	public void setSigId(String sigId);

	/**
	 * Gets the group id of this v legal signer.
	 *
	 * @return the group id of this v legal signer
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this v legal signer.
	 *
	 * @param groupId the group id of this v legal signer
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this v legal signer.
	 *
	 * @return the company id of this v legal signer
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this v legal signer.
	 *
	 * @param companyId the company id of this v legal signer
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this v legal signer.
	 *
	 * @return the user id of this v legal signer
	 */
	public long getUserId();

	/**
	 * Sets the user id of this v legal signer.
	 *
	 * @param userId the user id of this v legal signer
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this v legal signer.
	 *
	 * @return the user uuid of this v legal signer
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this v legal signer.
	 *
	 * @param userUuid the user uuid of this v legal signer
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the created date of this v legal signer.
	 *
	 * @return the created date of this v legal signer
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this v legal signer.
	 *
	 * @param createdDate the created date of this v legal signer
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the modified date of this v legal signer.
	 *
	 * @return the modified date of this v legal signer
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this v legal signer.
	 *
	 * @param modifiedDate the modified date of this v legal signer
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the created by user of this v legal signer.
	 *
	 * @return the created by user of this v legal signer
	 */
	public long getCreatedByUser();

	/**
	 * Sets the created by user of this v legal signer.
	 *
	 * @param createdByUser the created by user of this v legal signer
	 */
	public void setCreatedByUser(long createdByUser);

	/**
	 * Gets the modified by user of this v legal signer.
	 *
	 * @return the modified by user of this v legal signer
	 */
	public long getModifiedByUser();

	/**
	 * Sets the modified by user of this v legal signer.
	 *
	 * @param modifiedByUser the modified by user of this v legal signer
	 */
	public void setModifiedByUser(long modifiedByUser);

	/**
	 * Gets the first name of this v legal signer.
	 *
	 * @return the first name of this v legal signer
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this v legal signer.
	 *
	 * @param firstName the first name of this v legal signer
	 */
	public void setFirstName(String firstName);

	/**
	 * Gets the last name of this v legal signer.
	 *
	 * @return the last name of this v legal signer
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this v legal signer.
	 *
	 * @param lastName the last name of this v legal signer
	 */
	public void setLastName(String lastName);

	/**
	 * Gets the language of this v legal signer.
	 *
	 * @return the language of this v legal signer
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this v legal signer.
	 *
	 * @param language the language of this v legal signer
	 */
	public void setLanguage(String language);

	/**
	 * Gets the status signer of this v legal signer.
	 *
	 * @return the status signer of this v legal signer
	 */
	public boolean getStatusSigner();

	/**
	 * Determines if this v legal signer is status signer.
	 *
	 * @return <code>true</code> if this v legal signer is status signer; <code>false</code> otherwise
	 */
	public boolean isStatusSigner();

	/**
	 * Sets whether this {$entity.humanName} is status signer.
	 *
	 * @param statusSigner the status signer of this v legal signer
	 */
	public void setStatusSigner(boolean statusSigner);

	/**
	 * Gets a copy of this v legal signer as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalSigner toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalSigner vLegalSigner);

	public int hashCode();

	public String toString();

	public String toXmlString();
}