/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.vportal.portlet.vlegal.service.persistence.VLegalDURelPK;

import java.io.Serializable;

/**
 * The base model interface for the VLegalDURel service. Represents a row in the &quot;VLegalDURel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalDURelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalDURelImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal d u rel model instance should use the {@link VLegalDURel} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalDURel
 * @see com.vportal.portlet.vlegal.model.impl.VLegalDURelImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalDURelModelImpl
 * @generated
 */
public interface VLegalDURelModel extends BaseModel<VLegalDURel> {
	/**
	 * Gets the primary key of this v legal d u rel.
	 *
	 * @return the primary key of this v legal d u rel
	 */
	public VLegalDURelPK getPrimaryKey();

	/**
	 * Sets the primary key of this v legal d u rel
	 *
	 * @param pk the primary key of this v legal d u rel
	 */
	public void setPrimaryKey(VLegalDURelPK pk);

	/**
	 * Gets the department id of this v legal d u rel.
	 *
	 * @return the department id of this v legal d u rel
	 */
	public long getDepartmentId();

	/**
	 * Sets the department id of this v legal d u rel.
	 *
	 * @param departmentId the department id of this v legal d u rel
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Gets the userid of this v legal d u rel.
	 *
	 * @return the userid of this v legal d u rel
	 */
	public long getUserid();

	/**
	 * Sets the userid of this v legal d u rel.
	 *
	 * @param userid the userid of this v legal d u rel
	 */
	public void setUserid(long userid);

	/**
	 * Gets a copy of this v legal d u rel as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalDURel toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalDURel vLegalDURel);

	public int hashCode();

	public String toString();

	public String toXmlString();
}