/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlegal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.vportal.portlet.vlegal.service.persistence.VLegalTDRelPK;

import java.io.Serializable;

/**
 * The base model interface for the VLegalTDRel service. Represents a row in the &quot;VLegalTDRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlegal.model.impl.VLegalTDRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlegal.model.impl.VLegalTDRelImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v legal t d rel model instance should use the {@link VLegalTDRel} interface instead.
 * </p>
 *
 * @author ACB
 * @see VLegalTDRel
 * @see com.vportal.portlet.vlegal.model.impl.VLegalTDRelImpl
 * @see com.vportal.portlet.vlegal.model.impl.VLegalTDRelModelImpl
 * @generated
 */
public interface VLegalTDRelModel extends BaseModel<VLegalTDRel> {
	/**
	 * Gets the primary key of this v legal t d rel.
	 *
	 * @return the primary key of this v legal t d rel
	 */
	public VLegalTDRelPK getPrimaryKey();

	/**
	 * Sets the primary key of this v legal t d rel
	 *
	 * @param pk the primary key of this v legal t d rel
	 */
	public void setPrimaryKey(VLegalTDRelPK pk);

	/**
	 * Gets the doc id of this v legal t d rel.
	 *
	 * @return the doc id of this v legal t d rel
	 */
	@AutoEscape
	public String getDocId();

	/**
	 * Sets the doc id of this v legal t d rel.
	 *
	 * @param docId the doc id of this v legal t d rel
	 */
	public void setDocId(String docId);

	/**
	 * Gets the tag id of this v legal t d rel.
	 *
	 * @return the tag id of this v legal t d rel
	 */
	@AutoEscape
	public String getTagId();

	/**
	 * Sets the tag id of this v legal t d rel.
	 *
	 * @param tagId the tag id of this v legal t d rel
	 */
	public void setTagId(String tagId);

	/**
	 * Gets a copy of this v legal t d rel as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VLegalTDRel toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VLegalTDRel vLegalTDRel);

	public int hashCode();

	public String toString();

	public String toXmlString();
}