/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vsi.edirectory.portlet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vsi.edirectory.portlet.model.EDFunctionEmployee;
import com.vsi.edirectory.portlet.model.EDFunctionEmployeeModel;
import com.vsi.edirectory.portlet.model.EDFunctionEmployeeSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the EDFunctionEmployee service. Represents a row in the &quot;EDFunctionEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vsi.edirectory.portlet.model.EDFunctionEmployeeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EDFunctionEmployeeImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a e d function employee model instance should use the {@link com.vsi.edirectory.portlet.model.EDFunctionEmployee} interface instead.
 * </p>
 *
 * @author vinhnt
 * @see EDFunctionEmployeeImpl
 * @see com.vsi.edirectory.portlet.model.EDFunctionEmployee
 * @see com.vsi.edirectory.portlet.model.EDFunctionEmployeeModel
 * @generated
 */
public class EDFunctionEmployeeModelImpl extends BaseModelImpl<EDFunctionEmployee>
	implements EDFunctionEmployeeModel {
	public static final String TABLE_NAME = "EDFunctionEmployee";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", new Integer(Types.VARCHAR) },
			{ "id_", new Integer(Types.BIGINT) },
			{ "functionId", new Integer(Types.BIGINT) },
			{ "employeeId", new Integer(Types.BIGINT) }
		};
	public static final String TABLE_SQL_CREATE = "create table EDFunctionEmployee (uuid_ VARCHAR(75) null,id_ LONG not null primary key,functionId LONG,employeeId LONG)";
	public static final String TABLE_SQL_DROP = "drop table EDFunctionEmployee";
	public static final String ORDER_BY_JPQL = " ORDER BY edFunctionEmployee.functionId ASC, edFunctionEmployee.employeeId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EDFunctionEmployee.functionId ASC, EDFunctionEmployee.employeeId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vsi.edirectory.portlet.model.EDFunctionEmployee"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vsi.edirectory.portlet.model.EDFunctionEmployee"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EDFunctionEmployee toModel(EDFunctionEmployeeSoap soapModel) {
		EDFunctionEmployee model = new EDFunctionEmployeeImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setFunctionId(soapModel.getFunctionId());
		model.setEmployeeId(soapModel.getEmployeeId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EDFunctionEmployee> toModels(
		EDFunctionEmployeeSoap[] soapModels) {
		List<EDFunctionEmployee> models = new ArrayList<EDFunctionEmployee>(soapModels.length);

		for (EDFunctionEmployeeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vsi.edirectory.portlet.model.EDFunctionEmployee"));

	public EDFunctionEmployeeModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long pk) {
		setId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		_uuid = uuid;
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public long getFunctionId() {
		return _functionId;
	}

	public void setFunctionId(long functionId) {
		_functionId = functionId;
	}

	public long getEmployeeId() {
		return _employeeId;
	}

	public void setEmployeeId(long employeeId) {
		_employeeId = employeeId;
	}

	public EDFunctionEmployee toEscapedModel() {
		if (isEscapedModel()) {
			return (EDFunctionEmployee)this;
		}
		else {
			return (EDFunctionEmployee)Proxy.newProxyInstance(EDFunctionEmployee.class.getClassLoader(),
				new Class[] { EDFunctionEmployee.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					EDFunctionEmployee.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		EDFunctionEmployeeImpl edFunctionEmployeeImpl = new EDFunctionEmployeeImpl();

		edFunctionEmployeeImpl.setUuid(getUuid());

		edFunctionEmployeeImpl.setId(getId());

		edFunctionEmployeeImpl.setFunctionId(getFunctionId());

		edFunctionEmployeeImpl.setEmployeeId(getEmployeeId());

		return edFunctionEmployeeImpl;
	}

	public int compareTo(EDFunctionEmployee edFunctionEmployee) {
		int value = 0;

		if (getFunctionId() < edFunctionEmployee.getFunctionId()) {
			value = -1;
		}
		else if (getFunctionId() > edFunctionEmployee.getFunctionId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getEmployeeId() < edFunctionEmployee.getEmployeeId()) {
			value = -1;
		}
		else if (getEmployeeId() > edFunctionEmployee.getEmployeeId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		EDFunctionEmployee edFunctionEmployee = null;

		try {
			edFunctionEmployee = (EDFunctionEmployee)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = edFunctionEmployee.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", id=");
		sb.append(getId());
		sb.append(", functionId=");
		sb.append(getFunctionId());
		sb.append(", employeeId=");
		sb.append(getEmployeeId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.vsi.edirectory.portlet.model.EDFunctionEmployee");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>functionId</column-name><column-value><![CDATA[");
		sb.append(getFunctionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeId</column-name><column-value><![CDATA[");
		sb.append(getEmployeeId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _uuid;
	private long _id;
	private long _functionId;
	private long _employeeId;
	private transient ExpandoBridge _expandoBridge;
}