/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vsi.edirectory.portlet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.vsi.edirectory.portlet.model.EDFunction;
import com.vsi.edirectory.portlet.model.EDFunctionModel;
import com.vsi.edirectory.portlet.model.EDFunctionSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the EDFunction service. Represents a row in the &quot;EDFunction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.vsi.edirectory.portlet.model.EDFunctionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EDFunctionImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a e d function model instance should use the {@link com.vsi.edirectory.portlet.model.EDFunction} interface instead.
 * </p>
 *
 * @author vinhnt
 * @see EDFunctionImpl
 * @see com.vsi.edirectory.portlet.model.EDFunction
 * @see com.vsi.edirectory.portlet.model.EDFunctionModel
 * @generated
 */
public class EDFunctionModelImpl extends BaseModelImpl<EDFunction>
	implements EDFunctionModel {
	public static final String TABLE_NAME = "EDFunction";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", new Integer(Types.BIGINT) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "name", new Integer(Types.VARCHAR) },
			{ "levelEd", new Integer(Types.INTEGER) },
			{ "isShowTree", new Integer(Types.BOOLEAN) },
			{ "description", new Integer(Types.VARCHAR) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "languageId", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table EDFunction (id_ LONG not null primary key,createdDate DATE null,name VARCHAR(500) null,levelEd INTEGER,isShowTree BOOLEAN,description VARCHAR(1000) null,groupId LONG,userId LONG,companyId LONG,languageId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table EDFunction";
	public static final String ORDER_BY_JPQL = " ORDER BY edFunction.levelEd ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EDFunction.levelEd ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.vsi.edirectory.portlet.model.EDFunction"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.vsi.edirectory.portlet.model.EDFunction"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EDFunction toModel(EDFunctionSoap soapModel) {
		EDFunction model = new EDFunctionImpl();

		model.setId(soapModel.getId());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setName(soapModel.getName());
		model.setLevelEd(soapModel.getLevelEd());
		model.setIsShowTree(soapModel.getIsShowTree());
		model.setDescription(soapModel.getDescription());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setLanguageId(soapModel.getLanguageId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EDFunction> toModels(EDFunctionSoap[] soapModels) {
		List<EDFunction> models = new ArrayList<EDFunction>(soapModels.length);

		for (EDFunctionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.vsi.edirectory.portlet.model.EDFunction"));

	public EDFunctionModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long pk) {
		setId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public int getLevelEd() {
		return _levelEd;
	}

	public void setLevelEd(int levelEd) {
		_levelEd = levelEd;
	}

	public boolean getIsShowTree() {
		return _isShowTree;
	}

	public boolean isIsShowTree() {
		return _isShowTree;
	}

	public void setIsShowTree(boolean isShowTree) {
		_isShowTree = isShowTree;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public String getLanguageId() {
		if (_languageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageId;
		}
	}

	public void setLanguageId(String languageId) {
		_languageId = languageId;
	}

	public EDFunction toEscapedModel() {
		if (isEscapedModel()) {
			return (EDFunction)this;
		}
		else {
			return (EDFunction)Proxy.newProxyInstance(EDFunction.class.getClassLoader(),
				new Class[] { EDFunction.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					EDFunction.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		EDFunctionImpl edFunctionImpl = new EDFunctionImpl();

		edFunctionImpl.setId(getId());

		EDFunctionModelImpl edFunctionModelImpl = edFunctionImpl;

		edFunctionModelImpl._originalId = edFunctionModelImpl._id;

		edFunctionModelImpl._setOriginalId = false;
		edFunctionImpl.setCreatedDate(getCreatedDate());

		edFunctionImpl.setName(getName());

		edFunctionImpl.setLevelEd(getLevelEd());

		edFunctionImpl.setIsShowTree(getIsShowTree());

		edFunctionImpl.setDescription(getDescription());

		edFunctionImpl.setGroupId(getGroupId());

		edFunctionModelImpl._originalGroupId = edFunctionModelImpl._groupId;

		edFunctionModelImpl._setOriginalGroupId = false;
		edFunctionImpl.setUserId(getUserId());

		edFunctionImpl.setCompanyId(getCompanyId());

		edFunctionImpl.setLanguageId(getLanguageId());

		return edFunctionImpl;
	}

	public int compareTo(EDFunction edFunction) {
		int value = 0;

		if (getLevelEd() < edFunction.getLevelEd()) {
			value = -1;
		}
		else if (getLevelEd() > edFunction.getLevelEd()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		EDFunction edFunction = null;

		try {
			edFunction = (EDFunction)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = edFunction.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", levelEd=");
		sb.append(getLevelEd());
		sb.append(", isShowTree=");
		sb.append(getIsShowTree());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.vsi.edirectory.portlet.model.EDFunction");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>levelEd</column-name><column-value><![CDATA[");
		sb.append(getLevelEd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isShowTree</column-name><column-value><![CDATA[");
		sb.append(getIsShowTree());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private Date _createdDate;
	private String _name;
	private int _levelEd;
	private boolean _isShowTree;
	private String _description;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private long _companyId;
	private String _languageId;
	private transient ExpandoBridge _expandoBridge;
}