/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vsearch.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.mail.service.MailService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.CompanyLocalService;
import com.liferay.portal.service.CompanyService;
import com.liferay.portal.service.PortletPreferencesLocalService;
import com.liferay.portal.service.PortletPreferencesService;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.CompanyPersistence;
import com.liferay.portal.service.persistence.PortletPreferencesPersistence;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.vportal.portlet.vsearch.model.VConfigSearch;
import com.vportal.portlet.vsearch.service.VConfigSearchLocalService;
import com.vportal.portlet.vsearch.service.VConfigSearchService;
import com.vportal.portlet.vsearch.service.persistence.VConfigSearchPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the v config search local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.vportal.portlet.vsearch.service.impl.VConfigSearchLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.vportal.portlet.vsearch.service.VConfigSearchLocalServiceUtil} to access the v config search local service.
 * </p>
 *
 * @author Ba
 * @see com.vportal.portlet.vsearch.service.impl.VConfigSearchLocalServiceImpl
 * @see com.vportal.portlet.vsearch.service.VConfigSearchLocalServiceUtil
 * @generated
 */
public abstract class VConfigSearchLocalServiceBaseImpl
	implements VConfigSearchLocalService {
	/**
	 * Adds the v config search to the database. Also notifies the appropriate model listeners.
	 *
	 * @param vConfigSearch the v config search to add
	 * @return the v config search that was added
	 * @throws SystemException if a system exception occurred
	 */
	public VConfigSearch addVConfigSearch(VConfigSearch vConfigSearch)
		throws SystemException {
		vConfigSearch.setNew(true);

		return vConfigSearchPersistence.update(vConfigSearch, false);
	}

	/**
	 * Creates a new v config search with the primary key. Does not add the v config search to the database.
	 *
	 * @param confisearchId the primary key for the new v config search
	 * @return the new v config search
	 */
	public VConfigSearch createVConfigSearch(long confisearchId) {
		return vConfigSearchPersistence.create(confisearchId);
	}

	/**
	 * Deletes the v config search with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param confisearchId the primary key of the v config search to delete
	 * @throws PortalException if a v config search with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteVConfigSearch(long confisearchId)
		throws PortalException, SystemException {
		vConfigSearchPersistence.remove(confisearchId);
	}

	/**
	 * Deletes the v config search from the database. Also notifies the appropriate model listeners.
	 *
	 * @param vConfigSearch the v config search to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteVConfigSearch(VConfigSearch vConfigSearch)
		throws SystemException {
		vConfigSearchPersistence.remove(vConfigSearch);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return vConfigSearchPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return vConfigSearchPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return vConfigSearchPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return vConfigSearchPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the v config search with the primary key.
	 *
	 * @param confisearchId the primary key of the v config search to get
	 * @return the v config search
	 * @throws PortalException if a v config search with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public VConfigSearch getVConfigSearch(long confisearchId)
		throws PortalException, SystemException {
		return vConfigSearchPersistence.findByPrimaryKey(confisearchId);
	}

	/**
	 * Gets a range of all the v config searchs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of v config searchs to return
	 * @param end the upper bound of the range of v config searchs to return (not inclusive)
	 * @return the range of v config searchs
	 * @throws SystemException if a system exception occurred
	 */
	public List<VConfigSearch> getVConfigSearchs(int start, int end)
		throws SystemException {
		return vConfigSearchPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of v config searchs.
	 *
	 * @return the number of v config searchs
	 * @throws SystemException if a system exception occurred
	 */
	public int getVConfigSearchsCount() throws SystemException {
		return vConfigSearchPersistence.countAll();
	}

	/**
	 * Updates the v config search in the database. Also notifies the appropriate model listeners.
	 *
	 * @param vConfigSearch the v config search to update
	 * @return the v config search that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public VConfigSearch updateVConfigSearch(VConfigSearch vConfigSearch)
		throws SystemException {
		vConfigSearch.setNew(false);

		return vConfigSearchPersistence.update(vConfigSearch, true);
	}

	/**
	 * Updates the v config search in the database. Also notifies the appropriate model listeners.
	 *
	 * @param vConfigSearch the v config search to update
	 * @param merge whether to merge the v config search with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the v config search that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public VConfigSearch updateVConfigSearch(VConfigSearch vConfigSearch,
		boolean merge) throws SystemException {
		vConfigSearch.setNew(false);

		return vConfigSearchPersistence.update(vConfigSearch, merge);
	}

	/**
	 * Gets the v config search local service.
	 *
	 * @return the v config search local service
	 */
	public VConfigSearchLocalService getVConfigSearchLocalService() {
		return vConfigSearchLocalService;
	}

	/**
	 * Sets the v config search local service.
	 *
	 * @param vConfigSearchLocalService the v config search local service
	 */
	public void setVConfigSearchLocalService(
		VConfigSearchLocalService vConfigSearchLocalService) {
		this.vConfigSearchLocalService = vConfigSearchLocalService;
	}

	/**
	 * Gets the v config search remote service.
	 *
	 * @return the v config search remote service
	 */
	public VConfigSearchService getVConfigSearchService() {
		return vConfigSearchService;
	}

	/**
	 * Sets the v config search remote service.
	 *
	 * @param vConfigSearchService the v config search remote service
	 */
	public void setVConfigSearchService(
		VConfigSearchService vConfigSearchService) {
		this.vConfigSearchService = vConfigSearchService;
	}

	/**
	 * Gets the v config search persistence.
	 *
	 * @return the v config search persistence
	 */
	public VConfigSearchPersistence getVConfigSearchPersistence() {
		return vConfigSearchPersistence;
	}

	/**
	 * Sets the v config search persistence.
	 *
	 * @param vConfigSearchPersistence the v config search persistence
	 */
	public void setVConfigSearchPersistence(
		VConfigSearchPersistence vConfigSearchPersistence) {
		this.vConfigSearchPersistence = vConfigSearchPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the mail remote service.
	 *
	 * @return the mail remote service
	 */
	public MailService getMailService() {
		return mailService;
	}

	/**
	 * Sets the mail remote service.
	 *
	 * @param mailService the mail remote service
	 */
	public void setMailService(MailService mailService) {
		this.mailService = mailService;
	}

	/**
	 * Gets the company local service.
	 *
	 * @return the company local service
	 */
	public CompanyLocalService getCompanyLocalService() {
		return companyLocalService;
	}

	/**
	 * Sets the company local service.
	 *
	 * @param companyLocalService the company local service
	 */
	public void setCompanyLocalService(CompanyLocalService companyLocalService) {
		this.companyLocalService = companyLocalService;
	}

	/**
	 * Gets the company remote service.
	 *
	 * @return the company remote service
	 */
	public CompanyService getCompanyService() {
		return companyService;
	}

	/**
	 * Sets the company remote service.
	 *
	 * @param companyService the company remote service
	 */
	public void setCompanyService(CompanyService companyService) {
		this.companyService = companyService;
	}

	/**
	 * Gets the company persistence.
	 *
	 * @return the company persistence
	 */
	public CompanyPersistence getCompanyPersistence() {
		return companyPersistence;
	}

	/**
	 * Sets the company persistence.
	 *
	 * @param companyPersistence the company persistence
	 */
	public void setCompanyPersistence(CompanyPersistence companyPersistence) {
		this.companyPersistence = companyPersistence;
	}

	/**
	 * Gets the portlet preferences local service.
	 *
	 * @return the portlet preferences local service
	 */
	public PortletPreferencesLocalService getPortletPreferencesLocalService() {
		return portletPreferencesLocalService;
	}

	/**
	 * Sets the portlet preferences local service.
	 *
	 * @param portletPreferencesLocalService the portlet preferences local service
	 */
	public void setPortletPreferencesLocalService(
		PortletPreferencesLocalService portletPreferencesLocalService) {
		this.portletPreferencesLocalService = portletPreferencesLocalService;
	}

	/**
	 * Gets the portlet preferences remote service.
	 *
	 * @return the portlet preferences remote service
	 */
	public PortletPreferencesService getPortletPreferencesService() {
		return portletPreferencesService;
	}

	/**
	 * Sets the portlet preferences remote service.
	 *
	 * @param portletPreferencesService the portlet preferences remote service
	 */
	public void setPortletPreferencesService(
		PortletPreferencesService portletPreferencesService) {
		this.portletPreferencesService = portletPreferencesService;
	}

	/**
	 * Gets the portlet preferences persistence.
	 *
	 * @return the portlet preferences persistence
	 */
	public PortletPreferencesPersistence getPortletPreferencesPersistence() {
		return portletPreferencesPersistence;
	}

	/**
	 * Sets the portlet preferences persistence.
	 *
	 * @param portletPreferencesPersistence the portlet preferences persistence
	 */
	public void setPortletPreferencesPersistence(
		PortletPreferencesPersistence portletPreferencesPersistence) {
		this.portletPreferencesPersistence = portletPreferencesPersistence;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = vConfigSearchPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = VConfigSearchLocalService.class)
	protected VConfigSearchLocalService vConfigSearchLocalService;
	@BeanReference(type = VConfigSearchService.class)
	protected VConfigSearchService vConfigSearchService;
	@BeanReference(type = VConfigSearchPersistence.class)
	protected VConfigSearchPersistence vConfigSearchPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = MailService.class)
	protected MailService mailService;
	@BeanReference(type = CompanyLocalService.class)
	protected CompanyLocalService companyLocalService;
	@BeanReference(type = CompanyService.class)
	protected CompanyService companyService;
	@BeanReference(type = CompanyPersistence.class)
	protected CompanyPersistence companyPersistence;
	@BeanReference(type = PortletPreferencesLocalService.class)
	protected PortletPreferencesLocalService portletPreferencesLocalService;
	@BeanReference(type = PortletPreferencesService.class)
	protected PortletPreferencesService portletPreferencesService;
	@BeanReference(type = PortletPreferencesPersistence.class)
	protected PortletPreferencesPersistence portletPreferencesPersistence;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}