/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portal.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AccessCounter service. Represents a row in the &quot;AccessCounter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portal.model.impl.AccessCounterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portal.model.impl.AccessCounterImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a access counter model instance should use the {@link AccessCounter} interface instead.
 * </p>
 *
 * @author HOAN
 * @see AccessCounter
 * @see com.vportal.portal.model.impl.AccessCounterImpl
 * @see com.vportal.portal.model.impl.AccessCounterModelImpl
 * @generated
 */
public interface AccessCounterModel extends BaseModel<AccessCounter> {
	/**
	 * Gets the primary key of this access counter.
	 *
	 * @return the primary key of this access counter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this access counter
	 *
	 * @param pk the primary key of this access counter
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the id of this access counter.
	 *
	 * @return the id of this access counter
	 */
	public long getId();

	/**
	 * Sets the id of this access counter.
	 *
	 * @param id the id of this access counter
	 */
	public void setId(long id);

	/**
	 * Gets the company id of this access counter.
	 *
	 * @return the company id of this access counter
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this access counter.
	 *
	 * @param companyId the company id of this access counter
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the access date of this access counter.
	 *
	 * @return the access date of this access counter
	 */
	public Date getAccessDate();

	/**
	 * Sets the access date of this access counter.
	 *
	 * @param accessDate the access date of this access counter
	 */
	public void setAccessDate(Date accessDate);

	/**
	 * Gets the access count of this access counter.
	 *
	 * @return the access count of this access counter
	 */
	public int getAccessCount();

	/**
	 * Sets the access count of this access counter.
	 *
	 * @param accessCount the access count of this access counter
	 */
	public void setAccessCount(int accessCount);

	/**
	 * Gets a copy of this access counter as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public AccessCounter toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AccessCounter accessCounter);

	public int hashCode();

	public String toString();

	public String toXmlString();
}