/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vsi.advertisement.portlet.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.vsi.advertisement.portlet.model.AdvItem;
import com.vsi.advertisement.portlet.service.AdvItemLocalService;
import com.vsi.advertisement.portlet.service.AdvItemService;
import com.vsi.advertisement.portlet.service.AdvTypeLocalService;
import com.vsi.advertisement.portlet.service.AdvTypeService;
import com.vsi.advertisement.portlet.service.persistence.AdvItemPersistence;
import com.vsi.advertisement.portlet.service.persistence.AdvTypePersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the adv item local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.vsi.advertisement.portlet.service.impl.AdvItemLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.vsi.advertisement.portlet.service.AdvItemLocalServiceUtil} to access the adv item local service.
 * </p>
 *
 * @author vinhnt
 * @see com.vsi.advertisement.portlet.service.impl.AdvItemLocalServiceImpl
 * @see com.vsi.advertisement.portlet.service.AdvItemLocalServiceUtil
 * @generated
 */
public abstract class AdvItemLocalServiceBaseImpl implements AdvItemLocalService {
	/**
	 * Adds the adv item to the database. Also notifies the appropriate model listeners.
	 *
	 * @param advItem the adv item to add
	 * @return the adv item that was added
	 * @throws SystemException if a system exception occurred
	 */
	public AdvItem addAdvItem(AdvItem advItem) throws SystemException {
		advItem.setNew(true);

		return advItemPersistence.update(advItem, false);
	}

	/**
	 * Creates a new adv item with the primary key. Does not add the adv item to the database.
	 *
	 * @param itemId the primary key for the new adv item
	 * @return the new adv item
	 */
	public AdvItem createAdvItem(long itemId) {
		return advItemPersistence.create(itemId);
	}

	/**
	 * Deletes the adv item with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param itemId the primary key of the adv item to delete
	 * @throws PortalException if a adv item with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteAdvItem(long itemId)
		throws PortalException, SystemException {
		advItemPersistence.remove(itemId);
	}

	/**
	 * Deletes the adv item from the database. Also notifies the appropriate model listeners.
	 *
	 * @param advItem the adv item to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteAdvItem(AdvItem advItem) throws SystemException {
		advItemPersistence.remove(advItem);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return advItemPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return advItemPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return advItemPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return advItemPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the adv item with the primary key.
	 *
	 * @param itemId the primary key of the adv item to get
	 * @return the adv item
	 * @throws PortalException if a adv item with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public AdvItem getAdvItem(long itemId)
		throws PortalException, SystemException {
		return advItemPersistence.findByPrimaryKey(itemId);
	}

	/**
	 * Gets a range of all the adv items.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of adv items to return
	 * @param end the upper bound of the range of adv items to return (not inclusive)
	 * @return the range of adv items
	 * @throws SystemException if a system exception occurred
	 */
	public List<AdvItem> getAdvItems(int start, int end)
		throws SystemException {
		return advItemPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of adv items.
	 *
	 * @return the number of adv items
	 * @throws SystemException if a system exception occurred
	 */
	public int getAdvItemsCount() throws SystemException {
		return advItemPersistence.countAll();
	}

	/**
	 * Updates the adv item in the database. Also notifies the appropriate model listeners.
	 *
	 * @param advItem the adv item to update
	 * @return the adv item that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public AdvItem updateAdvItem(AdvItem advItem) throws SystemException {
		advItem.setNew(false);

		return advItemPersistence.update(advItem, true);
	}

	/**
	 * Updates the adv item in the database. Also notifies the appropriate model listeners.
	 *
	 * @param advItem the adv item to update
	 * @param merge whether to merge the adv item with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the adv item that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public AdvItem updateAdvItem(AdvItem advItem, boolean merge)
		throws SystemException {
		advItem.setNew(false);

		return advItemPersistence.update(advItem, merge);
	}

	/**
	 * Gets the adv type local service.
	 *
	 * @return the adv type local service
	 */
	public AdvTypeLocalService getAdvTypeLocalService() {
		return advTypeLocalService;
	}

	/**
	 * Sets the adv type local service.
	 *
	 * @param advTypeLocalService the adv type local service
	 */
	public void setAdvTypeLocalService(AdvTypeLocalService advTypeLocalService) {
		this.advTypeLocalService = advTypeLocalService;
	}

	/**
	 * Gets the adv type remote service.
	 *
	 * @return the adv type remote service
	 */
	public AdvTypeService getAdvTypeService() {
		return advTypeService;
	}

	/**
	 * Sets the adv type remote service.
	 *
	 * @param advTypeService the adv type remote service
	 */
	public void setAdvTypeService(AdvTypeService advTypeService) {
		this.advTypeService = advTypeService;
	}

	/**
	 * Gets the adv type persistence.
	 *
	 * @return the adv type persistence
	 */
	public AdvTypePersistence getAdvTypePersistence() {
		return advTypePersistence;
	}

	/**
	 * Sets the adv type persistence.
	 *
	 * @param advTypePersistence the adv type persistence
	 */
	public void setAdvTypePersistence(AdvTypePersistence advTypePersistence) {
		this.advTypePersistence = advTypePersistence;
	}

	/**
	 * Gets the adv item local service.
	 *
	 * @return the adv item local service
	 */
	public AdvItemLocalService getAdvItemLocalService() {
		return advItemLocalService;
	}

	/**
	 * Sets the adv item local service.
	 *
	 * @param advItemLocalService the adv item local service
	 */
	public void setAdvItemLocalService(AdvItemLocalService advItemLocalService) {
		this.advItemLocalService = advItemLocalService;
	}

	/**
	 * Gets the adv item remote service.
	 *
	 * @return the adv item remote service
	 */
	public AdvItemService getAdvItemService() {
		return advItemService;
	}

	/**
	 * Sets the adv item remote service.
	 *
	 * @param advItemService the adv item remote service
	 */
	public void setAdvItemService(AdvItemService advItemService) {
		this.advItemService = advItemService;
	}

	/**
	 * Gets the adv item persistence.
	 *
	 * @return the adv item persistence
	 */
	public AdvItemPersistence getAdvItemPersistence() {
		return advItemPersistence;
	}

	/**
	 * Sets the adv item persistence.
	 *
	 * @param advItemPersistence the adv item persistence
	 */
	public void setAdvItemPersistence(AdvItemPersistence advItemPersistence) {
		this.advItemPersistence = advItemPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = advItemPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AdvTypeLocalService.class)
	protected AdvTypeLocalService advTypeLocalService;
	@BeanReference(type = AdvTypeService.class)
	protected AdvTypeService advTypeService;
	@BeanReference(type = AdvTypePersistence.class)
	protected AdvTypePersistence advTypePersistence;
	@BeanReference(type = AdvItemLocalService.class)
	protected AdvItemLocalService advItemLocalService;
	@BeanReference(type = AdvItemService.class)
	protected AdvItemService advItemService;
	@BeanReference(type = AdvItemPersistence.class)
	protected AdvItemPersistence advItemPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}