/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vfaq.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FAQAnswer service. Represents a row in the &quot;vfaq_FAQAnswer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vfaq.model.impl.FAQAnswerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vfaq.model.impl.FAQAnswerImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a f a q answer model instance should use the {@link FAQAnswer} interface instead.
 * </p>
 *
 * @author HOAN
 * @see FAQAnswer
 * @see com.vportal.portlet.vfaq.model.impl.FAQAnswerImpl
 * @see com.vportal.portlet.vfaq.model.impl.FAQAnswerModelImpl
 * @generated
 */
public interface FAQAnswerModel extends BaseModel<FAQAnswer> {
	/**
	 * Gets the primary key of this f a q answer.
	 *
	 * @return the primary key of this f a q answer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this f a q answer
	 *
	 * @param pk the primary key of this f a q answer
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the uuid of this f a q answer.
	 *
	 * @return the uuid of this f a q answer
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this f a q answer.
	 *
	 * @param uuid the uuid of this f a q answer
	 */
	public void setUuid(String uuid);

	/**
	 * Gets the id of this f a q answer.
	 *
	 * @return the id of this f a q answer
	 */
	public long getId();

	/**
	 * Sets the id of this f a q answer.
	 *
	 * @param id the id of this f a q answer
	 */
	public void setId(long id);

	/**
	 * Gets the questionid of this f a q answer.
	 *
	 * @return the questionid of this f a q answer
	 */
	public long getQuestionid();

	/**
	 * Sets the questionid of this f a q answer.
	 *
	 * @param questionid the questionid of this f a q answer
	 */
	public void setQuestionid(long questionid);

	/**
	 * Gets the content of this f a q answer.
	 *
	 * @return the content of this f a q answer
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this f a q answer.
	 *
	 * @param content the content of this f a q answer
	 */
	public void setContent(String content);

	/**
	 * Gets the answer order of this f a q answer.
	 *
	 * @return the answer order of this f a q answer
	 */
	public int getAnswerOrder();

	/**
	 * Sets the answer order of this f a q answer.
	 *
	 * @param answerOrder the answer order of this f a q answer
	 */
	public void setAnswerOrder(int answerOrder);

	/**
	 * Gets the answered by user of this f a q answer.
	 *
	 * @return the answered by user of this f a q answer
	 */
	@AutoEscape
	public String getAnsweredByUser();

	/**
	 * Sets the answered by user of this f a q answer.
	 *
	 * @param answeredByUser the answered by user of this f a q answer
	 */
	public void setAnsweredByUser(String answeredByUser);

	/**
	 * Gets the answered date of this f a q answer.
	 *
	 * @return the answered date of this f a q answer
	 */
	public Date getAnsweredDate();

	/**
	 * Sets the answered date of this f a q answer.
	 *
	 * @param answeredDate the answered date of this f a q answer
	 */
	public void setAnsweredDate(Date answeredDate);

	/**
	 * Gets the modified by user of this f a q answer.
	 *
	 * @return the modified by user of this f a q answer
	 */
	@AutoEscape
	public String getModifiedByUser();

	/**
	 * Sets the modified by user of this f a q answer.
	 *
	 * @param modifiedByUser the modified by user of this f a q answer
	 */
	public void setModifiedByUser(String modifiedByUser);

	/**
	 * Gets the language of this f a q answer.
	 *
	 * @return the language of this f a q answer
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this f a q answer.
	 *
	 * @param language the language of this f a q answer
	 */
	public void setLanguage(String language);

	/**
	 * Gets the modified date of this f a q answer.
	 *
	 * @return the modified date of this f a q answer
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this f a q answer.
	 *
	 * @param modifiedDate the modified date of this f a q answer
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the approved of this f a q answer.
	 *
	 * @return the approved of this f a q answer
	 */
	public boolean getApproved();

	/**
	 * Determines if this f a q answer is approved.
	 *
	 * @return <code>true</code> if this f a q answer is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Sets whether this {$entity.humanName} is approved.
	 *
	 * @param approved the approved of this f a q answer
	 */
	public void setApproved(boolean approved);

	/**
	 * Gets the approved by user of this f a q answer.
	 *
	 * @return the approved by user of this f a q answer
	 */
	@AutoEscape
	public String getApprovedByUser();

	/**
	 * Sets the approved by user of this f a q answer.
	 *
	 * @param approvedByUser the approved by user of this f a q answer
	 */
	public void setApprovedByUser(String approvedByUser);

	/**
	 * Gets the approved date of this f a q answer.
	 *
	 * @return the approved date of this f a q answer
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this f a q answer.
	 *
	 * @param approvedDate the approved date of this f a q answer
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Gets the user id of this f a q answer.
	 *
	 * @return the user id of this f a q answer
	 */
	public long getUserId();

	/**
	 * Sets the user id of this f a q answer.
	 *
	 * @param userId the user id of this f a q answer
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this f a q answer.
	 *
	 * @return the user uuid of this f a q answer
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this f a q answer.
	 *
	 * @param userUuid the user uuid of this f a q answer
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the attach name of this f a q answer.
	 *
	 * @return the attach name of this f a q answer
	 */
	@AutoEscape
	public String getAttachName();

	/**
	 * Sets the attach name of this f a q answer.
	 *
	 * @param attachName the attach name of this f a q answer
	 */
	public void setAttachName(String attachName);

	/**
	 * Gets the folder id of this f a q answer.
	 *
	 * @return the folder id of this f a q answer
	 */
	public long getFolderId();

	/**
	 * Sets the folder id of this f a q answer.
	 *
	 * @param folderId the folder id of this f a q answer
	 */
	public void setFolderId(long folderId);

	/**
	 * Gets a copy of this f a q answer as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public FAQAnswer toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FAQAnswer faqAnswer);

	public int hashCode();

	public String toString();

	public String toXmlString();
}