/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vadvman.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AdvType service. Represents a row in the &quot;AdvType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vadvman.model.impl.AdvTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vadvman.model.impl.AdvTypeImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a adv type model instance should use the {@link AdvType} interface instead.
 * </p>
 *
 * @author HOAN
 * @see AdvType
 * @see com.vportal.portlet.vadvman.model.impl.AdvTypeImpl
 * @see com.vportal.portlet.vadvman.model.impl.AdvTypeModelImpl
 * @generated
 */
public interface AdvTypeModel extends BaseModel<AdvType> {
	/**
	 * Gets the primary key of this adv type.
	 *
	 * @return the primary key of this adv type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this adv type
	 *
	 * @param pk the primary key of this adv type
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the type id of this adv type.
	 *
	 * @return the type id of this adv type
	 */
	public long getTypeId();

	/**
	 * Sets the type id of this adv type.
	 *
	 * @param typeId the type id of this adv type
	 */
	public void setTypeId(long typeId);

	/**
	 * Gets the create date of this adv type.
	 *
	 * @return the create date of this adv type
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this adv type.
	 *
	 * @param createDate the create date of this adv type
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this adv type.
	 *
	 * @return the modified date of this adv type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this adv type.
	 *
	 * @param modifiedDate the modified date of this adv type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the group id of this adv type.
	 *
	 * @return the group id of this adv type
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this adv type.
	 *
	 * @param groupId the group id of this adv type
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this adv type.
	 *
	 * @return the company id of this adv type
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this adv type.
	 *
	 * @param companyId the company id of this adv type
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the name of this adv type.
	 *
	 * @return the name of this adv type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this adv type.
	 *
	 * @param name the name of this adv type
	 */
	public void setName(String name);

	/**
	 * Gets the description of this adv type.
	 *
	 * @return the description of this adv type
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this adv type.
	 *
	 * @param description the description of this adv type
	 */
	public void setDescription(String description);

	/**
	 * Gets a copy of this adv type as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public AdvType toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AdvType advType);

	public int hashCode();

	public String toString();

	public String toXmlString();
}