/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vportal.portlet.vlinksman.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LinkGroup service. Represents a row in the &quot;LinkGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.vportal.portlet.vlinksman.model.impl.LinkGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.vportal.portlet.vlinksman.model.impl.LinkGroupImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a link group model instance should use the {@link LinkGroup} interface instead.
 * </p>
 *
 * @author hai
 * @see LinkGroup
 * @see com.vportal.portlet.vlinksman.model.impl.LinkGroupImpl
 * @see com.vportal.portlet.vlinksman.model.impl.LinkGroupModelImpl
 * @generated
 */
public interface LinkGroupModel extends BaseModel<LinkGroup> {
	/**
	 * Gets the primary key of this link group.
	 *
	 * @return the primary key of this link group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this link group
	 *
	 * @param pk the primary key of this link group
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the linkgroup id of this link group.
	 *
	 * @return the linkgroup id of this link group
	 */
	public long getLinkgroupId();

	/**
	 * Sets the linkgroup id of this link group.
	 *
	 * @param linkgroupId the linkgroup id of this link group
	 */
	public void setLinkgroupId(long linkgroupId);

	/**
	 * Gets the group id of this link group.
	 *
	 * @return the group id of this link group
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this link group.
	 *
	 * @param groupId the group id of this link group
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this link group.
	 *
	 * @return the company id of this link group
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this link group.
	 *
	 * @param companyId the company id of this link group
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the created date of this link group.
	 *
	 * @return the created date of this link group
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this link group.
	 *
	 * @param createdDate the created date of this link group
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Gets the modified date of this link group.
	 *
	 * @return the modified date of this link group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this link group.
	 *
	 * @param modifiedDate the modified date of this link group
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the name of this link group.
	 *
	 * @return the name of this link group
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this link group.
	 *
	 * @param name the name of this link group
	 */
	public void setName(String name);

	/**
	 * Gets the description of this link group.
	 *
	 * @return the description of this link group
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this link group.
	 *
	 * @param description the description of this link group
	 */
	public void setDescription(String description);

	/**
	 * Gets a copy of this link group as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public LinkGroup toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LinkGroup linkGroup);

	public int hashCode();

	public String toString();

	public String toXmlString();
}