/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;

import com.test.model.Vlookupprice;
import com.test.model.VlookuppriceModel;
import com.test.model.VlookuppriceSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the Vlookupprice service. Represents a row in the &quot;QuanTri_Vlookupprice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.test.model.VlookuppriceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VlookuppriceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a vlookupprice model instance should use the {@link com.test.model.Vlookupprice} interface instead.
 * </p>
 *
 * @author Long
 * @see VlookuppriceImpl
 * @see com.test.model.Vlookupprice
 * @see com.test.model.VlookuppriceModel
 * @generated
 */
public class VlookuppriceModelImpl extends BaseModelImpl<Vlookupprice>
	implements VlookuppriceModel {
	public static final String TABLE_NAME = "QuanTri_Vlookupprice";
	public static final Object[][] TABLE_COLUMNS = {
			{ "lookuppriceId", new Integer(Types.VARCHAR) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "createdByUser", new Integer(Types.VARCHAR) },
			{ "createdDate", new Integer(Types.TIMESTAMP) },
			{ "modifiedByUser", new Integer(Types.VARCHAR) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "status", new Integer(Types.INTEGER) },
			{ "price", new Integer(Types.INTEGER) },
			{ "position1", new Integer(Types.VARCHAR) },
			{ "position2", new Integer(Types.VARCHAR) },
			{ "position3", new Integer(Types.VARCHAR) },
			{ "position4", new Integer(Types.VARCHAR) },
			{ "position5", new Integer(Types.VARCHAR) },
			{ "title", new Integer(Types.VARCHAR) },
			{ "content", new Integer(Types.VARCHAR) },
			{ "parentId", new Integer(Types.VARCHAR) },
			{ "language", new Integer(Types.VARCHAR) },
			{ "listParent", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table QuanTri_Vlookupprice (lookuppriceId VARCHAR(75) not null primary key,groupId LONG,companyId LONG,createdByUser VARCHAR(75) null,createdDate DATE null,modifiedByUser VARCHAR(75) null,modifiedDate DATE null,status INTEGER,price INTEGER,position1 VARCHAR(75) null,position2 VARCHAR(75) null,position3 VARCHAR(75) null,position4 VARCHAR(75) null,position5 VARCHAR(75) null,title VARCHAR(75) null,content VARCHAR(75) null,parentId VARCHAR(75) null,language VARCHAR(75) null,listParent VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table QuanTri_Vlookupprice";
	public static final String ORDER_BY_JPQL = " ORDER BY vlookupprice.modifiedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY QuanTri_Vlookupprice.modifiedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.test.model.Vlookupprice"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.test.model.Vlookupprice"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Vlookupprice toModel(VlookuppriceSoap soapModel) {
		Vlookupprice model = new VlookuppriceImpl();

		model.setLookuppriceId(soapModel.getLookuppriceId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreatedByUser(soapModel.getCreatedByUser());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setModifiedByUser(soapModel.getModifiedByUser());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setPrice(soapModel.getPrice());
		model.setPosition1(soapModel.getPosition1());
		model.setPosition2(soapModel.getPosition2());
		model.setPosition3(soapModel.getPosition3());
		model.setPosition4(soapModel.getPosition4());
		model.setPosition5(soapModel.getPosition5());
		model.setTitle(soapModel.getTitle());
		model.setContent(soapModel.getContent());
		model.setParentId(soapModel.getParentId());
		model.setLanguage(soapModel.getLanguage());
		model.setListParent(soapModel.getListParent());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Vlookupprice> toModels(VlookuppriceSoap[] soapModels) {
		List<Vlookupprice> models = new ArrayList<Vlookupprice>(soapModels.length);

		for (VlookuppriceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.test.model.Vlookupprice"));

	public VlookuppriceModelImpl() {
	}

	public String getPrimaryKey() {
		return _lookuppriceId;
	}

	public void setPrimaryKey(String pk) {
		setLookuppriceId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return _lookuppriceId;
	}

	public String getLookuppriceId() {
		if (_lookuppriceId == null) {
			return StringPool.BLANK;
		}
		else {
			return _lookuppriceId;
		}
	}

	public void setLookuppriceId(String lookuppriceId) {
		_lookuppriceId = lookuppriceId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public String getCreatedByUser() {
		if (_createdByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdByUser;
		}
	}

	public void setCreatedByUser(String createdByUser) {
		_createdByUser = createdByUser;
	}

	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	public String getModifiedByUser() {
		if (_modifiedByUser == null) {
			return StringPool.BLANK;
		}
		else {
			return _modifiedByUser;
		}
	}

	public void setModifiedByUser(String modifiedByUser) {
		_modifiedByUser = modifiedByUser;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public int getStatus() {
		return _status;
	}

	public void setStatus(int status) {
		_status = status;
	}

	public int getPrice() {
		return _price;
	}

	public void setPrice(int price) {
		_price = price;
	}

	public String getPosition1() {
		if (_position1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _position1;
		}
	}

	public void setPosition1(String position1) {
		_position1 = position1;
	}

	public String getPosition2() {
		if (_position2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _position2;
		}
	}

	public void setPosition2(String position2) {
		_position2 = position2;
	}

	public String getPosition3() {
		if (_position3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _position3;
		}
	}

	public void setPosition3(String position3) {
		_position3 = position3;
	}

	public String getPosition4() {
		if (_position4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _position4;
		}
	}

	public void setPosition4(String position4) {
		_position4 = position4;
	}

	public String getPosition5() {
		if (_position5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _position5;
		}
	}

	public void setPosition5(String position5) {
		_position5 = position5;
	}

	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	public void setTitle(String title) {
		_title = title;
	}

	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	public void setContent(String content) {
		_content = content;
	}

	public String getParentId() {
		if (_parentId == null) {
			return StringPool.BLANK;
		}
		else {
			return _parentId;
		}
	}

	public void setParentId(String parentId) {
		_parentId = parentId;
	}

	public String getLanguage() {
		if (_language == null) {
			return StringPool.BLANK;
		}
		else {
			return _language;
		}
	}

	public void setLanguage(String language) {
		_language = language;
	}

	public String getListParent() {
		if (_listParent == null) {
			return StringPool.BLANK;
		}
		else {
			return _listParent;
		}
	}

	public void setListParent(String listParent) {
		_listParent = listParent;
	}

	public Vlookupprice toEscapedModel() {
		if (isEscapedModel()) {
			return (Vlookupprice)this;
		}
		else {
			return (Vlookupprice)Proxy.newProxyInstance(Vlookupprice.class.getClassLoader(),
				new Class[] { Vlookupprice.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		VlookuppriceImpl vlookuppriceImpl = new VlookuppriceImpl();

		vlookuppriceImpl.setLookuppriceId(getLookuppriceId());

		vlookuppriceImpl.setGroupId(getGroupId());

		vlookuppriceImpl.setCompanyId(getCompanyId());

		vlookuppriceImpl.setCreatedByUser(getCreatedByUser());

		vlookuppriceImpl.setCreatedDate(getCreatedDate());

		vlookuppriceImpl.setModifiedByUser(getModifiedByUser());

		vlookuppriceImpl.setModifiedDate(getModifiedDate());

		vlookuppriceImpl.setStatus(getStatus());

		vlookuppriceImpl.setPrice(getPrice());

		vlookuppriceImpl.setPosition1(getPosition1());

		vlookuppriceImpl.setPosition2(getPosition2());

		vlookuppriceImpl.setPosition3(getPosition3());

		vlookuppriceImpl.setPosition4(getPosition4());

		vlookuppriceImpl.setPosition5(getPosition5());

		vlookuppriceImpl.setTitle(getTitle());

		vlookuppriceImpl.setContent(getContent());

		vlookuppriceImpl.setParentId(getParentId());

		vlookuppriceImpl.setLanguage(getLanguage());

		vlookuppriceImpl.setListParent(getListParent());

		return vlookuppriceImpl;
	}

	public int compareTo(Vlookupprice vlookupprice) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(),
				vlookupprice.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Vlookupprice vlookupprice = null;

		try {
			vlookupprice = (Vlookupprice)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String pk = vlookupprice.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(39);

		sb.append("{lookuppriceId=");
		sb.append(getLookuppriceId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createdByUser=");
		sb.append(getCreatedByUser());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", modifiedByUser=");
		sb.append(getModifiedByUser());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", price=");
		sb.append(getPrice());
		sb.append(", position1=");
		sb.append(getPosition1());
		sb.append(", position2=");
		sb.append(getPosition2());
		sb.append(", position3=");
		sb.append(getPosition3());
		sb.append(", position4=");
		sb.append(getPosition4());
		sb.append(", position5=");
		sb.append(getPosition5());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", parentId=");
		sb.append(getParentId());
		sb.append(", language=");
		sb.append(getLanguage());
		sb.append(", listParent=");
		sb.append(getListParent());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(61);

		sb.append("<model><model-name>");
		sb.append("com.test.model.Vlookupprice");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>lookuppriceId</column-name><column-value><![CDATA[");
		sb.append(getLookuppriceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdByUser</column-name><column-value><![CDATA[");
		sb.append(getCreatedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedByUser</column-name><column-value><![CDATA[");
		sb.append(getModifiedByUser());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>price</column-name><column-value><![CDATA[");
		sb.append(getPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position1</column-name><column-value><![CDATA[");
		sb.append(getPosition1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position2</column-name><column-value><![CDATA[");
		sb.append(getPosition2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position3</column-name><column-value><![CDATA[");
		sb.append(getPosition3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position4</column-name><column-value><![CDATA[");
		sb.append(getPosition4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>position5</column-name><column-value><![CDATA[");
		sb.append(getPosition5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentId</column-name><column-value><![CDATA[");
		sb.append(getParentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>language</column-name><column-value><![CDATA[");
		sb.append(getLanguage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>listParent</column-name><column-value><![CDATA[");
		sb.append(getListParent());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _lookuppriceId;
	private long _groupId;
	private long _companyId;
	private String _createdByUser;
	private Date _createdDate;
	private String _modifiedByUser;
	private Date _modifiedDate;
	private int _status;
	private int _price;
	private String _position1;
	private String _position2;
	private String _position3;
	private String _position4;
	private String _position5;
	private String _title;
	private String _content;
	private String _parentId;
	private String _language;
	private String _listParent;
}